### ISSUE TITLE
import spex file throw the exception :No external document ref found for SPDX ID DocumentRef-sources

### ISSUE THREAD

**Issue by liuxihua** [DependencyTrack/dependency-track#1017]
Exception :
06:11:29.745 ERROR [BomUploadProcessingTask] Error while processing bom

org.dependencytrack.exception.ParseException: Unable to parse SPDX Document

at org.dependencytrack.parser.spdx.rdf.SpdxDocumentParser.parse(SpdxDocumentParser.java:127)

at org.dependencytrack.parser.spdx.rdf.SpdxDocumentParser.parse(SpdxDocumentParser.java:95)

at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:102)

at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

at java.base/java.lang.Thread.run(Unknown Source)

Caused by: java.lang.Exception: No external document ref found for SPDX ID DocumentRef-sources:SPDXRef-File-system-stm32f4xx.c

at org.spdx.tools.TagToRDF.convertTagFileToRdf(TagToRDF.java:231)

at org.dependencytrack.parser.spdx.rdf.SpdxDocumentParser.parse(SpdxDocumentParser.java:119)

... 6 common frames omitted

version : Dependency-Track  v4.2.1

SPDX file: https://github.com/swinslow/cmake-spdx/blob/master/example/build.spdx

**Comment by stevespringett** [comment]
According to the SPDX Tools online validator, the SPDX document referenced is invalid.

<img width="1674" alt="Screen Shot 2021-04-25 at 4 40 43 PM" src="https://user-images.githubusercontent.com/3878933/116010522-14345580-a5e5-11eb-80d2-21b1ed0098c9.png">

Please import a valid SPDX document.

**Comment by goneall** [comment]
I just submitted a [pull request to the CMAKE examples ](https://github.com/swinslow/cmake-spdx/pull/9) repo to resolve this issue.

**Comment by stevespringett** [comment]
Thanks @goneall

**Comment by liuxihua** [comment]
@goneall @stevespringett ， Thanks a lot
