### ISSUE TITLE
HikariPool-1 - Exception during pool initialization

### ISSUE THREAD

**Issue by rinkucool007** [DependencyTrack/dependency-track#1057]
Hi,
While running Dependency Track in a container it was running fine previously, but now it is not initializing :

2021-05-24 22:16:28,050 [] ERROR [com.zaxxer.hikari.pool.HikariPool] HikariPool-1 - Exception during pool initialization.
org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalStateException: Chunk 7870840 not found [1.4.200/9]" [50000-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.message.DbException.convert(DbException.java:347)
        at org.h2.engine.Database.openDatabase(Database.java:333)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
        at org.datanucleus.store.rdbms.connectionpool.HikariCPConnectionPoolFactory.createConnectionPool(HikariCPConnectionPoolFactory.java:171)
        at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSource(ConnectionFactoryImpl.java:259)
        at org.datanucleus.store.rdbms.ConnectionFactoryImpl.initialiseDataSource(ConnectionFactoryImpl.java:127)

**Comment by stevespringett** [comment]
`Chunk 7870840 not found` is a clue that the database has been corrupted. This can happen due to Dependency-Track upgrades, non-graceful shutdowns, or clients other than DT making connections to the database using a different JDBC driver version. For these reasons H2 is not recommended for production use.

https://docs.dependencytrack.org/getting-started/database-support/

See also: https://groups.google.com/forum/#!topic/h2-database/HZ1MRWhJ6H8

**Comment by rinkucool007** [comment]
Thanks, let me fix the DB.

**Comment by rinkucool007** [comment]
Is there any way to recover old data?

**Comment by stevespringett** [comment]
I'm not aware of any. But you may want to ask the H2 community and see if there's any solutions available.
