### ISSUE TITLE
EVENTSERVICELOG column ID does not exist

### ISSUE THREAD

**Issue by Orangenkopf** [DependencyTrack/dependency-track#1129]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
After upgrade from v4.2.2 to v4.3.0 DependencyTrack APISErver does not get into "started" mode, as it fails to write into the table EVENTSERVICELOG.
I did a downgrade to v4.2.2 on the same database and it works again.

### Steps to Reproduce:
Change your docker images to v4.3.0
docker-compose pull 
docker-compose up -d

### Expected Behavior:
Does not fail to write to database and start service

### Environment:
  
  - Dependency-Track Version: v4.3.0
  - Distribution: [ Docker ]
  - BOM Format & Version: none
  - Database Server: [PostgreSQL 13.0]
  - Browser:  Chrome

### Additional Details:
![image](https://user-images.githubusercontent.com/75792494/128004710-493fa3e5-b963-4c89-9e7f-3261ccb66ee2.png)
10:40:36.488 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
javax.jdo.JDODataStoreException: Insert of object "alpine.model.EventServiceLog@69536ae4" using statement "INSERT INTO "EVENTSERVICELOG" ("COMPLETED","STARTED","SUBSCRIBERCLASS") VALUES (?,?,?)" failed : ERROR: column ""ID"" does not exist
  Hint: Perhaps you meant to reference the column "EVENTSERVICELOG.ID".
  Position: 101
        at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:542)
        at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:720)
        at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:740)
        at alpine.persistence.AlpineQueryManager.createEventServiceLog(AlpineQueryManager.java:916)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:97)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: column ""ID"" does not exist
  Hint: Perhaps you meant to reference the column "EVENTSERVICELOG.ID".
  Position: 101
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
        at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
        at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:485)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
        at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4569)
        at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4546)
        at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2026)
        at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1869)
        at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1724)
        at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:715)
        ... 6 common frames omitted
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by csturiale** [comment]
Same problem here, using the docker.io/dependencytrack/apiserver:4.3.0 and docker.io/dependencytrack/apiserver:snapshot

**Comment by stevespringett** [comment]
Resolved in v4.3.1
