### ISSUE TITLE
Project creation API returns 500 error

### ISSUE THREAD

**Issue by beloglazov91** [DependencyTrack/dependency-track#1202]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
I call `PUT /v1/project`, pass `name`, `description`, `publisher`, `author`, `group` and `version` properties, but as result get `500 error`. Also project creates in dependency track, I see it when call `projects list` after that.

### Steps to Reproduce:
Create a new project via API.

### Expected Behavior:
Will be returned 200 code with project object.

### Environment:
  
  - Dependency-Track Version: 4.3.6
  - Distribution: Docker
  - Database Server: PostgreSQL

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
The UI makes this call to create a project as well and I haven't experienced any issues with it. Upon success, the server should return a 201. 

Can you provide the headers and body of the request please?

**Comment by beloglazov91** [comment]
@stevespringett See below the whole data:

> {
    "message": "Request failed with status code 500",
    "name": "Error",
    "stack": "Error: Request failed with status code 500\n    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:470:12)\n    at endReadableNT (internal/streams/readable.js:1317:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)",
    "config": {
        "url": "http://10.0.1.241:8080/api/v1/project",
        "method": "put",
        "data": "{\"author\":\"Alexey\",\"publisher\":\"Alexey\",\"group\":\"main\",\"name\":\"demo-x5\",\"description\":\"The test project.\",\"version\":\"1.0\",\"active\":true}",
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json",
            "X-Api-Key": "securekey",
            "User-Agent": "axios/0.21.4",
            "Content-Length": 136
        },
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        }
    }
}

**Comment by stevespringett** [comment]
The request appears to look good, but hard to say what axios is turning it into. Also, I just want to make sure that you're submitting the request to the API Server and not the frontend server correct?

**Comment by beloglazov91** [comment]
Sure, I submit the request to api server. Furthermore, the project is created after that request. But response contains status 500 and message about "server error".

I used 4.3.6 docker image and just ran it and submitted that request.

**Comment by beloglazov91** [comment]
@stevespringett I decided to try call "create project" via the dashboard and found out that the request has "CORS Error: missing allow origin header" error. All other requests in dashboard are working fine. I hope that will help you to reproduce a problem (api and frontend have different domains in my case).
