### ISSUE TITLE
Missing dependency signpost-core

### ISSUE THREAD

**Issue by perorope** [DependencyTrack/dependency-track#1349]
### Current Behavior:
Vulndb analyzer (vulndb-data-mirror) can not login to VulnDb

### Steps to Reproduce:
Start dt using docker compose
Login to dt
Define and enable vulndb analyzer
Create project using fromtend
Add component to the project with CPE defined

in dependency-tracker log:
21:07:53.744 INFO [VulnDbAnalysisTask] Starting VulnDB analysis task
21:07:53.751 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NoClassDefFoundError: oauth/signpost/exception/OAuthException
	at org.dependencytrack.tasks.scanners.VulnDbAnalysisTask.analyze(VulnDbAnalysisTask.java:115)
	at org.dependencytrack.tasks.scanners.VulnDbAnalysisTask.inform(VulnDbAnalysisTask.java:93)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.performAnalysis(VulnerabilityAnalysisTask.java:148)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.analyzeComponents(VulnerabilityAnalysisTask.java:115)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:69)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: oauth.signpost.exception.OAuthException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:538)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 9 common frames omitted

### Environment:
  
  - Dependency-Track Version: dependencytrack/apiserver 4.3.6
  - Distribution: Docker 
  - BOM Format & Version: --
  - Database Server: PostgreSQL
  - Browser: Chrome

### Additional Details:
Classpath is missing dependency signpost-core as it is dependency of vulndb-data-mirror.

21:07:53.744 INFO [VulnDbAnalysisTask] Starting VulnDB analysis task
21:07:53.751 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NoClassDefFoundError: oauth/signpost/exception/OAuthException
	at org.dependencytrack.tasks.scanners.VulnDbAnalysisTask.analyze(VulnDbAnalysisTask.java:115)
	at org.dependencytrack.tasks.scanners.VulnDbAnalysisTask.inform(VulnDbAnalysisTask.java:93)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.performAnalysis(VulnerabilityAnalysisTask.java:148)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.analyzeComponents(VulnerabilityAnalysisTask.java:115)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:69)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: oauth.signpost.exception.OAuthException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:538)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 9 common frames omitted\

**Comment by perorope** [comment]
Broken dependency:
transitive dependency of vuldb-data-mirror is 
<dependency>
            <groupId>com.konghq</groupId>
            <artifactId>unirest-java</artifactId>
            <version>2.3.17</version>
 </dependency>
but  dependency-tracker depends on  unirest 
<dependency>
            <groupId>com.konghq</groupId>
            <artifactId>unirest-java</artifactId>
            <version> 3.13.6.</version>
</dependency>

**Comment by stevespringett** [comment]
Ah yes, I'll need to update vulndb-data-mirror prior to the next DT release.
