### ISSUE TITLE
NullPointerException for users without Teams

### ISSUE THREAD

**Issue by valentijnscholten** [DependencyTrack/dependency-track#1524]
I started using the Portfolio Access Control and noticed that if you create a user which is not in any teams, this will lead to a NullPointerExceptions on opening the project as `userPrincipal.getTeams()` returns `null`;

```
2022-04-09 17:04:44,824 [] ERROR [alpine.server.resources.GlobalExceptionHandler] Uncaught internal server error
java.lang.NullPointerException: null
        at org.dependencytrack.persistence.ProjectQueryManager.hasAccess(ProjectQueryManager.java:669)
        at org.dependencytrack.persistence.QueryManager.hasAccess(QueryManager.java:282)
        at org.dependencytrack.resources.v1.MetricsResource.getProjectMetrics(MetricsResource.java:398)
        at org.dependencytrack.resources.v1.MetricsResource.getProjectMetricsXDays(MetricsResource.java:241)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

I am running the api server locally with `jetty`.

Not sure if this should be fixed in DT (check for `null`), or upstream in Alpine which contains the `UserPrincipal` class with the annotated relationship. 

https://github.com/DependencyTrack/dependency-track/blob/ad371d889606f8bbcffc584eaf9510c917bd9001/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java#L669

### Environment:
  
  - Dependency-Track Version: 4.5.0-SNAPSHOT https://github.com/DependencyTrack/dependency-track/commit/ad371d889606f8bbcffc584eaf9510c917bd9001
  - Distribution: jetty
  - BOM Format & Version: n/a
  - Database Server: H2
  - Browser: lynx

**Comment by stevespringett** [comment]
Thanks for reporting. Issue has been resolved.
