### ISSUE TITLE
NullPointerException on metrics update

### ISSUE THREAD

**Issue by valentijnscholten** [DependencyTrack/dependency-track#1525]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
```
2022-04-09 17:01:07,924 [] ERROR [org.dependencytrack.tasks.MetricsUpdateTask] An unexpected error occurred while updating portfolio metrics and iterating through projects. The error occurred while updating metrics for project: 00e9f228-3cbd-4f53-80ff-ded0ad0856f0
java.lang.NullPointerException: null
        at org.dependencytrack.tasks.MetricsUpdateTask.updateProjectMetrics(MetricsUpdateTask.java:365)
        at org.dependencytrack.tasks.MetricsUpdateTask.updatePortfolioMetrics(MetricsUpdateTask.java:105)
        at org.dependencytrack.tasks.MetricsUpdateTask.inform(MetricsUpdateTask.java:67)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Steps to Reproduce:
Create Project
Observe logs

### Expected Behavior:
No exceptions or at least nothing at ERROR level

Might not be a big problem as I think it only happens the first time metrics for a project are updated. Still might lead to false positives in error monitoring tools such as Sentry, New Relic, DataDog.

### Environment:
  
  - Dependency-Track Version: 4.5.0-SNAPSHOT https://github.com/DependencyTrack/dependency-track/commit/ad371d889606f8bbcffc584eaf9510c917bd9001
  - Distribution: jetty
  - BOM Format & Version: n/a
  - Database Server: H2
  - Browser: lynx

**Comment by nscuro** [comment]
Thanks for reporting @valentijnscholten! This one's on me, and is fixed in #1526. 

Do your null checks, kinds 🫠
