### ISSUE TITLE
Api Server Pod is not Starting and got stuck

### ISSUE THREAD

**Issue by nchennaboina** [DependencyTrack/dependency-track#1552]
The defect may already be reported! Please search for the defect before creating one.

### Environment: Dev
  
  - Dependency-Track Version: 4.4.2
  - Distribution: Azure Kubernetes 
  - BOM Format & Version: 
  - Database Server:  H2
  - Browser: chrome/mozila/IE

### Additional Details:

2022-04-18 14:33:23,943 INFO [EmbeddedJettyServer] Alpine Executable WAR v1.3.0 (49dc89aa-4f58-404e-b0d6-4001902c5fa1) built on: 2022-02-13T03:18:56Z
2022-04-18 14:33:25,298 INFO [Config] --------------------------------------------------------------------------------
2022-04-18 14:33:25,318 INFO [Config] OS Name:      Linux
2022-04-18 14:33:25,327 INFO [Config] OS Version:   5.4.0-1062-azure
2022-04-18 14:33:25,335 INFO [Config] OS Arch:      amd64
2022-04-18 14:33:25,343 INFO [Config] CPU Cores:    2
2022-04-18 14:33:25,359 INFO [Config] Max Memory:   4.0 GB (4,294,967,296.0 bytes)
2022-04-18 14:33:25,404 INFO [Config] Java Vendor:  Eclipse Adoptium
2022-04-18 14:33:25,449 INFO [Config] Java Version: 11.0.14.1+1
2022-04-18 14:33:25,459 INFO [Config] Java Home:    /opt/java/openjdk
2022-04-18 14:33:25,468 INFO [Config] Java Temp:    /tmp
2022-04-18 14:33:25,484 INFO [Config] User:         dtrack
2022-04-18 14:33:25,490 INFO [Config] User Home:    /data/
2022-04-18 14:33:25,496 INFO [Config] --------------------------------------------------------------------------------
2022-04-18 14:33:25,503 INFO [Config] Initializing Configuration
2022-04-18 14:33:25,510 INFO [Config] System property alpine.application.properties not specified
2022-04-18 14:33:25,516 INFO [Config] Loading application.properties from classpath
2022-04-18 14:33:25,552 INFO [Config] --------------------------------------------------------------------------------
2022-04-18 14:33:25,566 INFO [Config] Application:  Dependency-Track
2022-04-18 14:33:25,572 INFO [Config] Version:      4.4.2
2022-04-18 14:33:25,578 INFO [Config] Built-on:     2022-03-04T20:43:17Z
2022-04-18 14:33:25,584 INFO [Config] --------------------------------------------------------------------------------
2022-04-18 14:33:25,590 INFO [Config] Framework:    Alpine
2022-04-18 14:33:25,605 INFO [Config] Version :     1.10.5
2022-04-18 14:33:25,611 INFO [Config] Built-on:     2022-03-02T21:59:26Z
2022-04-18 14:33:25,618 INFO [Config] --------------------------------------------------------------------------------
2022-04-18 14:33:25,646 INFO [RequirementsVerifier] Initializing requirements verifier
2022-04-18 14:33:25,665 INFO [UpgradeInitializer] Initializing upgrade framework

**Comment by stevespringett** [comment]
H2 should not be used in production. Please refer to https://docs.dependencytrack.org/getting-started/database-support/

There's a high probability it will not be included at all in a future release.

**Comment by nchennaboina** [comment]
we are using in dev environment for evaluation purpose, not yet in production.

**Comment by nscuro** [comment]
Look for a file called `db.lock.mv` or so in your pod's `/data/.dependency-track` volume. Deleting it should fix the issue. Don't delete `db.mv.db` though, that's your actual database.

**Comment by nchennaboina** [comment]
Hi Niklas,

I haven't found that file but I have below logs files. Please let me know
which is the most recent log file so that I will export and provide it to
you for analysis.

[image: image.png]

Thanks & Regards,

*Narendra C*

*Mob :* +91 – 8983375514

      +91 – 9490979391

**Comment by nchennaboina** [comment]
there was no space left on the mounted path /data and now i have increased it from 5Gi to 11Gi, but i don`t see the application is coming online. 

Please suggest on the further steps.

**Comment by nchennaboina** [comment]
@nscuro -- could you please let me know how we can recover H2 DB? because i am seeing below logs from app logs.

2022-04-20 09:19:28,819 [] ERROR [alpine.upgrade.UpgradeMetaProcessor] An error occurred connecting to the database.
org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-200]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:222)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:182)
        at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:103)
        at org.h2.engine.Database.getPageStore(Database.java:2659)
        at org.h2.engine.Database.open(Database.java:675)
        at org.h2.engine.Database.openDatabase(Database.java:307)
        at org.h2.engine.Database.<init>(Database.java:301)
        at org.h2.engine.Engine.openSession(Engine.java:74)
        at org.h2.engine.Engine.openSession(Engine.java:192)
        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
        at org.h2.engine.Engine.createSession(Engine.java:166)
        at org.h2.engine.Engine.createSession(Engine.java:29)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
        at org.h2.Driver.connect(Driver.java:69)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at alpine.upgrade.UpgradeMetaProcessor.createConnection(UpgradeMetaProcessor.java:186)
        at alpine.upgrade.UpgradeMetaProcessor.<init>(UpgradeMetaProcessor.java:62)
        at org.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(UpgradeInitializer.java:53)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1043)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)
        at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:978)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:705)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:895)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
        at org.eclipse.jetty.server.Server.start(Server.java:469)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
        at org.eclipse.jetty.server.Server.doStart(Server.java:414)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
        at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:99)
Caused by: java.lang.IllegalStateException: File corrupted in chunk 7394175, expected page length 4..1536, got 1702000233 [1.4.200/6]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)
        at org.h2.mvstore.Chunk.readBufferForPage(Chunk.java:368)
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1214)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2209)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
        at org.h2.mvstore.Page.get(Page.java:222)
        at org.h2.mvstore.MVMap.get(MVMap.java:472)
        at org.h2.mvstore.MVMap.get(MVMap.java:459)
        at org.h2.mvstore.MVStore.getChunk(MVStore.java:1228)
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1214)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2209)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:672)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
        at org.h2.mvstore.CursorPos.traverseDown(CursorPos.java:58)
        at org.h2.mvstore.Cursor.traverseDown(Cursor.java:157)
        at org.h2.mvstore.Cursor.<init>(Cursor.java:31)
        at org.h2.mvstore.Cursor.<init>(Cursor.java:27)
        at org.h2.mvstore.MVMap.keyIterator(MVMap.java:699)
        at org.h2.mvstore.MVStore.scrubMetaMap(MVStore.java:427)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:410)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3579)
        at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:170)
        ... 36 common frames omitted

**Comment by nscuro** [comment]
As evident by the stacktrace, your database file is corrupted and needs recovery. H2 has a [recovery tool](http://www.h2database.com/html/advanced.html#using_recover_tool) for this. I haven't used it though, and I fear I also can't assist in restoring your DB. 

H2 is mainly meant to be used for local testing, but not for long-running instances, even if they are "test" or "pre-prod". Please consider using a dedicated database service like Postgres.
