### ISSUE TITLE
Upgrading from 4.2.2 to 4.3.0 fails with SQL error java.sql.SQLException: Incorrect string value: '\xEF\xBB\xBFins...' for column 'TEXT' at row 1

### ISSUE THREAD

**Issue by francisATgwn** [DependencyTrack/dependency-track#1610]
### Current Behavior:

apiserver won't start up all the way, gives a stack trace during startup while trying to update the LICENSE table. The apiserver _technically_ starts up as in it listens on port 8080, but it only gives 503 Service Unavailable

### Steps to Reproduce:

Upgrade from 4.2.2 to 4.3.0. Surely there is more to it than this, but I don't know what complicating factors are unique to our environment.

### Expected Behavior:

apiserver starts up successfully

### Environment:
  
  - Dependency-Track Version: 4.3.0
  - Distribution: Docker
  - BOM Format & Version: cyclonedx?
  - Database Server: MySQL
  - Browser:  Chrome

### Additional Details:

I started out by trying to upgrade from 4.2.2 to 4.4.2. We're using the docker compose provided in your documentation. The server was first created using 4.2.2 and this is its first upgrade. I worked backwards in versions until I could reliably reproduce by upgrading to 4.3.0. Downgrading to 4.2.2 after reproducing the error restored the expected functionality. I can flip back and forth between 4.2.2 and 4.3.0 which flips back and forth between working and not working, respectively.

```
~ # docker run --rm -it --env-file /etc/docker/compose/dependency-track/apiserver.env -p 8081:8080 -v dependency-track:/data dependencytrack/apiserver:4.3.0
^[[3~18:35:45.890 INFO [Config] --------------------------------------------------------------------------------
18:35:45.905 INFO [Config] OS Name:      Linux
18:35:45.909 INFO [Config] OS Version:   5.8.0-1041-aws
18:35:45.910 INFO [Config] OS Arch:      amd64
18:35:45.916 INFO [Config] CPU Cores:    2
18:35:45.979 INFO [Config] Max Memory:   6.1 GB (6,593,445,888.0 bytes)
18:35:45.983 INFO [Config] Java Vendor:  AdoptOpenJDK
18:35:45.987 INFO [Config] Java Version: 11.0.11+9
18:35:45.988 INFO [Config] Java Home:    /opt/java/openjdk
18:35:45.989 INFO [Config] Java Temp:    /tmp
18:35:45.989 INFO [Config] User:         dtrack
18:35:45.990 INFO [Config] User Home:    /data/
18:35:45.990 INFO [Config] --------------------------------------------------------------------------------
18:35:45.991 INFO [Config] Initializing Configuration
18:35:45.992 INFO [Config] System property alpine.application.properties not specified
18:35:45.992 INFO [Config] Loading application.properties from classpath
18:35:46.005 INFO [Config] --------------------------------------------------------------------------------
18:35:46.010 INFO [Config] Application:  Dependency-Track
18:35:46.011 INFO [Config] Version:      4.3.0
18:35:46.012 INFO [Config] Built-on:     2021-08-02T22:41:52Z
18:35:46.013 INFO [Config] --------------------------------------------------------------------------------
18:35:46.014 INFO [Config] Framework:    Alpine
18:35:46.015 INFO [Config] Version :     1.10.0
18:35:46.016 INFO [Config] Built-on:     2021-07-22T03:30:11Z
18:35:46.017 INFO [Config] --------------------------------------------------------------------------------
18:35:46.055 INFO [RequirementsVerifier] Initializing requirements verifier
18:35:46.056 INFO [UpgradeInitializer] Initializing upgrade framework
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
18:35:47.887 WARN [DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
18:35:47.945 WARN [DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
18:35:48.043 WARN [Datastore] Default type for java type of java.math.BigInteger was previously jdbc-type=NUMERIC but this is not provided by the JDBC driver! Please report this to the DataNucleus developers
18:35:50.970 INFO [PersistenceManagerFactory] Initializing persistence framework
18:35:51.140 WARN [DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
18:35:51.164 WARN [DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
18:35:51.180 WARN [Datastore] Default type for java type of java.math.BigInteger was previously jdbc-type=NUMERIC but this is not provided by the JDBC driver! Please report this to the DataNucleus developers
18:35:53.308 INFO [EventSubsystemInitializer] Initializing asynchronous event subsystem
18:35:53.613 INFO [DefaultObjectGenerator] Initializing default object generator
18:35:53.641 INFO [DefaultObjectGenerator] Synchronizing permissions to datastore
18:35:53.859 INFO [DefaultObjectGenerator] Synchronizing SPDX license definitions to datastore
18:35:55.960 ERROR [Persist] Update of object "org.dependencytrack.model.License@3f3c8b60" using statement "UPDATE "LICENSE" SET "TEMPLATE"=? WHERE "ID"=?" failed : java.sql.SQLException: Incorrect string value: '\xEF\xBB\xBFins...' for column 'TEMPLATE' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1350)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
        at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
        at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
        at org.datanucleus.store.rdbms.request.UpdateRequest.execute(UpdateRequest.java:452)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.updateObjectInTable(RDBMSPersistenceHandler.java:406)
        at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.updateObject(RDBMSPersistenceHandler.java:380)
        at org.datanucleus.state.StateManagerImpl.flush(StateManagerImpl.java:5838)
        at org.datanucleus.flush.FlushOrdered.execute(FlushOrdered.java:106)
        at org.datanucleus.ExecutionContextImpl.flushInternal(ExecutionContextImpl.java:4068)
        at org.datanucleus.ExecutionContextImpl.processNontransactionalAtomicChanges(ExecutionContextImpl.java:1409)
        at org.datanucleus.ExecutionContextImpl.processNontransactionalUpdate(ExecutionContextImpl.java:1370)
        at org.datanucleus.state.StateManagerImpl.setStringField(StateManagerImpl.java:2960)
        at org.dependencytrack.model.License.dnSettemplate(License.java)
        at org.dependencytrack.model.License.setTemplate(License.java:239)
        at org.dependencytrack.persistence.LicenseQueryManager.updateLicense(LicenseQueryManager.java:125)
        at org.dependencytrack.persistence.LicenseQueryManager.synchronizeLicense(LicenseQueryManager.java:147)
        at org.dependencytrack.persistence.QueryManager.synchronizeLicense(QueryManager.java:445)
        at org.dependencytrack.persistence.DefaultObjectGenerator.loadDefaultLicenses(DefaultObjectGenerator.java:125)
        at org.dependencytrack.persistence.DefaultObjectGenerator.contextInitialized(DefaultObjectGenerator.java:91)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1067)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:572)
        at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:996)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1449)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1414)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:423)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:387)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:98)

18:36:03.352 INFO [MetricsUpdateTask] Executing portfolio metrics update
18:36:03.354 INFO [MetricsUpdateTask] Executing metrics update on vulnerability database
18:36:03.573 INFO [NpmAdvisoryMirrorTask] Starting NPM advisory mirroring task
18:36:03.584 INFO [ClearComponentAnalysisCacheTask] Clearing ComponentAnalysisCache
18:36:03.612 INFO [ClearComponentAnalysisCacheTask] Complete
18:36:03.647 INFO [NpmAdvisoryMirrorTask] Retrieving NPM advisories at Wed May 11 18:36:03 GMT 2022
18:36:03.656 INFO [MetricsUpdateTask] Executing metrics update for project: 084531ee-4283-4b20-839f-5c42ca398734
18:36:04.134 INFO [MetricsUpdateTask] Completed metrics update for project: 084531ee-4283-4b20-839f-5c42ca398734
18:36:04.143 INFO [MetricsUpdateTask] Executing metrics update for project: 1d7cb8d9-b3e6-498e-98b1-237cc251e3ef
18:36:04.276 INFO [MetricsUpdateTask] Completed metrics update for project: 1d7cb8d9-b3e6-498e-98b1-237cc251e3ef
18:36:04.284 INFO [MetricsUpdateTask] Executing metrics update for project: 73f963ce-b4bc-448f-8d9e-df2d90991c4f
18:36:05.257 INFO [NpmAdvisoryMirrorTask] Retrieving NPM advisories from https://registry.npmjs.org/-/npm/v1/security/advisories
18:36:06.230 WARN [NpmAdvisoryMirrorTask] An unexpected response received from NPM while performing mirror. Response: 404 Not Found - Aborting
18:36:06.236 INFO [NpmAdvisoryMirrorTask] NPM advisory mirroring complete
18:36:11.701 INFO [MetricsUpdateTask] Completed metrics update for project: 73f963ce-b4bc-448f-8d9e-df2d90991c4f
18:36:11.710 INFO [MetricsUpdateTask] Executing metrics update for project: 9b1e75a9-ed2a-4a5c-bd8c-eed1aae216ef
18:36:24.853 INFO [MetricsUpdateTask] Completed metrics update for project: 9b1e75a9-ed2a-4a5c-bd8c-eed1aae216ef
18:36:24.863 INFO [MetricsUpdateTask] Executing metrics update for project: b5016662-693b-4574-bfba-28f9060646e6
18:36:26.926 INFO [MetricsUpdateTask] Completed metrics update for project: b5016662-693b-4574-bfba-28f9060646e6
18:36:26.936 INFO [MetricsUpdateTask] Executing metrics update for project: 633bfe40-34f7-419c-8a45-93645a07ff47
18:36:33.403 INFO [MetricsUpdateTask] Completed metrics update for project: 633bfe40-34f7-419c-8a45-93645a07ff47
18:36:33.412 INFO [MetricsUpdateTask] Executing metrics update for project: 504ae6a1-cd2a-45bf-894d-0c61f1964cc0
18:36:40.399 INFO [MetricsUpdateTask] Completed metrics update for project: 504ae6a1-cd2a-45bf-894d-0c61f1964cc0
18:36:40.406 INFO [MetricsUpdateTask] Executing metrics update for project: fd952ac5-1507-4898-8e90-2661f0013929
18:36:42.524 INFO [MetricsUpdateTask] Completed metrics update for project: fd952ac5-1507-4898-8e90-2661f0013929
18:36:42.534 INFO [MetricsUpdateTask] Executing metrics update for project: 305e397d-442f-4bd2-ab6a-2eb1277f7afd
^CShutting down application
```

It initially gave the same error on the TEXT column, but those logs are lost in my terminal scrollback due to troubleshooting.

Our database expert helped me troubleshoot and we found the following.

Initially, the columns `TEXT` and `TEMPLATE` on the `LICENSE` table were set to `mediumtext` with collation `latin1_swedish_ci`. We suspected this has to do with why the UTF-8 BOM was being rejected.

We tried executing the following command:

```
ALTER TABLE LICENSE MODIFY
    TEXT mediumtext
        CHARACTER SET latin1
        COLLATE latin1_bin
        NOT NULL;
```

No dice, the error still occurred. Then we tried the following:

```
ALTER TABLE LICENSE MODIFY
    TEXT text;
```

again, no dice, the error still occurred. I did find 2 entries in that table with lots of `?` in their TEXT field; so maybe those bits of existing data were problematic for 4.3.0 to deal with.

Finally, we tried the following:

```
ALTER TABLE LICENSE MODIFY
    TEXT text
        CHARACTER SET utf8mb4;
```

This changed the stack trace so it was now for the `TEMPLATE` field; the stack trace I pasted above. Same command for TEMPLATE and that resolved the issue. The server starts up as expected. I repeated with 4.4.2 and it also works as expected. I am able to log in and see all the projects on the dashboard.

The schema now looks like this:

```
SHOW FULL COLUMNS FROM LICENSE;
+---------------+--------------+--------------------+------+-----+---------+----------------+---------------------------------+---------+
| Field         | Type         | Collation          | Null | Key | Default | Extra          | Privileges                      | Comment |
+---------------+--------------+--------------------+------+-----+---------+----------------+---------------------------------+---------+
| ID            | bigint(20)   | NULL               | NO   | PRI | NULL    | auto_increment | select,insert,update,references |         |
| COMMENT       | mediumtext   | latin1_swedish_ci  | YES  |     | NULL    |                | select,insert,update,references |         |
| ISDEPRECATED  | bit(1)       | NULL               | NO   |     | NULL    |                | select,insert,update,references |         |
| FSFLIBRE      | bit(1)       | NULL               | YES  |     | NULL    |                | select,insert,update,references |         |
| HEADER        | mediumtext   | latin1_swedish_ci  | YES  |     | NULL    |                | select,insert,update,references |         |
| LICENSEID     | varchar(255) | latin1_bin         | YES  | UNI | NULL    |                | select,insert,update,references |         |
| NAME          | varchar(255) | latin1_bin         | NO   | MUL | NULL    |                | select,insert,update,references |         |
| ISOSIAPPROVED | bit(1)       | NULL               | NO   |     | NULL    |                | select,insert,update,references |         |
| SEEALSO       | mediumblob   | NULL               | YES  |     | NULL    |                | select,insert,update,references |         |
| TEMPLATE      | text         | utf8mb4_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| TEXT          | text         | utf8mb4_general_ci | YES  |     | NULL    |                | select,insert,update,references |         |
| UUID          | varchar(36)  | latin1_bin         | NO   | UNI | NULL    |                | select,insert,update,references |         |
+---------------+--------------+--------------------+------+-----+---------+----------------+---------------------------------+---------+
```

**Comment by stevespringett** [comment]
Sounds about right. The docs specifically state that if UTF-8 is required, do not use MySQL, as there are multiple issues with it. The license table is one of them. One other user is doing some research into getting modern versions of MySQL and MariaDB working. It's a bit of a hack, but he's been able to do it, and to my knowledge, does require manual database schema manipulation, similar to what you've done here.

**Comment by francisATgwn** [comment]
We are considering migrating to postgres. Is there a documented process for this?

**Comment by nscuro** [comment]
UTF-8 in MySQL is a painful experience without the required expertise (speaking from experience, I migrated to PostgreSQL due to this). You'll run into more of these issues once UTF-8 characters are to be inserted into indexed columns, which yields KeyLengthViolation errors.

As Steve points out, another user posted a very detailed guide here that may be of interest: https://github.com/DependencyTrack/dependency-track/issues/271#issuecomment-1108923693

**Comment by francisATgwn** [comment]
One of the frustrating things here is that I don't know where the UTF-8 is coming from. I expect it's from some external data source, some vulnerability database, that was introduced in 4.3.0. Again, switching back to 4.2.2 we do not see the error, so there's something in 4.3.0 that is a complicating factor.

**Comment by nscuro** [comment]
> @francisATgwn We are considering migrating to postgres. Is there a documented process for this?

Yeah, kinda. I wrote one way back when for DT 4.2.2: https://gist.github.com/nscuro/1d32c6099a8a82f98f737fffa936b416#file-instructions-md

The migrated instance has been running without issues ever since.

> One of the frustrating things here is that I don't know where the UTF-8 is coming from.

External data. If it's not licenses, it will be vulnerability descriptions, titles, what have you. 

> Again, switching back to 4.2.2 we do not see the error, so there's something in 4.3.0 that is a complicating factor.

I've had this kind of issue with 4.2.2. I don't think it's related to the version.

**Comment by francisATgwn** [comment]
Thank you both for the quick response.

My personal opinion is that, given the nature of what dependency track does, pulling from such a variety of data sources, UTF-8 is inevitable. So, if UTF-8 isn't a good experience out of the box on mysql then mysql shouldn't be listed as a supported database. Deploying this into AWS I look at cost chart and see that postgres-compatible aurora's minimum instance type is more expensive than mysql-compatible aurora; I see that dependency track supports mysql 5.7; so that's what I deploy.

I'm satisfied that this is a known issue and if you don't intend to do anything about it, that's fine, we understand the risk we're taking by continuing to run mysql and you can go ahead and close this issue.
