### ISSUE TITLE
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption

### ISSUE THREAD

**Issue by taicomjp** [DependencyTrack/dependency-track#1636]
### Current Behavior:
SQL connect will fail and show "The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption"
but encrypt=false will work 
seem current jdbc mssql driver not support ssl encryption

### Steps to Reproduce:
docker-compose.yml
     - ALPINE_DATABASE_MODE=external
     - ALPINE_DATABASE_URL=jdbc:sqlserver://x.x.x.x:1433;databaseName=dtrack;encrypt=true
     - ALPINE_DATABASE_DRIVER=com.microsoft.sqlserver.jdbc.SQLServerDriver
     - ALPINE_DATABASE_USERNAME=xxxxxx
     - ALPINE_DATABASE_PASSWORD=xxxxxx

### Expected Behavior:
encrypt=true

### Environment:
  - Dependency-Track Version:4.5.0
  - Distribution: Docker
  - Database Server: MSSQL 2019

### Additional Details:

ERROR [UpgradeMetaProcessor] An error occurred connecting to the database.

com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target". ClientConnectionId:d82b4a01-7115-48da-9fda-11d151779a52

at com.microsoft.sqlserver.jdbc.SQLServerConnection.terminate(SQLServerConnection.java:3779)

at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1884)

at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3302)

at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2923)

at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2763)

at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1657)

at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1063)

at java.sql/java.sql.DriverManager.getConnection(Unknown Source)

at java.sql/java.sql.DriverManager.getConnection(Unknown Source)

at alpine.server.upgrade.UpgradeMetaProcessor.createConnection(UpgradeMetaProcessor.java:187)

at alpine.server.upgrade.UpgradeMetaProcessor.<init>(UpgradeMetaProcessor.java:63)

at org.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(UpgradeInitializer.java:54)

at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1043)

at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)

at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:978)

at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:705)

at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)

at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)

at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:895)

at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)

at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)

at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)

at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)

at org.eclipse.jetty.server.Server.start(Server.java:469)

at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)

at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)

at org.eclipse.jetty.server.Server.doStart(Server.java:414)

at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)

at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:100)

Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)

at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)

at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)

at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)

at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(Unknown Source)

at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(Unknown Source)

at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(Unknown Source)

at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)

at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)

at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)

at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)

at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)

at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)

at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)

at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)

at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)

at com.microsoft.sqlserver.jdbc.TDSChannel.enableSSL(IOBuffer.java:1783)

... 27 common frames omitted

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)

at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)

at java.base/sun.security.validator.Validator.validate(Unknown Source)

at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)

at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)

at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)

at com.microsoft.sqlserver.jdbc.HostNameOverrideX509TrustManager.checkServerTrusted(SQLServerTrustManager.java:86)

at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(Unknown Source)

... 40 common frames omitted

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)

at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)

at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)

... 48 common frames omitted

**Comment by nscuro** [comment]
Hi @taicomjp 👋

Encryption is indeed working, it's just that whatever certificate your database is offering cannot be trusted by your Dependency-Track instance. Possibly because it was generated automatically by your SQL Server instance and not signed by any Certificate Authority trusted by DT.

Two possible solutions:
* Add `trustServerCertificate=true` in your connection string (see https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-with-ssl-encryption?view=sql-server-ver15#configuring-the-connection)
* Add the certificate or CA that signed your certificate to DT's trust store

The latter requires you to either
* Build a custom container
* Mount your own trust store into the container at `/opt/java/openjdk/lib/security/cacerts`

**Comment by taicomjp** [comment]
thanks  @nscuro
Add trustServerCertificate=true work fine
