### ISSUE TITLE
Emails are not sent in DT.

### ISSUE THREAD

**Issue by jayachathu** [DependencyTrack/dependency-track#1817]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior
I added a gmail address as email receiver. But I could not see the email after a DT analysis is done

### Steps to Reproduce:
Add a project and jenkins upload can create different versions for each upload.
Create an email notification to be sent for all the projects.
Add all the Group in the email configurations (BOM_PROCESS etc)
Then upload a bom from Jenkins.
After analsis complete, no email is sent.

### Expected Behavior:
After analysis complete, an email should be sent.

### Environment:
  
  - Dependency-Track Version: latest
  - Distribution: [ Docker  ]
  - BOM Format & Version:  CycloneDX  "specVersion": "1.4",
    "version": 1,
  - Database Server: [ PostgreSQL ]
  - Browser: Chrome

**Comment by stevespringett** [comment]
What do the logs say?

**Comment by msymons** [comment]
...and what happens when you use the "Configuration Test" button  (Administration -> Configuration -> Email)?

**Comment by redaabdellah21** [comment]
Are you sure this is not related to your company's proxy? I had a problem with this when sending an email.

**Comment by jayachathu** [comment]
Below is the error I received.

Caused by: javax.mail.SendFailedException: Invalid Addresses
	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:2064)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1286)
	at javax.mail.Transport.send0(Transport.java:231)
	at javax.mail.Transport.send(Transport.java:100)
	at alpine.server.mail.SendMail.send(SendMail.java:239)
	... 71 common frames omitted
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.7.64 TenantAttribution; Relay Access Denied [TYCJPN01FT027.eop-JPN01.prod.protection.outlook.com]

	at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1917)
	... 75 common frames omitted

**Comment by jayachathu** [comment]
I got it solved. thanks
