### ISSUE TITLE
Too large evidence value for the database schema

### ISSUE THREAD

**Issue by jblamotte** [DependencyTrack/dependency-track#182]
### Issue Type:
  - [x] defect report
  - [ ] enhancement request
  
### Current Behavior:
When analysing a dependency-check-report.xml with large evidence value, the analysis fail.

### Steps to Reproduce (if defect):
Analyse a dependency-check.xml with a very large evidence value (> 4096)

### Expected Behavior:
Evidence reported, or at least truncated. And a non blocking analysis ;)
Use a text field, with no size limitation, even if it fragment database ? or truncate ?

### Environment:
  
  - Dependency-Track Version: 3.1.1
  - Distribution: [Executable WAR]
  - BoM Format & Version: dependency-check.xml engineVersion 3.2.1
  - Database Server: [MySQL]
  - Browser: 

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Caused by: org.datanucleus.exceptions.NucleusUserException: Attempt to store value "TRUNCATED here ... long text...  ," in column ""VALUE"" that has maximum length of 4096. Please correct your data!
	at org.datanucleus.store.rdbms.mapping.datastore.CharRDBMSMapping.setString(CharRDBMSMapping.java:253)
	at org.datanucleus.store.rdbms.mapping.java.SingleFieldMapping.setString(SingleFieldMapping.java:180)
	at org.datanucleus.store.rdbms.fieldmanager.ParameterSetter.storeStringField(ParameterSetter.java:158)
	at org.datanucleus.state.StateManagerImpl.providedStringField(StateManagerImpl.java:1811)
	at org.owasp.dependencytrack.model.Evidence.dnProvideField(Evidence.java)
	at org.owasp.dependencytrack.model.Evidence.dnProvideFields(Evidence.java)
	at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:2510)
	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:307)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4551)
	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4528)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2025)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1868)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1723)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
	... 11 common frames omitted

**Comment by stevespringett** [comment]
Looks like one of the fields in the dependency-check report is too long to fit into the database. Usually this is a description field.

Can you attach the xml report you're uploading please. If your unable to publicly share, consider sending it to steve.springett@owasp.org or a secure file drop service.

**Comment by jblamotte** [comment]
In copy, an extract of the dependency-check-report.xml producing the error. (.txt because github doesn't accept xml)

I think you can probably truncate the value.

[dependency-check-report-minimal.xml.txt](https://github.com/DependencyTrack/dependency-track/files/2257924/dependency-check-report-minimal.xml.txt)

**Comment by stevespringett** [comment]
@jblamotte thanks for providing the extract. I've confirmed the issue and have checked-in a fix that will account for extra-large fields in all the String/CLOB fields in the Component and Evidence model classes.

**Comment by jblamotte** [comment]
Just tested 3.2. 
Issue solved, indeed :)
