### ISSUE TITLE
Relation "schemaversion" does not exist on postgresql database server

### ISSUE THREAD

**Issue by devqore** [DependencyTrack/dependency-track#188]
### Issue Type:
  - defect report
  
### Current Behavior:
Each start of DependencyTrack on postgresql database starts with exception in log:

```
18:10:35.140 INFO [Config] --------------------------------------------------------------------------------
18:10:35.140 INFO [Config] Initializing Configuration
18:10:35.150 INFO [Config] Loading application properties from /home/someone/.dependency-track/application.properties
18:10:35.152 INFO [Config] --------------------------------------------------------------------------------
18:10:35.152 INFO [Config] Application: Dependency-Track
18:10:35.152 INFO [Config] Version:     3.1.1
18:10:35.152 INFO [Config] Built-on:    2018-06-20 20:00:54
18:10:35.152 INFO [Config] --------------------------------------------------------------------------------
18:10:35.152 INFO [Config] Framework:   Alpine
18:10:35.152 INFO [Config] Version :    1.2.0
18:10:35.152 INFO [Config] Built-on:    2018-06-19 05:32:11
18:10:35.152 INFO [Config] --------------------------------------------------------------------------------
18:10:35.263 INFO [PersistenceManagerFactory] Initializing persistence framework
18:10:35.264 INFO [Config] Expanding classpath to include: /home/someone/.dependency-track/postgresql-42.2.4.jar
18:10:36.688 ERROR [UpgradeExecutor] Failed to update schema version
org.postgresql.util.PSQLException: ERROR: relation "schemaversion" does not exist
  Pozycja: 21
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:150)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:113)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at alpine.upgrade.UpgradeMetaProcessor.updateSchemaVersion(UpgradeMetaProcessor.java:136)
	at alpine.upgrade.UpgradeExecutor.executeUpgrades(UpgradeExecutor.java:76)
	at org.owasp.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(UpgradeInitializer.java:39)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:890)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:558)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:853)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:370)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:785)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:287)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:419)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:386)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:71)
18:10:36.695 INFO [DefaultObjectGenerator] Synchronizing permissions to datastore.
18:10:37.059 INFO [DefaultObjectGenerator] Adding default users and teams to datastore.
...
```

### Steps to Reproduce:

```
$ rm -rf ~/.dependency-track
$ mkdir ~/.dependency-track

$ wget -c https://jdbc.postgresql.org/download/postgresql-42.2.4.jar -O ~/.dependency-track/postgresql-42.2.4.jar
$ wget -c https://github.com/DependencyTrack/dependency-track/releases/download/3.1.1/dependency-track-embedded.war

$ cat >~/.dependency-track/application.properties <<EOM
alpine.worker.threads=0
alpine.worker.thread.multiplier=4
alpine.data.directory=~/.dependency-track
alpine.watchdog.logging.interval=0
alpine.database.mode=external
alpine.database.url=jdbc:postgresql://localhost:5432/postgres
alpine.database.driver=org.postgresql.Driver
alpine.database.driver.path=~/.dependency-track/postgresql-42.2.4.jar
alpine.database.username=postgres
alpine.database.password=dt
alpine.enforce.authentication=true
alpine.enforce.authorization=true
alpine.bcrypt.rounds=14
alpine.ldap.enabled=false
EOM

# clean database from container, tested also on clean postgresql 9.2 from official centos 7 repository
$ docker run --name postgres -e POSTGRES_PASSWORD=dt -p 5432:5432 -d postgres:9.3

# for me home must be given as absolute path
$ java -jar -Xmx4G -Dalpine.application.properties=/home/someone/.dependency-track/application.properties dependency-track-embedded.war
```

### Expected Behavior:
No error in log.

### Environment:
  - Dependency-Track Version: 3.1.1
  - Distribution: tested on: Executable WAR and Traditional WAR 
  - Database Server:  PostgreSQL 9.3 from docker like above and postgresql 9.2 - default version from centos 7

**Comment by stevespringett** [comment]
This was recently fixed in https://github.com/stevespringett/Alpine/commit/167985c6d661993833b6d3f6e28384b237eebbd6


The issue only affects Postgres users. Folks using MySQL, MSSQL, or H2 are unaffected. If the database started out using Dependency-Track v3.0.0, then there may be a few issues with regards to Portfolio Metrics. If the database started out as v3.1.0 there's nothing to worry about. You can safely ignore the error and when you upgrade to 3.2.0 when it's released, the error will go away and the upgrades will be successful.

**Comment by devqore** [comment]
Thank you for quick response. I verified on DependencyTrack master (47ed5ce1ca7f57a7e3270c1d177dcfb07e9eee27) and looks good :)
