### ISSUE TITLE
ERROR [MavenMetaAnalyzer] Request failure

### ISSUE THREAD

**Issue by sgupta22altair** [DependencyTrack/dependency-track#1976]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:22,284 INFO [InternalAnalysisTask] Starting internal analysis task
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:22,378 INFO [InternalAnalysisTask] Internal analysis complete
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:22,380 WARN [OssIndexAnalysisTask] An API username or token has not been specified for use with OSS Index. Using anonymous access
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:22,380 INFO [OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:24,940 INFO [OssIndexAnalysisTask] Analyzing 100 component(s)
**sahil-dtrack-apiserver-1  | 2022-09-22 16:17:25,012 ERROR [MavenMetaAnalyzer] Request failure
sahil-dtrack-apiserver-1  | java.net.SocketTimeoutException: Read timed out**
sahil-dtrack-apiserver-1  |     at java.base/java.net.SocketInputStream.socketRead0(Native Method)
sahil-dtrack-apiserver-1  |     at java.base/java.net.SocketInputStream.socketRead(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.net.SocketInputStream.read(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.net.SocketInputStream.read(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
sahil-dtrack-apiserver-1  |     at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
sahil-dtrack-apiserver-1  |     at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
sahil-dtrack-apiserver-1  |     at org.dependencytrack.tasks.repositories.MavenMetaAnalyzer.analyze(MavenMetaAnalyzer.java:85)
sahil-dtrack-apiserver-1  |     at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.analyze(RepositoryMetaAnalyzerTask.java:85)
sahil-dtrack-apiserver-1  |     at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.inform(RepositoryMetaAnalyzerTask.java:50)
sahil-dtrack-apiserver-1  |     at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
sahil-dtrack-apiserver-1  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.lang.Thread.run(Unknown Source)
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:26,081 INFO [OssIndexAnalysisTask] Analyzing 100 component(s)
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:27,182 INFO [OssIndexAnalysisTask] Analyzing 100 component(s)
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:28,122 INFO [OssIndexAnalysisTask] Analyzing 100 component(s)
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:29,278 INFO [OssIndexAnalysisTask] Analyzing 100 component(s)
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:30,126 INFO [OssIndexAnalysisTask] Analyzing 72 component(s)
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:30,126 INFO [OssIndexAnalysisTask] Sonatype OSS Index analysis complete
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:30,132 INFO [PolicyEngine] Evaluating 572 component(s) against applicable policies
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:30,582 INFO [PolicyEngine] Policy analysis complete
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:30,582 INFO [MetricsUpdateTask] Executing metrics update for project: 545ac2d3-e8b2-4597-9e2e-d97c877c8443
sahil-dtrack-apiserver-1  | 2022-09-22 16:17:31,628 INFO [MetricsUpdateTask] Completed metrics update for project: 545ac2d3-e8b2-4597-9e2e-d97c877c8443
**sahil-dtrack-apiserver-1  | 2022-09-22 16:17:59,424 ERROR [MavenMetaAnalyzer] Request failure
sahil-dtrack-apiserver-1  | org.apache.http.conn.HttpHostConnectException: Connect to repo1.maven.org:443** [repo1.maven.org/199.232.196.209, repo1.maven.org/199.232.192.209] failed: Connection refused (Connection refused)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
sahil-dtrack-apiserver-1  |     at org.dependencytrack.tasks.repositories.MavenMetaAnalyzer.analyze(MavenMetaAnalyzer.java:85)
sahil-dtrack-apiserver-1  |     at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.analyze(RepositoryMetaAnalyzerTask.java:85)
sahil-dtrack-apiserver-1  |     at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.inform(RepositoryMetaAnalyzerTask.java:50)
sahil-dtrack-apiserver-1  |     at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
sahil-dtrack-apiserver-1  |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.lang.Thread.run(Unknown Source)
sahil-dtrack-apiserver-1  | Caused by: java.net.ConnectException: Connection refused (Connection refused)
sahil-dtrack-apiserver-1  |     at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
sahil-dtrack-apiserver-1  |     at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
sahil-dtrack-apiserver-1  |     at java.base/java.net.Socket.connect(Unknown Source)
sahil-dtrack-apiserver-1  |     at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
sahil-dtrack-apiserver-1  |     at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
sahil-dtrack-apiserver-1  |     ... 16 common frames omitted

### Steps to Reproduce:
I have uploaded an SBOM generated by Cyclodex Maven plugin that contain 564 libraries

### Expected Behavior:

Error in logs while uploading SBOM in Dependency track
2022-09-22 16:17:59,424 ERROR [MavenMetaAnalyzer] Request failure
sahil-dtrack-apiserver-1  | org.apache.http.conn.HttpHostConnectException: Connect to repo1.maven.org:443 [repo1.maven.org/199.232.196.209, repo1.maven.org/199.232.192.209] failed: Connection refused (Connection refused)
2022-09-22 16:17:25,012 ERROR [MavenMetaAnalyzer] Request failure
sahil-dtrack-apiserver-1  | java.net.SocketTimeoutException: Read timed out

**and Dependency track is unable to identify vulnerabilities**

### Environment:
  
  - Dependency-Track Version: v4.5.0
  - Distribution: Docker
  - BOM Format & Version: Cyclonedx 1.3
  - Database Server: H2
  - Browser: Chrome

**Comment by nscuro** [comment]
Hi @sgupta22altair, 

connection resets and read timeouts are network issues that Dependency-Track can't do anything about. If you're running DT inside a corporate network, maybe you need to setup a proxy? See https://docs.dependencytrack.org/getting-started/configuration/#proxy-configuration

**Comment by sbpoc2022** [comment]
I have the same issue. I know my proxy connection works bcoz DT can pull updates from Github advisory, but when analyzing BOM using Sonatype analyzer it fails. Is there a DT environment property where external analyzer RESTful endpoints can be checked?

2022-10-04 19:05:12,655 INFO [OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
2022-10-04 19:05:12,926 ERROR [OssIndexAnalysisTask] Request failure
kong.unirest.UnirestException: java.net.SocketException: Connection reset
	at kong.unirest.DefaultInterceptor.onFail(DefaultInterceptor.java:43)
	at kong.unirest.CompoundInterceptor.lambda$onFail$2(CompoundInterceptor.java:54)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.Collections$2.tryAdvance(Unknown Source). When

**Comment by melba-lopez** [comment]
Hi @nscuro  :) Long time no see!!  

We've been getting this issue recently due to us intentionally denying all inbound/outbound traffic unless we explicitly define it.  We will be fixing it by adding rules for the majority of the 19ish endpoints that are defined for DT.  Howevever, when we don't want to use an endpoint (for whatever reason) ... then this becomes problematic and makes DT unstable.

**Example**:  After a fresh reboot, everything is looking good from a log perspective.  You upload a few SBOMs and you start to see these errors for the endpoints that aren't reachable.  After a few hours, DT will stop processing BOMs.  It will take in the BOM, but the API server never actually gets the request because it appears to be bogged down by constant error messages.  The only 2 solutions is to add the endpoint OR reboot every few hours.  

Obviously we plan on adding the maven endpoint, but we won't be adding ALL the endpionts.  My concern is this problem will still arise from the other endpoints not being allowed.  

Has this or will this be addressed in newer versions of DT?  Any thoughts to explicitly allowing a setting to turn off/on the connections in DT so that it knows if the user wants to disable them?

**Comment by nscuro** [comment]
@melba-lopez You can disable all default repositories in the settings in case you don't need them, or don't want to allow them being requested: https://docs.dependencytrack.org/datasources/repositories/

Are there other endpoints besides those for repositories that appear problematic in your case?
