### ISSUE TITLE
MSSQL Deadlock

### ISSUE THREAD

**Issue by BlythMeister** [DependencyTrack/dependency-track#1989]
### Current Behavior:

When pushing a lot of SBOM files at the same time for different projects we see SQL deadlocks

### Steps to Reproduce:

Push 20 SBOM files one after each other and observe logs

### Expected Behavior:

No deadlocks

### Environment:
  
  - Dependency-Track Version: 4.5.0
  - Distribution: Docker
  - BOM Format & Version: CycloneDX 1.3
  - Database Server: MSSQL
  - Browser: N/A

### Additional Details:

```
2022-09-30 13:42:52,275 ERROR [MetricsUpdateTask] An unexpected error occurred while updating project metrics and iterating through components. The error occurred while updating metrics for project: 2448cf4c-2af3-462a-b503-d2b236d1a7ab and component: dea83006-0c7e-436f-9a1e-a6280fc447d4
javax.jdo.JDOException: Exception thrown when executing query : SELECT 'org.dependencytrack.model.DependencyMetrics' AS DN_TYPE,A0.CRITICAL,A0.FINDINGS_AUDITED,A0.FINDINGS_TOTAL,A0.FINDINGS_UNAUDITED,A0.FIRST_OCCURRENCE,A0.HIGH,A0.ID,A0.RISKSCORE,A0.LAST_OCCURRENCE AS NUCORDER0,A0.LOW,A0.MEDIUM,A0.POLICYVIOLATIONS_AUDITED,A0.POLICYVIOLATIONS_FAIL,A0.POLICYVIOLATIONS_INFO,A0.POLICYVIOLATIONS_LICENSE_AUDITED,A0.POLICYVIOLATIONS_LICENSE_TOTAL,A0.POLICYVIOLATIONS_LICENSE_UNAUDITED,A0.POLICYVIOLATIONS_OPERATIONAL_AUDITED,A0.POLICYVIOLATIONS_OPERATIONAL_TOTAL,A0.POLICYVIOLATIONS_OPERATIONAL_UNAUDITED,A0.POLICYVIOLATIONS_SECURITY_AUDITED,A0.POLICYVIOLATIONS_SECURITY_TOTAL,A0.POLICYVIOLATIONS_SECURITY_UNAUDITED,A0.POLICYVIOLATIONS_TOTAL,A0.POLICYVIOLATIONS_UNAUDITED,A0.POLICYVIOLATIONS_WARN,A0.SUPPRESSED,A0.UNASSIGNED_SEVERITY,A0.VULNERABILITIES FROM DEPENDENCYMETRICS A0 WHERE A0.COMPONENT_ID = ? ORDER BY NUCORDER0 DESC
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:676)
	at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:456)
	at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:276)
	at org.dependencytrack.persistence.MetricsQueryManager.getMostRecentDependencyMetrics(MetricsQueryManager.java:137)
	at org.dependencytrack.persistence.QueryManager.getMostRecentDependencyMetrics(QueryManager.java:937)
at org.dependencytrack.tasks.MetricsUpdateTask.updateComponentMetrics(MetricsUpdateTask.java:492)
	at org.dependencytrack.tasks.MetricsUpdateTask.updateProjectMetrics(MetricsUpdateTask.java:278)
	at org.dependencytrack.tasks.MetricsUpdateTask.inform(MetricsUpdateTask.java:69)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Transaction (Process ID 463) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5479)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1798)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1056)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
	at org.datanucleus.store.rdbms.query.ForwardQueryResult.initialise(ForwardQueryResult.java:93)
	at org.datanucleus.store.rdbms.query.JDOQLQuery.performExecute(JDOQLQuery.java:714)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1975)
	at org.datanucleus.store.query.Query.executeWithArray(Query.java:1864)
	at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:433)
	... 10 common frames omitted
```

**Comment by BlythMeister** [comment]
This only seemed to happen for the first 24 or so hours.

Believe it to be due to incomplete SQL database statistics as new data added.

Don't think this is a real issue.
