### ISSUE TITLE
Uncaught internal server error java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by habakuk007** [DependencyTrack/dependency-track#2029]
### Current Behavior:

I get this error in the Docker Log Terminal:

    2022-10-11 10:34:46,950 ERROR [GlobalExceptionHandler] Uncaught internal server error
    java.lang.NumberFormatException: For input string: ""
           at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
           at java.base/java.lang.Integer.parseInt(Unknown Source)
           at java.base/java.lang.Integer.valueOf(Unknown Source)
           at org.dependencytrack.model.Finding.getCwes(Finding.java:169)
(see attachement for complete stack trace).

And now the vulnerabilities list of the test project I added is not shown any more (0 entries, before were about 40).

### Steps to Reproduce:

I changed some components, added internal vulnerabilities and added a CPE to the project...

### Expected Behavior:

Do not produce uncaught internal server errors

### Environment:
  
  - Dependency-Track Version: 4.5.0
  - Distribution: Docker
  - BOM Format & Version: CycloneDX 
  - Database Server: Docker
  - Browser: Firefox

[Stacktrace.txt](https://github.com/DependencyTrack/dependency-track/files/9754273/Stacktrace.txt)

**Comment by nscuro** [comment]
Thanks for reporting @habakuk007! This will be fixed in 4.6 which is scheduled for release for today.
