### ISSUE TITLE
NVD mirroring failing when dependency track syncing the data feeds.

### ISSUE THREAD

**Issue by Swapnil-CSI** [DependencyTrack/dependency-track#2063]
### Current Behavior:

Facing issue while using the dependency track nvd mirrors on dependency-check tool.  Sometime it shows below error whenever the dependency track tries to sync the NVD data with https://nvd.nist.gov/feeds

1. Dependency track log
```
2022-10-18 14:05:01,333 INFO [NistMirrorTask] Retrieval of nvdcve-1.1-2022.json.gz not necessary. Will use modified feed for updates.
2022-10-18 14:05:01,333 INFO [NistMirrorTask] Retrieval of nvdcve-1.1-2021.json.gz not necessary. Will use modified feed for updates.
2022-10-18 14:05:01,333 INFO [NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
2022-10-18 14:05:01,572 INFO [NistMirrorTask] Downloading...
2022-10-18 14:05:01,863 INFO [NistMirrorTask] Uncompressing nvdcve-1.1-2020.json.gz
2022-10-18 14:05:02,888 INFO [NvdParser] Parsing nvdcve-1.1-2020.json
2022-10-18 14:08:35,402 INFO [MetricsUpdateTask] Completed metrics update on vulnerability database
```

3. Dependency check log ( using dependency track nvd mirroring )
```
[INFO] Download Started for NVD CVE - 2020
[ERROR] Error retrieving https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz; received response code 304; Not Modified
[INFO] Download Attempt 2 for NVD CVE - 2020
[INFO] Processing Complete for NVD CVE - 2012  (27159 ms)
[INFO] Processing Started for NVD CVE - 2015
[ERROR] Error retrieving https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz; received response code 304; Not Modified
[INFO] Download Attempt 3 for NVD CVE - 2020
[INFO] Processing Complete for NVD CVE - 2013  (27253 ms)
[INFO] Processing Started for NVD CVE - 2016
[ERROR] Error retrieving https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz; received response code 304; Not Modified
[INFO] Download Attempt 4 for NVD CVE - 2020
[INFO] Processing Complete for NVD CVE - 2014  (19073 ms)
[INFO] Processing Started for NVD CVE - 2017
[ERROR] Error retrieving https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz; received response code 304; Not Modified
[ERROR] Download Failed for NVD CVE - 2020
Some CVEs may not be reported. Reason: Download failed, unable to copy 'https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz' to '/tmp/dctemp9b817a9a-796f-4d2b-9910-a1afbd649626/cve2020_13916503771010561981.json.gz'; Error downloading file https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz; unable to connect.
[ERROR] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] Download Attempt 5 for NVD CVE - 2020
[INFO] Processing Complete for NVD CVE - 2015  (15610 ms)
[INFO] Processing Started for NVD CVE - 2018
[ERROR] Error downloading NVD CVE - 2020 Reason: Unable to download NVD CVE 2020
[INFO] Processing Complete for NVD CVE - 2016  (17548 ms)
[INFO] Processing Started for NVD CVE - 2019
[INFO] Download Started for NVD CVE - 2021
[INFO] Download Complete for NVD CVE - 2021  (196 ms)
[INFO] Processing Complete for NVD CVE - 2017  (19967 ms)
[INFO] Processing Started for NVD CVE - 2021
[INFO] Download Started for NVD CVE - 2022
[INFO] Download Complete for NVD CVE - 2022  (216 ms)
[ERROR] The execution of the download was interrupted
org.owasp.dependencycheck.data.update.exception.UpdateException: The execution of the download was interrupted
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:293)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.update(NvdCveUpdater.java:136)
	at org.owasp.dependencycheck.Engine.doUpdates(Engine.java:878)
	at org.owasp.dependencycheck.Engine.initializeAndUpdateDatabase(Engine.java:683)
	at org.owasp.dependencycheck.Engine.analyzeDependencies(Engine.java:609)
	at org.owasp.dependencycheck.App.runScan(App.java:256)
	at org.owasp.dependencycheck.App.run(App.java:188)
	at org.owasp.dependencycheck.App.main(App.java:83)
Caused by: java.util.concurrent.ExecutionException: org.owasp.dependencycheck.utils.DownloadFailedException: Unable to download NVD CVE 2020
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.owasp.dependencycheck.data.update.NvdCveUpdater.performUpdate(NvdCveUpdater.java:283)
	... 7 common frames omitted
Caused by: org.owasp.dependencycheck.utils.DownloadFailedException: Unable to download NVD CVE 2020
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:143)
	at org.owasp.dependencycheck.data.update.nvd.DownloadTask.call(DownloadTask.java:43)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[WARN] Unable to update 1 or more Cached Web DataSource, using local data instead. Results may not include recent vulnerabilities.
[ERROR] Unable to continue dependency-check analysis.
[ERROR] One or more fatal errors occurred
[ERROR] The execution of the download was interrupted
[ERROR] No documents exist
```

### Environment:
  
  - Dependency-Track Version: 4.6.1/4.5.0
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]
  - BOM Format & Version:
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
  - Browser: 

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by nscuro** [comment]
Ah, yeah, it says right there in the log output you posted that it's Dependency-Check having issues.

So Dependency-Check apparently can't deal with 304 responses from Dependency-Track's NVD mirror. I think you may want to raise this in the Dependency-Check repository instead? Looking at the code, returning a 304 is intended behavior from the DT side.

**Comment by Swapnil-CSI** [comment]
No, Actually, At the time of issue, When I tried to curl the url it was showing timeout
```
curl -OL   https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz
```
It was started working after I manually fetched the 2020 feeds on /data/nist dir on dependency track pod.
```
wget --no-check-certificate https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
gunzip nvdcve-1.1-2020.json.gz
wget --no-check-certificate https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
wget --no-check-certificate https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta
```
( Before downloading the feeds, I seen that the .gz file timestamp was showing year 1970 )

**Comment by Swapnil-CSI** [comment]
I faced similar issue today. Here are the logs.

```
[swapnil@bharshankar tmp]$ wget https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz
--2022-11-03 16:53:11--  https://example.com/mirror/nvd/nvdcve-1.1-2020.json.gz
Resolving example.com (example.com)... 10.0.1.18
Connecting to example.com (example.com)|10.0.1.18|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
2022-11-03 16:53:13 ERROR 304: Not Modified.

[swapnil@bharshankar tmp]$
```

dependency-track-apiserver server logs

```
2022-11-03 09:26:21,325 INFO [NistMirrorTask] Retrieval of nvdcve-1.1-2022.json.gz not necessary. Will use modified feed for updates.
2022-11-03 09:26:21,325 INFO [NistMirrorTask] Retrieval of nvdcve-1.1-2021.json.gz not necessary. Will use modified feed for updates.
2022-11-03 09:26:21,325 INFO [NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
2022-11-03 09:26:21,504 INFO [NistMirrorTask] Downloading...
2022-11-03 09:26:21,754 INFO [NistMirrorTask] Uncompressing nvdcve-1.1-2020.json.gz
2022-11-03 09:26:22,584 INFO [NvdParser] Parsing nvdcve-1.1-2020.json
2022-11-03 09:41:04,452 INFO [InternalComponentIdentificationTask] Starting internal component identification
```

Manually downloaded the 2020 NVD files.
```
dtrack@dependency-track-apiserver-94846747b-npsvc:/data/nist$ ls -lrth | grep -i 2020
-rw-r--r-- 1 dtrack dtrack 5.4M Jan  1  1970 nvdcve-1.1-2020.json.gz
-rw-r--r-- 1 dtrack dtrack  166 Nov  2 11:43 nvdcve-1.1-2020.meta
-rw-rw-r-- 1 dtrack dtrack 109M Nov  3 09:26 nvdcve-1.1-2020.json
dtrack@dependency-track-apiserver-94846747b-npsvc:/data/nist$

dtrack@dependency-track-apiserver-94846747b-npsvc:/data/nist$ rm -rf nvdcve-1.1-2020.*
dtrack@dependency-track-apiserver-94846747b-npsvc:/data/nist$ wget --no-check-certificate https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
--2022-11-03 11:29:52--  https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
Resolving nvd.nist.gov (nvd.nist.gov)... 18.235.227.114, 2600:1f18:268d:1ddd:fd96:dcaa:cf17:f2b2
Connecting to nvd.nist.gov (nvd.nist.gov)|18.235.227.114|:443... connected.
WARNING: The certificate of ‘nvd.nist.gov’ is not trusted.
WARNING: The certificate of ‘nvd.nist.gov’ doesn't have a known issuer.
HTTP request sent, awaiting response... 200 OK
Length: 5634946 (5.4M) [application/x-gzip]
Saving to: ‘nvdcve-1.1-2020.json.gz’

nvdcve-1.1-2020.json.gz    100%[========================================>]   5.37M  24.7MB/s    in 0.2s

2022-11-03 11:29:53 (24.7 MB/s) - ‘nvdcve-1.1-2020.json.gz’ saved [5634946/5634946]

dtrack@dependency-track-apiserver-94846747b-npsvc:/data/nist$ gunzip nvdcve-1.1-2020.json.gz
dtrack@dependency-track-apiserver-94846747b-npsvc:/data/nist$ wget --no-check-certificate https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
--2022-11-03 11:30:11--  https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.json.gz
Resolving nvd.nist.gov (nvd.nist.gov)... 18.235.227.114, 2600:1f18:268d:1ddd:fd96:dcaa:cf17:f2b2
Connecting to nvd.nist.gov (nvd.nist.gov)|18.235.227.114|:443... connected.
WARNING: The certificate of ‘nvd.nist.gov’ is not trusted.
WARNING: The certificate of ‘nvd.nist.gov’ doesn't have a known issuer.
HTTP request sent, awaiting response... 200 OK
Length: 5634946 (5.4M) [application/x-gzip]
Saving to: ‘nvdcve-1.1-2020.json.gz’

nvdcve-1.1-2020.json.gz    100%[========================================>]   5.37M  23.7MB/s    in 0.2s

2022-11-03 11:30:11 (23.7 MB/s) - ‘nvdcve-1.1-2020.json.gz’ saved [5634946/5634946]

dtrack@dependency-track-apiserver-94846747b-npsvc:/data/nist$ wget --no-check-certificate https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta
--2022-11-03 11:30:22--  https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2020.meta
Resolving nvd.nist.gov (nvd.nist.gov)... 18.235.227.114, 2600:1f18:268d:1ddd:fd96:dcaa:cf17:f2b2
Connecting to nvd.nist.gov (nvd.nist.gov)|18.235.227.114|:443... connected.
WARNING: The certificate of ‘nvd.nist.gov’ is not trusted.
WARNING: The certificate of ‘nvd.nist.gov’ doesn't have a known issuer.
HTTP request sent, awaiting response... 200 OK
Length: 166 [text/plain]
Saving to: ‘nvdcve-1.1-2020.meta’

nvdcve-1.1-2020.meta       100%[========================================>]     166  --.-KB/s    in 0s

2022-11-03 11:30:22 (126 MB/s) - ‘nvdcve-1.1-2020.meta’ saved [166/166]

dtrack@dependency-track-apiserver-94846747b-npsvc:/data/nist$
exit
[swapnil@bharshankar tmp]$ wget https://example.com/mirror/nvd/nvdcve-1.1-2021.json.gz
--2022-11-03 17:00:40--  https://example.com/mirror/nvd/nvdcve-1.1-2021.json.gz
Resolving example.com (example.com)... 10.0.1.18
Connecting to example.com (example.com)|10.0.1.18|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6083028 (5.8M) [application/gzip]
Saving to: ‘nvdcve-1.1-2021.json.gz.1’

nvdcve-1.1-2021.json.gz.1   25%[=========>                               ]   1.45M   380KB/s    eta 14s    ^C
[swapnil@bharshankar tmp]$
```

**Comment by stevespringett** [comment]
If there's a defect, it likely will not be fixed because the NVD has deprecated the feeds and will be removing support for them. Dependency-Track will as well. See #1861

**Comment by syalioune** [comment]
From what I can gather, I believe there are different issues at play here :

1. DT NvdMirrorServlet returning 304 not modified

Neither Dependency Track nor Dependency Check can handle status 304 upon NVD feed download. Only status 200 is expected by DT https://github.com/DependencyTrack/dependency-track/blob/2f6a7e504d60ef17a7bb621d0d77a942563a75c8/src/main/java/org/dependencytrack/tasks/NistMirrorTask.java#L215-L253 and [DC](https://github.com/jeremylong/DependencyCheck/blob/2495c996fc5c642513b82c2f71ca496b0e14e7bc/utils/src/main/java/org/owasp/dependencycheck/utils/HttpResourceConnection.java#L211-L250)

Based on the provided logs, the issue is highly circumstancial and happens when the mirror servlet is called while DT is uncompressing and parsing a year's JSON feed. During that specific interval, the file last modified attribute is set back to epoch https://github.com/DependencyTrack/dependency-track/blob/2f6a7e504d60ef17a7bb621d0d77a942563a75c8/src/main/java/org/dependencytrack/tasks/NistMirrorTask.java#L222-L225 causing the NvdMirrorServlet to return the 304 not modified status.

Coincidentally, the recent fix to #2048 merged to master should fix it as the last modified date is now handled using an external file without modifying the feed file https://github.com/DependencyTrack/dependency-track/blob/45868a937f9e5902bee630a2a8c627e459b773d1/src/main/java/org/dependencytrack/tasks/NistMirrorTask.java#L233-L237

3. NVD feed parsing by DT

This is maybe a timezone configuration issue but I'm puzzled by the fact that parsing of 2020 file seems to stop midway through.
It started at `09:26:22,584` and was not finished at `11:29:52` on november 03rd. Can't reliably tell if it is 3 minutes or 2H later...
@Swapnil-CSI Can you pls shed some light on the timeline ? Do you have any other errors in the logs ?

**Comment by Swapnil-CSI** [comment]
@syalioune I do not see other errors on pod. 
I seen the error when I tried to use the NVD mirrors at 11:29:52
```
dtrack@dependency-track-apiserver-94846747b-npsvc:/opt/owasp/dependency-track$ date
Fri Nov  4 08:14:47 UTC 2022
dtrack@dependency-track-apiserver-94846747b-npsvc:/opt/owasp/dependency-track$

```

**Comment by Swapnil-CSI** [comment]
Seen similar issue again. Tried to use NVD mirrors in pipeline but revived error.

```
[INFO] Download Started for NVD CVE - 2015
[INFO] Download Complete for NVD CVE - 2015  (306 ms)
[INFO] Download Started for NVD CVE - 2017
[INFO] Download Complete for NVD CVE - 2017  (478 ms)
[INFO] Download Started for NVD CVE - 2018
[ERROR] Error retrieving https://example.com/mirror/nvd/nvdcve-1.1-2018.json.gz; received response code 304; Not Modified
[INFO] Download Attempt 2 for NVD CVE - 2018
[ERROR] Error retrieving https://example.com/mirror/nvd/nvdcve-1.1-2018.json.gz; received response code 304; Not Modified
[INFO] Download Attempt 3 for NVD CVE - 2018
[INFO] Processing Complete for NVD CVE - 2009  (27277 ms)
[INFO] Processing Started for NVD CVE - 2015
[ERROR] Error retrieving https://example.com/mirror/nvd/nvdcve-1.1-2018.json.gz; received response code 304; Not Modified
[INFO] Download Attempt 4 for NVD CVE - 2018
[INFO] Processing Complete for NVD CVE - 2014  (28349 ms)
[INFO] Processing Started for NVD CVE - 2017
[ERROR] Error retrieving https://example.com/mirror/nvd/nvdcve-1.1-2018.json.gz; received response code 304; Not Modified
[ERROR] Download Failed for NVD CVE - 2018
Some CVEs may not be reported. Reason: Download failed, unable to copy 'https://example.com/mirror/nvd/nvdcve-1.1-2018.json.gz' to '/tmp/dctemp6f1e334b-7bb8-4b94-8576-137c68ecfd11/cve2018_14364400717628467266.json.gz'; Error downloading file https://example.com/mirror/nvd/nvdcve-1.1-2018.json.gz; unable to connect.
[ERROR] If you are behind a proxy you may need to configure dependency-check to use the proxy.
[INFO] Download Attempt 5 for NVD CVE - 2018
[INFO] Processing Complete for NVD CVE - 2013  (35417 ms)

```

pod log
```
2022-12-13 09:52:26,473 INFO [PortfolioMetricsUpdateTask] Completed portfolio metrics update in 08:43:304
2022-12-13 10:27:19,564 INFO [NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2019.meta
2022-12-13 10:27:19,769 INFO [NistMirrorTask] Downloading...
2022-12-13 10:27:19,771 INFO [NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2018.json.gz
2022-12-13 10:27:19,832 INFO [NistMirrorTask] Downloading...
2022-12-13 10:27:20,069 INFO [NistMirrorTask] Uncompressing nvdcve-1.1-2018.json.gz
2022-12-13 10:27:20,507 INFO [NvdParser] Parsing nvdcve-1.1-2018.json
2022-12-13 10:43:43,169 INFO [PortfolioMetricsUpdateTask] Executing portfolio metrics update
2022-12-13 10:43:43,172 INFO [VulnerabilityMetricsUpdateTask] Executing metrics update on vulnerability database
2022-12-13 10:43:43,176 INFO [ProjectMetricsUpdateTask] Executing metrics update for project
```

After sometime when i run pipeline again. NVD mirrors are started working again.

**Comment by Swapnil-CSI** [comment]
Not facing this issue after upgrading the DT to latest version.
