### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by jskovjyskebankdk** [DependencyTrack/dependency-track#212]
### Issue Type:
  - [x] defect report
  - [ ] enhancement request

### Current Behavior:
The dependency track application crashes fairly frequently. In a matter of hours, is what I am observing.

I have attached log output at the end from when the crashing starts. The exception repeats every second until I kill it.

It is not very clear from the log (to me) what the origin of the problem might be.

### Steps to Reproduce (if defect):
Let DT run, pushing data to it from Jenkins.

### Expected Behavior:
It should keep running :)

### Environment:
  
  - Dependency-Track Version: 3.2.1
  - Distribution: Embedded WAR
  - BoM Format & Version:
  - Database Server: H2
  - Browser: 

I run it in a Docker container with 4GB RAM using Oracle 8_181.

I use H2 trying to see it working before I set up a proper DB.
There does not appear to be problems with memory or CPU load.

It is not clear to me (from the stack trace) that using H2 should be the root of the problem?!

I guess I will try to set up an external DB to see if it changes anything.

### Other Details:
```
2018-10-11 11:24:37,011 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: 737124f6-8660-469c-988f-f9dcb6ffe88b
2018-10-11 11:24:37,059 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: 7919dc7e-67ac-480e-a647-6aba4700ebb1
2018-10-11 11:49:59,297 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:720)
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:734)
        at org.apache.lucene.index.IndexWriter.deleteDocuments(IndexWriter.java:1420)
        at org.dependencytrack.search.ComponentIndexer.remove(ComponentIndexer.java:95)
        at org.dependencytrack.search.ComponentIndexer.remove(ComponentIndexer.java:39)
        at org.dependencytrack.tasks.IndexTask.inform(IndexTask.java:50)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:90)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-10-11 11:49:59,297 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
org.apache.lucene.store.AlreadyClosedException: this IndexWriter is closed
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:720)
        at org.apache.lucene.index.IndexWriter.ensureOpen(IndexWriter.java:734)
        at org.apache.lucene.index.IndexWriter.deleteDocuments(IndexWriter.java:1420)
        at org.dependencytrack.search.ComponentIndexer.remove(ComponentIndexer.java:95)
        at org.dependencytrack.search.ComponentIndexer.remove(ComponentIndexer.java:39)
        at org.dependencytrack.tasks.IndexTask.inform(IndexTask.java:50)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:90)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by stevespringett** [comment]
This issue is benign and you can safely ignore it. If something is open and is later closed, it cannot be closed again, which is what this stack trace is telling me. There's likely a double close somewhere in the code but it should not affect anything.

**Comment by stevespringett** [comment]
I'm unable to reproduce this issue, but I've made a few minor tweaks that may help. I'm going to leave the ticket open for awhile. If you find that 3.3 fixes the issue, please close it. If it's still ongoing, please reply to the ticket and let me know.

**Comment by jskovjyskebankdk** [comment]
Yes, sorry about the silence (vacation, and then swamped with other stuff).

My plan is to try again with 3.3 and an external DB. Probably next week.

Cheers.

**Comment by jskovjyskebankdk** [comment]
I have run 3.3 with an external DB for a couple of days now.

No sign of the double-close, and the web application remains usable.

So it might have something in 3.2 or the H2 setup.

Thanks
