### ISSUE TITLE
NullPointerException during policy evaluation

### ISSUE THREAD

**Issue by valentijnscholten** [DependencyTrack/dependency-track#2135]
### Current Behavior:
```
2022-11-03 11:55:42,213 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
        at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
        at java.base/java.util.regex.Matcher.reset(Unknown Source)
        at java.base/java.util.regex.Matcher.<init>(Unknown Source)
        at java.base/java.util.regex.Pattern.matcher(Unknown Source)
        at org.dependencytrack.policy.CoordinatesPolicyEvaluator.versionMatches(CoordinatesPolicyEvaluator.java:99)
        at org.dependencytrack.policy.CoordinatesPolicyEvaluator.evaluate(CoordinatesPolicyEvaluator.java:65)
        at org.dependencytrack.policy.PolicyEngine.evaluate(PolicyEngine.java:85)
        at org.dependencytrack.policy.PolicyEngine.evaluate(PolicyEngine.java:69)
        at org.dependencytrack.tasks.VulnerabilityAnalysisTask.performPolicyEvaluation(VulnerabilityAnalysisTask.java:130)
        at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:76)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

https://github.com/DependencyTrack/dependency-track/blob/6c6ceadaaa86e1c1da7d8035eeaa1c950b0cb7b4/src/main/java/org/dependencytrack/policy/CoordinatesPolicyEvaluator.java#L98-L102

### Steps to Reproduce:
Might be this policy we have with no version in coordinates field:

![image](https://user-images.githubusercontent.com/4426050/200411091-e8493084-6fe3-4956-96d0-c0def1b4e1c3.png)

### Expected Behavior:
No errors.
Having a policy matching all versions should be possible, or proper validation should be done when creating/updating policies.

### Environment:
  
  - Dependency-Track Version: 4.6.1
  - Distribution: Docker
  - BOM Format & Version: n/a
  - Database Server: PostgreSQL
  - Browser: n/a

**Comment by valentijnscholten** [comment]
Diving further into the code it looks like a '*' might be valid way to match all versions. The tooltip is not very clear about this.

![image](https://user-images.githubusercontent.com/4426050/200412157-e33dd50e-4804-45c8-84f7-e4b334da8519.png)

Either way a empty value should not be accepted, or maybe it should be treated as '*' / default matching.

**Comment by msymons** [comment]
I saw a similar exception during policy evaluation:

```
2023-02-14 17:13:22,567 INFO [OssIndexAnalysisTask] Sonatype OSS Index analysis complete
2023-02-14 17:13:22,576 INFO [PolicyEngine] Evaluating 193 component(s) against applicable policies
2023-02-14 17:13:22,757 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: Cannot invoke "org.dependencytrack.model.LicenseGroup.getId()" because "lg" is null
	at org.dependencytrack.persistence.PolicyQueryManager.doesLicenseGroupContainLicense(PolicyQueryManager.java:469)
	at org.dependencytrack.persistence.QueryManager.doesLicenseGroupContainLicense(QueryManager.java:647)
	at org.dependencytrack.policy.LicenseGroupPolicyEvaluator.evaluate(LicenseGroupPolicyEvaluator.java:65)
	at org.dependencytrack.policy.PolicyEngine.evaluate(PolicyEngine.java:85)
	at org.dependencytrack.policy.PolicyEngine.evaluate(PolicyEngine.java:69)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.performPolicyEvaluation(VulnerabilityAnalysisTask.java:136)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:79)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

The cause was a License condition checking for License Group and the License Group was null.

The unfortunate consequence was that BOMs were uploaded by Jenkins Nightly Builds and the builds failed due to timeouts waiting for Analysis.

The problem for us started on 7th January and this was a week after the upgrade to v4.7.1  (so it was not the upgrade that caused the problem).  Deletion of the policy immedatly resulted in things coming right.

More importantly, I cannot seem to be able to deliberately create a License Group policy condition with blank group.  Neither can I edit an existing License Group Policy Condition to make it blank.  So I do not know how our problem policy got to have a null group.

(There is no usage of the API for this sort of thing).

**Comment by nscuro** [comment]
> @msymons More importantly, I cannot seem to be able to deliberately create a License Group policy condition with blank group. Neither can I edit an existing License Group Policy Condition to make it blank. So I do not know how our problem policy got to have a null group.

The error is caused when a policy refers to a license group that no longer exists. So most likely a custom license group was created, referred to in a policy condition, and then removed.
