### ISSUE TITLE
Can not create or delete project

### ISSUE THREAD

**Issue by gamma** [DependencyTrack/dependency-track#2165]
### Current Behavior

Creating or deleting a project results in errors and an NPE. The creation still works, but the deletion does not

```
dependdency-track-dtrack-apiserver-1  | 2022-11-18 09:59:21,493 ERROR [GlobalExceptionHandler] Uncaught internal server error
dependdency-track-dtrack-apiserver-1  | java.lang.NullPointerException: Cannot invoke "java.security.Principal.getName()" because the return value of "alpine.server.resources.AlpineResource.getPrincipal()" is null
dependdency-track-dtrack-apiserver-1  | 	at org.dependencytrack.resources.v1.ProjectResource.deleteProject(ProjectResource.java:425)
dependdency-track-dtrack-apiserver-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
dependdency-track-dtrack-apiserver-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
dependdency-track-dtrack-apiserver-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
dependdency-track-dtrack-apiserver-1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:134)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:177)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:81)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
dependdency-track-dtrack-apiserver-1  | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
dependdency-track-dtrack-apiserver-1  | 	at alpine.server.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:225)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
dependdency-track-dtrack-apiserver-1  | 	at alpine.server.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:93)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
dependdency-track-dtrack-apiserver-1  | 	at alpine.server.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:166)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1383)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1305)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.Server.handle(Server.java:563)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:139)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:933)
dependdency-track-dtrack-apiserver-1  | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1077)
dependdency-track-dtrack-apiserver-1  | 	at java.base/java.lang.Thread.run(Unknown Source)

```

### Steps to Reproduce

1. Set up fresh docker instance with minimal settings
2. Create or delete a project in the UI
3. NPE as stated above

### Expected Behavior

Project is created or deleted

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Container Image

### Database Server

N/A

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by gamma** [comment]
Possible issue in docker compose file (modified)

```
    - ALPINE_ENFORCE_AUTHENTICATION=false
    - ALPINE_ENFORCE_AUTHORIZATION=false
```
