### ISSUE TITLE
Unable to send MS Teams notification: Value in JsonObjects name/value pair cannot be null

### ISSUE THREAD

**Issue by codenox-vs** [DependencyTrack/dependency-track#2217]
### Current Behavior

Any action which should send a teams notification results in following exception.
The default template "Microsoft Teams" is used.
We have this notification for a long time, so this came with a surprise  after we did not receive any news for some time from our dependency track installation.

2022-11-30 15:37:37,796 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
	at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:222)
	at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:90)
	at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:75)
	at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:110)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

1. Have a teams notification setup
2. Try to change a  Audit Vulnerabilities  -> Analysis ->  any value
3. this does no longer trigger a teams notification

### Expected Behavior

a teams notification :)

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

14.1

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by codenox-vs** [comment]
I have no idea why, but it works now again. Same projects, same software version, same bom.xml ...  nothing changed but a new day :) ... "good" I guess, so I close it for now, since I would not be able to reproduce it now anyway ,,,
