### ISSUE TITLE
"Unsupported database file version or invalid file header in file" after update from v4.5 to v4.6 in docker

### ISSUE THREAD

**Issue by gwi42** [DependencyTrack/dependency-track#2249]
### Current Behavior

After updating from a working installation running version 4.5 to the current version 4.6.3 the docker container cannot access the database anymore.

I could not find any specific update instructions in the current 4.6.3 documentation and thus only recreated the container with the latest image.
The logs show the following error:
```
2022-12-07 13:01:25,103 ERROR [UpgradeInitializer] An error occurred determining database schema version. Unable to continue.
alpine.server.upgrade.UpgradeException: An error occurred connecting to the database.
	at alpine.server.upgrade.UpgradeMetaProcessor.createConnection(UpgradeMetaProcessor.java:193)
	at alpine.server.upgrade.UpgradeMetaProcessor.<init>(UpgradeMetaProcessor.java:63)
	at org.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(UpgradeInitializer.java:54)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1048)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:983)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:740)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:900)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:470)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:415)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:100)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "/data/.dependency-track/db.mv.db" [90048-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:212)
	at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:161)
	at org.h2.mvstore.db.Store.<init>(Store.java:145)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
	at alpine.server.upgrade.UpgradeMetaProcessor.createConnection(UpgradeMetaProcessor.java:187)
	... 19 common frames omitted
Caused by: org.h2.mvstore.MVStoreException: The write format 1 is smaller than the supported format 2 [2.1.214/5]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.MVStore.getUnsupportedWriteFormatException(MVStore.java:1066)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:886)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:463)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082)
	at org.h2.mvstore.db.Store.<init>(Store.java:136)
	... 29 common frames omitted
```

### Steps to Reproduce

1. Installed version 4.5 with docker compose and configured a couple of components
2. Recreated containers after pulling the latestes images

### Expected Behavior

Database should be updated during start of the next/current version and be able to use the existing configuration after an update

### Dependency-Track Version

4.6.2

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Hi @gwi-isec7,

the upgrade notes for 4.6.0 (see https://docs.dependencytrack.org/changelog/) clearly state:

> * The embedded H2 database has been upgraded to major version 2
>   * Manual upgrade steps are required, refer to the [H2 v2 migration guide](https://docs.dependencytrack.org/getting-started/database-support/#migrating-to-h2-v2)
>    * **Without the manual migration, Dependency-Track 4.6 will not work with H2 databases created by earlier versions**
>    * **Reminder**: H2 is not, and never has been, supported for production usage

**Comment by gwi-isec7** [comment]
Hi @nscuro,
thanks a lot for pointing me in the right direction!
I defenitely need to pay more attention, it seems...
Sorry for the troubles...
