### ISSUE TITLE
Stack trace in DefectDojo interface: Cannot invoke "java.util.ArrayList.size()" because "dojoTests" is null

### ISSUE THREAD

**Issue by sleepy-manul** [DependencyTrack/dependency-track#2385]
### Current Behavior

I followed the instructions at https://docs.dependencytrack.org/integrations/defectdojo/ :

* Created a new product in DefectDojo
* Created a new engagement for that product
* Took note of the engagement ID in the URL (in my case: 7)
* Set the property [ Group: integrations, Name: defectdojo.engagementId, Type: STRING, Value: 7 ] in my project
* On the global level in dependency-track, set the configuration setting "Enable Reimport" to true
* On the global level in dependency-track, set the API key and URL for DefectDojo

However, on every sync interval, I always get the following stack trace in the dependency-track container logfile. No information seems to be synced with DefectDojo.

```
2023-01-16 12:37:15,916 WARN [DefectDojoClient] DefectDojo Client did not receive expected response while attempting to retrieve tests list 502 - null
2023-01-16 12:37:15,923 ERROR [DefectDojoUploader] An error occurred attempting to upload findings to DefectDojo
java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.size()" because "dojoTests" is null
at org.dependencytrack.integrations.defectdojo.DefectDojoClient.getDojoTestId(DefectDojoClient.java:119)
at org.dependencytrack.integrations.defectdojo.DefectDojoUploader.upload(DefectDojoUploader.java:90)
at org.dependencytrack.tasks.VulnerabilityManagementUploadTask.processProjectFindings(VulnerabilityManagementUploadTask.java:66)
at org.dependencytrack.tasks.VulnerabilityManagementUploadTask.inform(VulnerabilityManagementUploadTask.java:46)
at org.dependencytrack.tasks.DefectDojoUploadTask.inform(DefectDojoUploadTask.java:37)
at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source) 
```

However, looking at the Django logs (DefectDojo component), it appears that it is dependency-track who closes the connection:

```2023/01/16 12:52:14 [error] 11#11: *75345 upstream prematurely closed connection while reading response header from upstream, client: 172.16.155.124, server: , request: "GET /api/v2/tests/?limit=100&engagement=6 HTTP/1.1", upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock:", host: "defect-dojo-helmrelease-defectdojo-django.defect-dojo.svc.cluster.local"
172.16.155.124 - - [16/Jan/2023:12:52:14 +0000] "GET /api/v2/tests/?limit=100&engagement=6 HTTP/1.1" 502 497 "-" "unirest-java/3.1.00" "-"
2023/01/16 12:52:15 [error] 11#11: *75345 upstream prematurely closed connection while reading response header from upstream, client: 172.16.155.124, server: , request: "GET /api/v2/tests/?limit=100&engagement=7 HTTP/1.1", upstream: "uwsgi://unix:///run/defectdojo/uwsgi.sock:", host: "defect-dojo-helmrelease-defectdojo-django.defect-dojo.svc.cluster.local"
172.16.155.124 - - [16/Jan/2023:12:52:15 +0000] "GET /api/v2/tests/?limit=100&engagement=7 HTTP/1.1" 502 497 "-" "unirest-java/3.1.00" "-" 
```

I have tried entering one of those URLs directly in my web browser, e.g. https://(my Defect Dojo instance DNS name)/api/v2/tests/?limit=100&engagement=7 , and it worked without problems; I received a JSON response. (REST API seems to work)

### Steps to Reproduce

1. See above

### Expected Behavior

After following the instructions at https://docs.dependencytrack.org/integrations/defectdojo/ , the data from dependency-track should be synced to DefectDojo.

### Dependency-Track Version

4.7.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

14.5

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by sleepy-manul** [comment]
I am dumb. The uswgi log of DefectDojo revealed:

```django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'defect-dojo-helmrelease-defectdojo-django.defect-dojo.svc.cluster.local'. You may need to add 'defect-dojo-helmrelease-defectdojo-django.defect-dojo.svc.cluster.local' to ALLOWED_HOSTS. ```

The problem came because, within the Kubernetes cluster, we used the service hostname. This is why it worked from my web browser (which uses the external load balancer's DNS name), but not from within the cluster.

I extended my Helm values.yaml like this:
```
spec:
  values:
    alternativeHosts:
      - defect-dojo-helmrelease-defectdojo-django.defect-dojo.svc.cluster.local
```

Maybe this is helpful if someone else has the same problem.
