### ISSUE TITLE
An unknown error occurred in an asynchronous event or notification thread

### ISSUE THREAD

**Issue by olafz** [DependencyTrack/dependency-track#2437]
### Current Behavior

In the logging, I occasionally see this stacktrace:

```
2023-02-01 19:11:16,135 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
javax.jdo.JDODataStoreException: Iteration request failed : SELECT 'alpine.model.Team''alpine.model.Team' AS "DN_TYPE","A1"."ID", AS "DN_TYPE","A1"."ID" AS "NUCORDER0","A1"."UUID",,"A0"."NOTIFICATIONRULE_ID" FROM "NOTIFICATIONRULE_TEAMS" "A0""NOTIFICATIONRULE_TEAMS" "A0" INNER JOIN "TEAM" "A1" ON "A0"."TEAM_ID" = "A1"."ID" INNER JOIN "TEAM" "A1" ON "A0"."TEAM_ID" = "A1"."ID" WHERE EXISTS (SELECT 'org.dependencytrack.model.NotificationRule''org.dependencytrack.model.NotificationRule' AS "DN_TYPE","A0_SUB"."ID" AS "DN_APPID" FROM  FROM "NOTIFICATIONRULE" "A0_SUB""NOTIFICATIONRULE" "A0_SUB" WHERE "A0_SUB"."NOTIFICATION_LEVEL" = 'INFORMATIONAL' AND "A0_SUB"."ENABLED" = 1 AND "A0_SUB"."SCOPE" = ? AND "A0"."NOTIFICATIONRULE_ID" = "A0_SUB"."ID") ORDER BY "NUCORDER0"EXISTS (SELECT 'org.dependencytrack.model.NotificationRule''org.dependencytrack.model.NotificationRule' AS "DN_TYPE","A0_SUB"."ID" AS "DN_APPID" FROM  FROM "NOTIFICATIONRULE" "A0_SUB""NOTIFICATIONRULE" "A0_SUB" WHERE "A0_SUB"."NOTIFICATION_LEVEL" = 'INFORMATIONAL' AND "A0_SUB"."ENABLED" = 1 AND "A0_SUB"."SCOPE" = ? AND "A0"."NOTIFICATIONRULE_ID" = "A0_SUB"."ID") ORDER BY "NUCORDER0"
	at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:605)
	at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:456)
	at org.datanucleus.api.jdo.JDOQuery.executeList(JDOQuery.java:345)
	at org.dependencytrack.notification.NotificationRouter.resolveRules(NotificationRouter.java:149)
	at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:58)
	at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:110)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: No value specified for parameter 2

(...)

2023-02-01 19:11:16,136 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
javax.jdo.JDODataStoreException: Iteration request failed : SELECT 'alpine.model.Team''alpine.model.Team' AS "DN_TYPE","A1"."ID", AS "DN_TYPE","A1"."ID" AS "NUCORDER0","A1"."UUID",,"A0"."NOTIFICATIONRULE_ID" FROM "NOTIFICATIONRULE_TEAMS" "A0""NOTIFICATIONRULE_TEAMS" "A0" INNER JOIN "TEAM" "A1" ON "A0"."TEAM_ID" = "A1"."ID" INNER JOIN "TEAM" "A1" ON "A0"."TEAM_ID" = "A1"."ID" WHERE EXISTS (SELECT 'org.dependencytrack.model.NotificationRule''org.dependencytrack.model.NotificationRule' AS "DN_TYPE","A0_SUB"."ID" AS "DN_APPID" FROM  FROM "NOTIFICATIONRULE" "A0_SUB""NOTIFICATIONRULE" "A0_SUB" WHERE "A0_SUB"."NOTIFICATION_LEVEL" = 'INFORMATIONAL' AND "A0_SUB"."ENABLED" = 1 AND "A0_SUB"."SCOPE" = ? AND "A0"."NOTIFICATIONRULE_ID" = "A0_SUB"."ID") ORDER BY "NUCORDER0"
	at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:605)
	at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:456)
	at org.datanucleus.api.jdo.JDOQuery.executeList(JDOQuery.java:345)
	at org.dependencytrack.notification.NotificationRouter.resolveRules(NotificationRouter.java:149)
	at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:58)
	at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:110)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS "DN_TYPE","A1"."ID" AS "NUCORDER0","A1"."UUID",,"A0"."NOTIFICATIONRULE_ID" FR' at line 1
```

I think the first error (`No value specified for parameter 2`) is misleading, since also in that SQL query you see an error around `AS "NUCORDER0","A1"."UUID",,"A0"."NOTIFICATIONRULE_ID" FROM` (note the double comma).

### Steps to Reproduce

This is a fresh install, without anything configured in the area of notifications, and after uploading a SBOM with vulnerabilities.

### Expected Behavior

I expect the error to be not there :)

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

MySQL

### Database Server Version

8.0

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Duplicate of #2061 (same root cause). This is fixed in v4.12.
