### ISSUE TITLE
Handling DB connection reset

### ISSUE THREAD

**Issue by mulder999** [DependencyTrack/dependency-track#2442]
### Current Behavior

With connection pool disable:

- Several connections are kept opened in idle
- No keep alive is performed, nor configurable in alpine
- Connection reset is not detected before application tries to access it
- Application raises an exception when the condition occurs
- User is force to retry until eventually all IDLE connections have been tried an new one have spawn

REM:
- Turning connection pool on is just making the problem worse and more difficult to understand. Depending on the configuration, I get either: a) massive connection leakage or b) Hikari refusing to create new connections. I have not found a way to avoid periodic backend restart.
- After some hesitation, I report as an improvement because dependency track clearly lack proper options at this stage to deal with DB connection reset. However any user facing the issue will see it as a bug.

### Proposed Behavior

I expect either:

A. Add optional keep alive, obviously discarding connection in case of issue/reset
B. Implement reconnect and retry in case `java.net.SocketException: Connection reset` is detected during a JDO call
C. Close connection after some configurable time in IDLE, that is no connection remains in IDLE forever (which does not work even in pool mode)
D. (Least resort) Close connection immediately after usage / Get always a fresh new connection

REM:
- DataNucleus seems to offer options for A and C but Alpine framework do not expose them.
- Connection pool through HikariCP seems to leverage some of those options but I cannot make them work properly either. See remarks in current behavior.

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this enhancement was already requested

**Comment by nscuro** [comment]
Can you provide more details on what configurations you tried and what behavior you've seen as a consequence? Are you monitoring your connection pools? https://docs.dependencytrack.org/getting-started/database-support/#connection-pooling

We made some improvements to how the connection pool(s) are being created in Alpine 2.2.0 / DT 4.7.0. I posted some details in https://github.com/DependencyTrack/dependency-track/issues/1935.

We now have more flexibility in how HikariCP is configured, as we do that ourselves now instead of delegating it to DataNucleus. What kind of configuration do you have in mind on the HikariCP side to address your concerns?

I don't think dead connections are something that should be handled manually by us, I'd expect the connection pool to take care of that. What's more, I don't believe DN would allow us to do it, it's just way too high of an abstraction. It has [its own connection management](https://github.com/datanucleus/datanucleus-core/blob/datanucleus-core-6.0.3/src/main/java/org/datanucleus/store/connection/ConnectionManagerImpl.java) on top of the actual connection pool implementation, it's pretty wild.

**Comment by mulder999** [comment]
@nscuro 

> Can you provide more details on what configurations you tried and what behavior you've seen as a consequence?

As I mentionned, I have been trying to mitigate the issue and attempted pretty much every possible configuration. Let's just focus on basics first. I have 2 systems in tests. Both connect to same postgres DB instance but different schema. Config is:

```(yaml)
      - ALPINE_DATABASE_MODE=external
      - ALPINE_DATABASE_URL=jdbc:postgresql://...
      - ALPINE_DATABASE_DRIVER=org.postgresql.Driver
      - ALPINE_DATABASE_USERNAME=xxxxx
      - ALPINE_DATABASE_PASSWORD_FILE=/run/secrets/db_secret
      - ALPINE_DATABASE_POOL_ENABLED=false
```

I observe 2 different patterns:
A) After some minutes/hours with system idle (9 connexions IDLE / 1 active), when attempting to call for eg `/api/v1/project` (list of projects, this is what the UI calls to display/refresh the projects screen") I receive back 500 errors. It requires up to 5 failures to return to a fully working connections sets. Exception in logs is `Caused by: java.net.SocketException: Connection reset at java.base/sun.nio.ch.NioSocketImpl.implRead(Unknown Source) at java.base/sun.nio.ch.NioSocketImpl.read(Unknown Source)`.

Explanation: the connection sitting in IDLE are in a dead state and the condition is detected only when DN attempt to use them

B) After some hours with system in IDLE, number of connections drops to 1 active / 1 IDLE. Calling `/api/v1/project` never returns. It seems impossible to exit this condition without backend restart. Reset exception is also visible in logs but not the time of the API call but when doing ` ERROR [Persist] Update of object with id "org.dependencytrack.model.DependencyMetrics:35155" using statement "UPDATE "DEPENDENCYMETRICS" SET "LAST_OCCURRENCE"=? WHERE "ID"=?" failed : org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend. `

Possible/partial explanation (just plain guesses at this stage): Transactional connections suffer the same issue as non transactional connections but for some reasons are not reopened (perhaps some business logic not managed transactionnally in DB to ensure unique execution)

> Are you monitoring your connection pools? https://docs.dependencytrack.org/getting-started/database-support/#connection-pooling

Not yet with internal metrics but using pg-admin. This is next on my todo since it might highlight discrepencies between what believe DN and the plain reality.

> We made some improvements to how the connection pool(s) are being created in Alpine 2.2.0 / DT 4.7.0. I posted some details in #1935.

I am using 4.7.1

> We now have more flexibility in how HikariCP is configured, as we do that ourselves now instead of delegating it to DataNucleus. What kind of configuration do you have in mind on the HikariCP side to address your concerns?

I believe KeepAlive should do the trick.

> I don't think dead connections are something that should be handled manually by us, I'd expect the connection pool to take care of that. What's more, I don't believe DN would allow us to do it, it's just way too high of an abstraction. It has [its own connection management](https://github.com/datanucleus/datanucleus-core/blob/datanucleus-core-6.0.3/src/main/java/org/datanucleus/store/connection/ConnectionManagerImpl.java) on top of the actual connection pool implementation, it's pretty wild.

Well if any technology gets out of control to this extend, it might be time to get ride of it... Nevertheless the class you point out seems to be good sign we could plug in a different connection manager if this one lack the options for proper tuning.

**Comment by nscuro** [comment]
> Well if any technology gets out of control to this extend, it might be time to get ride of it...

Easier said than done...

> I believe KeepAlive should do the trick.

I raised a PR in Alpine to make keepalive configurable: https://github.com/stevespringett/Alpine/pull/472
