### ISSUE TITLE
Missing graph in 4.7.1

### ISSUE THREAD

**Issue by andresghelarducci** [DependencyTrack/dependency-track#2464]
### Current Behavior

I have an environment that contains multiple projects ( around 50) the project are built using SBOM import with maven plugin and they were showing a graph for each project.
After the upgrade to dependencytrack 4.7.1 I cannot see anymore graph , there is only the main graph node without any other node
![immagine](https://user-images.githubusercontent.com/44871257/217201508-3ffdef3a-5852-4e07-9478-cc152f521e9d.png)

### Steps to Reproduce

1. start with a 4.7.0 projects  with graph
2. upgrade from 4.7.0 to 4.7.1 
3. check graph tab in projects  -> empty

### Expected Behavior

Graph should be present

### Dependency-Track Version

4.7.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by msymons** [comment]
@andresghelarducci, when you click on the component tab on the project page there will be a new icon (introduced in 4.7) to the right of the component name in component name column.   How does that work for you?

Also.. 793 components in a maven project?  That sure is a lot :smile:

**Comment by andresghelarducci** [comment]
Hi, 
I know about the graph button neae each component
![immagine](https://user-images.githubusercontent.com/44871257/217721995-dbf26611-0784-4785-80d3-71fc3cc622c0.png)
unfortunately  if I click on it the result is 
![immagine](https://user-images.githubusercontent.com/44871257/217722303-e71ceb5f-e9f4-4014-9e1d-d0e13b834ad8.png)
But I understood the cause: it seems that dependency track when I update from 4.7.0. to 4.7.1 deleted graph information(while keeping   components & vulnerabilities), infact now I forced the SBOM import of project and graph return visible again
![immagine](https://user-images.githubusercontent.com/44871257/217722637-97db7e92-78d5-4046-be99-96163276cf81.png)
In my case I have 50 projects so I lost a relevant info until I reimport them
Maybe not keeping graph information during an update shall be considered a bug?

**Comment by rkg-mm** [comment]
I wonder how this happened, since no change in 4.7.1. should be related to this graph from what I see. there were changes towards 4.7.0, but those should be fine and not be lost from own experience, also you said you were on 4.7.0 before...
Anyone else saw this?

**Comment by FabioRighe** [comment]
@andresghelarducci check issue that I open, maybe this could be the cause. [https://github.com/DependencyTrack/dependency-track/issues/2494](url)

**Comment by nscuro** [comment]
As @rkg-mm said there were no related changes in the version you upgraded to. So I am a bit baffled as to how this could have happened.

Is this behavior consistent for all your projects or is it just this one?

**Comment by andresghelarducci** [comment]
Hi, 
I confirm that I lost graph in ALL projects

Andres

**Comment by lucsoft** [comment]
its not only 4.7.1 saw it also in 4.7.0

**Comment by andresghelarducci** [comment]
Just an upgrade : today the problem happened again, all projects lost its graph and it appears again after on next build, I found the following errors .
Can you check if this is a bug ?

Andres

```
2023-04-17 07:18:44,940 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: c1b26cc9-da2e-4ed2-92bf-f8cf13f167c0
2023-04-17 07:18:46,621 INFO [BomUploadProcessingTask] Identified 7 new components
2023-04-17 07:18:46,621 INFO [BomUploadProcessingTask] Processing CycloneDX dependency graph for project: c1b26cc9-da2e-4ed2-92bf-f8cf13f167c0
2023-04-17 07:18:46,727 INFO [BomUploadProcessingTask] Processed 327 components and 0 services uploaded to project c1b26cc9-da2e-4ed2-92bf-f8cf13f167c0
2023-04-17 07:18:46,727 INFO [RepositoryMetaAnalyzerTask] Performing component repository metadata analysis against 327 components
2023-04-17 07:18:46,743 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
org.apache.lucene.store.AlreadyClosedException: Underlying file changed by an external force at 2023-04-14T16:03:35.010807589Z, (lock=NativeFSLock(path=/data/.dependency-track/index/servicecomponent/write.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2023-02-04T10:01:48.59299314Z))
        at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:191)
        at org.apache.lucene.store.LockValidatingDirectoryWrapper.syncMetaData(LockValidatingDirectoryWrapper.java:61)
        at org.apache.lucene.index.SegmentInfos.prepareCommit(SegmentInfos.java:802)
        at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:5084)
        at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3460)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3770)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3728)
        at org.dependencytrack.search.IndexManager.commit(IndexManager.java:249)
        at org.dependencytrack.tasks.IndexTask.inform(IndexTask.java:65)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)



2023-04-17 07:18:50,847 INFO [BomUploadProcessingTask] Processing CycloneDX dependency graph for project: 1780711b-7663-435c-91d9-984cb834645a
2023-04-17 07:18:50,856 INFO [BomUploadProcessingTask] Processed 735 components and 0 services uploaded to project 1780711b-7663-435c-91d9-984cb834645a
2023-04-17 07:18:50,857 INFO [RepositoryMetaAnalyzerTask] Performing component repository metadata analysis against 735 components
2023-04-17 07:18:50,869 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
org.apache.lucene.store.AlreadyClosedException: Underlying file changed by an external force at 2023-04-14T16:03:35.010807589Z, (lock=NativeFSLock(path=/data/.dependency-track/index/servicecomponent/write.lock,impl=sun.nio.ch.FileLockImpl[0:9223372036854775807 exclusive valid],creationTime=2023-02-04T10:01:48.59299314Z))
        at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:191)
        at org.apache.lucene.store.LockValidatingDirectoryWrapper.syncMetaData(LockValidatingDirectoryWrapper.java:61)
        at org.apache.lucene.index.SegmentInfos.prepareCommit(SegmentInfos.java:802)
        at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:5084)
        at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:3460)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:3770)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:3728)
        at org.dependencytrack.search.IndexManager.commit(IndexManager.java:249)
        at org.dependencytrack.tasks.IndexTask.inform(IndexTask.java:65)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)


```

**Comment by nscuro** [comment]
Those `AlreadyClosedException`s (#2379) are unrelated to this problem.

**Comment by andresghelarducci** [comment]
The problem occured during normal operation ( service was not restarted) and that were  the only error messages present in logs today (except some missing synch with defectdojo) , if you want I can provide you the logs

**Comment by nscuro** [comment]
@andresghelarducci Sharing your logs may help. If you're not comfortable with sharing them here, you can DM me in the OWASP Slack (invite [here](https://dependencytrack.org/slack/invite) if you're not on it already). My username is `nscur0`.

**Comment by SaberStrat** [comment]
I'm missing Dependency graphs too in 4.7.1. I don't see new project versions that were created today. I can't tell for sure if I've seen them ever since getting started with DT back in version 4.4.2. Though not remembering seeing them at all could mean they weren't ever there.
As to why I noticed only now: a coworker specificaly asked about that feature.

As a background how our BOMs are imported: 
1. we first create a raw project via API 
2. assign it to a team via ACL API
3. set the project's component type via API
4. upload the BOM via API

**Comment by Polleke696** [comment]
I'm having the same issue with version 4.10.1...

Uploaded various sboms (from cyclonedx, syft, grype) and various projects (custom java, keycloak, etc.) 
and none of them show the dependency graph.

**Comment by alberanid** [comment]
Dependency graphs are still missing as of v4.13.2.

My BOM is as follow (reduced to just 2 components):

```json

{
  "bomFormat": "CycloneDX",
  "specVersion": "1.4",
  "serialNumber": "urn:uuid:c524c74c-845c-4c8e-8c50-2887550f8367",
  "version": 1,
  "metadata": {
    "timestamp": "2025-05-14T07:48:13.776677+00:00",
    "tools": [
      {
        "name": "yocto"
      }
    ]
  },
  "components": [
    {
      "name": "glibc",
      "version": "2.35",
      "type": "library",
      "cpe": "cpe:2.3:*:*:glibc:2.35:*:*:*:*:*:*:*",
      "purl": "pkg:generic/glibc@2.35",
      "bom-ref": "8147ec1c-ba66-4388-85e4-3dd75bfe085e"
    },
    {
      "name": "acl",
      "version": "2.3.1",
      "type": "library",
      "cpe": "cpe:2.3:*:*:acl:2.3.1:*:*:*:*:*:*:*",
      "purl": "pkg:generic/acl@2.3.1",
      "bom-ref": "8f2cecb4-4aa4-4311-a966-518436a09c8a"
    }
  ],
  "dependencies": [
    {
      "ref": "8f2cecb4-4aa4-4311-a966-518436a09c8a",
      "dependsOn": [
        "8147ec1c-ba66-4388-85e4-3dd75bfe085e"
      ]
    }
  ]
}
```

In the logs I see that it detects 220 dependency graph entries, but still nothing is shown on the UI.

Logs:

```
apiserver-1  | 2025-05-23 09:08:20,748 INFO [BomUploadProcessingTask] Processing 447 components [bomSerialNumber=c524c74c-845c-4c8e-8c50-2887550f8367, bomFormat=CycloneDX, bomUploadToken=99770cda-b285-48cf-82fa-f53c17dad7da, projectName=yocto-divus, bomSpecVersion=1.4, projectUuid=55d7b4e9-955b-419c-95df-a95ce0b90731, projectVersion=0.0.4, bomVersion=1]
apiserver-1  | 2025-05-23 09:08:20,919 INFO [BomUploadProcessingTask] Processing 0 services [bomSerialNumber=c524c74c-845c-4c8e-8c50-2887550f8367, bomFormat=CycloneDX, bomUploadToken=99770cda-b285-48cf-82fa-f53c17dad7da, projectName=yocto-divus, bomSpecVersion=1.4, projectUuid=55d7b4e9-955b-419c-95df-a95ce0b90731, projectVersion=0.0.4, bomVersion=1]
apiserver-1  | 2025-05-23 09:08:20,922 INFO [BomUploadProcessingTask] Processing 220 dependency graph entries [bomSerialNumber=c524c74c-845c-4c8e-8c50-2887550f8367, bomFormat=CycloneDX, bomUploadToken=99770cda-b285-48cf-82fa-f53c17dad7da, projectName=yocto-divus, bomSpecVersion=1.4, projectUuid=55d7b4e9-955b-419c-95df-a95ce0b90731, projectVersion=0.0.4, bomVersion=1]
apiserver-1  | 2025-05-23 09:08:20,997 INFO [BomUploadProcessingTask] BOM processed successfully in 00:00:00.408 [bomSerialNumber=c524c74c-845c-4c8e-8c50-2887550f8367, bomFormat=CycloneDX, bomUploadToken=99770cda-b285-48cf-82fa-f53c17dad7da, projectName=yocto-divus, bomSpecVersion=1.4, projectUuid=55d7b4e9-955b-419c-95df-a95ce0b90731, projectVersion=0.0.4, bomVersion=1]
apiserver-1  | 2025-05-23 09:08:21,002 INFO [RepositoryMetaAnalyzerTask] Performing component repository metadata analysis against 447 components
apiserver-1  | 2025-05-23 09:08:21,222 INFO [RepositoryMetaAnalyzerTask] Completed component repository metadata analysis against 447 components
apiserver-1  | 2025-05-23 09:08:21,223 INFO [PolicyEngine] Evaluating 447 component(s) against applicable policies [eventToken=912a66bd-7306-479b-9019-82da662376bc, projectName=yocto-divus, projectUuid=55d7b4e9-955b-419c-95df-a95ce0b90731, projectVersion=0.0.4]
apiserver-1  | 2025-05-23 09:08:21,884 INFO [InternalAnalysisTask] Starting internal analysis task [eventToken=99770cda-b285-48cf-82fa-f53c17dad7da, projectName=yocto-divus, vulnAnalysisLevel=BOM_UPLOAD_ANALYSIS, projectUuid=55d7b4e9-955b-419c-95df-a95ce0b90731, projectVersion=0.0.4]
apiserver-1  | 2025-05-23 09:08:21,884 INFO [InternalAnalysisTask] Analyzing 447 component(s) [eventToken=99770cda-b285-48cf-82fa-f53c17dad7da, projectName=yocto-divus, vulnAnalysisLevel=BOM_UPLOAD_ANALYSIS, projectUuid=55d7b4e9-955b-419c-95df-a95ce0b90731, projectVersion=0.0.4]
apiserver-1  | 2025-05-23 09:08:22,316 INFO [PolicyEngine] Policy analysis complete [eventToken=912a66bd-7306-479b-9019-82da662376bc, projectName=yocto-divus, projectUuid=55d7b4e9-955b-419c-95df-a95ce0b90731, projectVersion=0.0.4]
apiserver-1  | 2025-05-23 09:08:22,316 INFO [ProjectMetricsUpdateTask] Executing metrics update for project 55d7b4e9-955b-419c-95df-a95ce0b90731
```

**Comment by nscuro** [comment]
@alberanid In your case the problem is that there is no `metadata.component` node (which maps to the project in DT, conceptually). DT can thus not make out a root of the graph.

Without such a root node, DT won't be able to differentiate between `acl` being the root (because nothing else depends on it), and a relationship between `acl` and something else simply missing.

You can find a full example here: https://cyclonedx.org/use-cases/software-dependencies/

**Comment by alberanid** [comment]
> the problem is that there is no `metadata.component` node

that was it, thank you very much - I missed that information.

Tested, and in my case solves the problem (partially: I still have to understand how to include all the dependencies that comes from a series of package groups in a Yocto distribution, but that's another story).

Thanks!
