### ISSUE TITLE
DT Track takes error when Author is greater than 255 characters in SBOM during import

### ISSUE THREAD

**Issue by nigellh** [DependencyTrack/dependency-track#2488]
### Current Behavior

After importing an SBOM, we noticed that it was not populating the vulnerabilities as expected (might be unrelated) and so I looked at the logs and saw a fair number of these:

```
[36mdtrack-apiserver_1  |[0m 2023-02-10 18:26:19,671 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: 6747cf15-28f8-4ef5-a37d-3b1f3cdb3855
[36mdtrack-apiserver_1  |[0m 2023-02-10 18:27:05,897 ERROR [BomUploadProcessingTask] Error while processing bom
[36mdtrack-apiserver_1  |[0m javax.jdo.JDOFatalUserException: Attempt to store value "Douglas Bates [aut], Martin Maechler [aut, cre] (<https://orcid.org/0000-0002-8685-9910>), Timothy A. Davis [ctb] (SuiteSparse and 'cs' C libraries, notably CHOLMOD, AMD; collaborators listed in dir(pattern = '^[A-Z]+[.]txt$', full.names=TRUE, system.file('doc', 'SuiteSparse', package='Matrix'))), Jens Oehlschlägel [ctb] (initial nearPD()), Jason Riedy [ctb] (condest() and onenormest() for octave, Copyright: Regents of the University of California), R Core Team [ctb] (base R matrix implementation)" in column "AUTHOR" that has maximum length of 255. Please correct your data!
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:678)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:702)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:722)
[36mdtrack-apiserver_1  |[0m 	at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:427)
[36mdtrack-apiserver_1  |[0m 	at org.dependencytrack.persistence.ComponentQueryManager.createComponent(ComponentQueryManager.java:320)
[36mdtrack-apiserver_1  |[0m 	at org.dependencytrack.persistence.QueryManager.createComponent(QueryManager.java:468)
[36mdtrack-apiserver_1  |[0m 	at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:181)
[36mdtrack-apiserver_1  |[0m 	at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:127)
[36mdtrack-apiserver_1  |[0m 	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
[36mdtrack-apiserver_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[36mdtrack-apiserver_1  |[0m 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[36mdtrack-apiserver_1  |[0m 	at java.base/java.lang.Thread.run(Unknown Source)
[36mdtrack-apiserver_1  |[0m Caused by: org.datanucleus.exceptions.NucleusUserException: Attempt to store value "Douglas Bates [aut], Martin Maechler [aut, cre] (<https://orcid.org/0000-0002-8685-9910>), Timothy A. Davis [ctb] (SuiteSparse and 'cs' C libraries, notably CHOLMOD, AMD; collaborators listed in dir(pattern = '^[A-Z]+[.]txt$', full.names=TRUE, system.file('doc', 'SuiteSparse', package='Matrix'))), Jens Oehlschlägel [ctb] (initial nearPD()), Jason Riedy [ctb] (condest() and onenormest() for octave, Copyright: Regents of the University of California), R Core Team [ctb] (base R matrix implementation)" in column "AUTHOR" that has maximum length of 255. Please correct your data!
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.store.rdbms.mapping.column.CharColumnMapping.setString(CharColumnMapping.java:253)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.store.rdbms.mapping.java.SingleFieldMapping.setString(SingleFieldMapping.java:202)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.store.rdbms.fieldmanager.ParameterSetter.storeStringField(ParameterSetter.java:158)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.state.StateManagerImpl.providedStringField(StateManagerImpl.java:1903)
[36mdtrack-apiserver_1  |[0m 	at org.dependencytrack.model.Component.dnProvideField(Component.java)
[36mdtrack-apiserver_1  |[0m 	at org.dependencytrack.model.Component.dnProvideFields(Component.java)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:2559)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:383)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4587)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4564)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2014)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.ExecutionContext.persistObjectInternal(ExecutionContext.java:320)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1862)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1723)
[36mdtrack-apiserver_1  |[0m 	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:697)
[36mdtrack-apiserver_1  |[0m 	... 10 common frames omitted
```

### Steps to Reproduce

1. Create a CDX SBOM that has an author field than 255 characters. Any SBOM will do and just manually edit one of the author fields to have grater than 255 characters. Use the data from the above error if needed.
2. Create a project in DT
3. Import the SBOM
4. Check the logs

### Expected Behavior

Good question. If length is a concern, truncate it rather than error and in the actual author data imported perhaps put (truncated) at the end so it is clear this has been done.

You could lengthen it, but then how long is enough? I suggest the above is good and show in the logs it was truncated as well

Cannot answer some of the details below.

I just did a curl followed by a docker-compose mid January to create the system, so it is whatever the basics are for one of these systems.

### Dependency-Track Version

4.6.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nigellh** [comment]
I am unable to give you the exact SBOM as there were several and they are internal distribution only, but I would expect any should do it.

**Comment by olafz** [comment]
We run into the same issue. 

The Multipart::Post library contains an author field that contains a very lengthy author field: https://github.com/socketry/multipart-post/blob/main/multipart-post.gemspec#L10
