### ISSUE TITLE
javax.jdo.JDOUserException: Field org.dependencytrack.model.Component.repositoryMeta is not marked as persistent so cannot be queried

### ISSUE THREAD

**Issue by walterdeboer** [DependencyTrack/dependency-track#2562]
### Current Behavior

When opening the Policy Violations tab, the PolicyViolationResource throws the following error and no violations are shown. 

Breaks on a new empty project in a new empty database, as well as on a project that has violations according to the project overview

```
javax.jdo.JDOUserException: Field org.dependencytrack.model.Component.repositoryMeta is not marked as persistent so cannot be queried
at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:698)
at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:456)
at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:276)
at alpine.persistence.AbstractAlpineQueryManager.execute(AbstractAlpineQueryManager.java:174)
at org.dependencytrack.persistence.PolicyQueryManager.getPolicyViolations(PolicyQueryManager.java:280)
at org.dependencytrack.persistence.QueryManager.getPolicyViolations(QueryManager.java:604)
at org.dependencytrack.resources.v1.PolicyViolationResource.getViolationsByProject(PolicyViolationResource.java:102)
```

### Steps to Reproduce

1.Open the Policy Violations tab for a project in the frontend

### Expected Behavior

No Exception is thrown and violations are shown (if any)

### Dependency-Track Version

4.8.0-SNAPSHOT

### Dependency-Track Distribution

Executable WAR

### Database Server

H2

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Can't reproduce with current `master` of both API server and frontend. 

What commit of `4.8.0-SNAPSHOT` are you using?

**Comment by walterdeboer** [comment]
Sorry, my bad. It's caused by an orderBy that's somehow comming from the frontend and is stored in some state somehow...

**Comment by walterdeboer** [comment]
Thanks for checking!

**Comment by walterdeboer** [comment]
ah, I messed up my local storage
