### ISSUE TITLE
OSS Index Scanner Configuration: Test Connection Button

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#265]
### Issue Type:
  - [ ] defect report
  - [X] enhancement request

This enhancement separates out a suggestion originally made in #264.
  
### Current Behavior:
Dependency-Track Admin (scanners) provides a screen for enabling OSS Index Scanner, requiring that credentials are provided (username and API token).

If the credentials are not correct, then performing a CycloneDX publish from Jenkins  does generate a report - and the only way to know that there was an authentication error from the logs...

```
 2019-01-15 11:39:08,409 [] INFO [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
2019-01-15 11:39:09,201 [] WARN [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Received unexpected HTTP response 401 Unauthorized
2019-01-15 11:39:09,201 [] INFO [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Analyzing 100 component(s)
2019-01-15 11:39:14,201 [] INFO [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Sonatype OSS Index analysis complete
2019-01-15 11:39:14,214 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: a5034962-c5da-45de-9348-f3480567cabe
```
The succesful analysis coupled with an HTTP 401 matches OSS Index documentation for the REST API...

> Rate limits apply to requests. If the rate is exceeded then responses will indicate 429 Too many requests status.
> 
> Authenticated requests have a higher limit
> 

### Expected Behavior:

Provide a button on the configuration screen for OSS Index to allow the connection to be tested.  This will allow the admin to check that credentials are correct without having to wait for an analysis to be performed and without having to examine the logs.  It would also validate the connection from Dependency-Track server to the OSS Index website  (routing problems, firewall block, etc)

### Environment:
  
  - Dependency-Track Version: v3.4.0

**Comment by stevespringett** [comment]
OSSIndex only has one endpoint that could potentially be used for this sort of connection test: /api/v3/version

Need to investigate if this endpoint responds to authenticated requests or not. If not, an enhancement would need to be filed with Sonatype.

**Comment by msymons** [comment]
I tested the `/api/v3/version` endpoint and it does respond to authenticated requests.

I used the [REST API page](https://ossindex.sonatype.org/rest) and performed "Authorize", followed by trying out `/api/v3/component-report/{coordinates}` to give me a valid authorization string for usage in curl.

I then ran the following (inserting "-v" option so I could see the response headers)
```
curl -X GET "https://ossindex.sonatype.org/api/v3/version" - v -H "accept: application/vnd.ossindex.version.v1+json" -H  "authorization: Basic validvalue"
```
...gave a 200 response.

```
curl -X GET "https://ossindex.sonatype.org/api/v3/version" - v -H "accept: application/vnd.ossindex.version.v1+json" -H  "authorization: Basic invalidvalue"
```
...gave a 401 response.

**Comment by Gu-glitch** [comment]
Hi,

## Request(s)

Would it be possible to add a check button to the analyzer configuration page of Sonatype OSS Index?

Also Would it be possible to change the "API Username" to "API Email" as shown in the Sonatype OSS Index user settings?

## Technical part

As @msymons said we can't use the /api/v3/version endpoint because it doesn't need to be authenticated to be requested.

So we have to use the "Request vulnerability report for component": /api/v3/component-report/{coordinates}

`curl -X GET "https://ossindex.sonatype.org/api/v3/component-report/pkg%3Apypi%2Fpillow%402.3.0" -H  "accept: application/vnd.ossindex.component-report.v1+json" -H  "authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"`

From what we can get a 200 status code response. But selecting a particular vulnerability hoping It will not be removed is not that great. Maybe contacting SonaType would be a great idea?
**reference:** ( https://ossindex.sonatype.org/swagger.json ) 

## Design part:

### Check Button
`<button type="button" class="btn btn-secondary btn-config-property" id="checkOssIndexConfigButton" data-group-name="scanner">Check</button>`

![dtrack-check](https://user-images.githubusercontent.com/56113081/69353900-89c52500-0c7f-11ea-87eb-795a1f005947.png)

### Success event
```
<div role="alert" class="alert alert-success">
 Success! Your access is correctly configured </div>
```
![dtrack-check-ok](https://user-images.githubusercontent.com/56113081/69353902-89c52500-0c7f-11ea-9468-81259349f967.png)

### Fail event

> <div role="alert" class="alert alert-danger">
>  Failed! Please verify your API Email, API Token or your access to Sonatype OSS Index </div>
> 
> 



![dtrack-check-fail](https://user-images.githubusercontent.com/56113081/69353901-89c52500-0c7f-11ea-8b9e-513b3627f69e.png)

**Comment by msymons** [comment]
Another reason for a test button...  a 4.8.0 snapshot deployment seems to have "lost" its' secret key and is logging the followng for every BOM upload:

```
2023-02-14 14:38:27,824 ERROR [OssIndexAnalysisTask] An error occurred decrypting the OSS Index API Token. Skipping
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at java.base/com.sun.crypto.provider.CipherCore.unpad(Unknown Source)
	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(Unknown Source)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(Unknown Source)
	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.Cipher.doFinal(Unknown Source)
	at alpine.security.crypto.DataEncryption.decryptAsBytes(DataEncryption.java:136)
	at alpine.security.crypto.DataEncryption.decryptAsBytes(DataEncryption.java:148)
	at alpine.security.crypto.DataEncryption.decryptAsString(DataEncryption.java:176)
	at org.dependencytrack.tasks.scanners.OssIndexAnalysisTask.inform(OssIndexAnalysisTask.java:137)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.performAnalysis(VulnerabilityAnalysisTask.java:169)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.analyzeComponents(VulnerabilityAnalysisTask.java:128)
	at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:77)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

...but without showing any problem whatsoever in the UI.  The  problem is that it is possible for people to have permissions to administer DT via UI/API but do not have access to logs.

**Comment by nscuro** [comment]
This is shipping with v5 finally!
