### ISSUE TITLE
Web front-end crash

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#273]
### Issue Type:
  - [X] defect report
  - [ ] enhancement request
  
  
### Current Behavior:
On more than one occasion, Dependency-Track has had a crashed web server (the UI), even whilst there is nothing odd in the logs and normal tasks are seeming to continue to run as normal.

I have previously reported CPU problems via #264, and attached a screenshot of a "UI-gone-wrong" to the initial report.  ie, web server running and just shows directory WEB-INF.   What I am reporting here is something different, as my DT server currently runs with npm analyser disabled and the CPU utilisation is bubbling along for day after day at a steady 3% with spikes to 10% (that indicate DT tasks running).

After a service restart, everything was back to normal with the UI.

I did not test dependency-track jenkins plugin whilst the DT web UI was down...  but I am sure it would not have been possible to publish a BOM from Jenkins.

### Steps to Reproduce (if defect):
Hard to reproduce as DT can be up and running fine for a period and suddenly cannot be accessed via the UI.

### Expected Behavior:
Stable webserver.

### Environment:
  
  - Dependency-Track Version:  v3.4.0
  - Distribution: [Executable WAR]
  - Database Server: [PostgreSQL]
  - Browser:   Firefox v64

### Other Details:
(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

When the webserver is accessed, it displays:

```
Problem accessing /WEB-INF/fragments/error.jsp. Reason:
--
 
/WEB-INF/fragments/error.jsp
 
Caused by:
 
org.apache.jasper.JasperException: org.apache.jasper.JasperException: java.io.FileNotFoundException: /tmp/jetty-0.0.0.0-8080-dependency-track-embedded.war-_-any-1020949971490178642.dir/webapp/WEB-INF/lib/encoder-jsp-1.2.2.jar (No such file or directory)
at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:579)
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:403)
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
...
```
Let me know if you need the full exception  (I am logging this issue from home and do not currently just have the above snippet to hand).

Although I report that the logs contained nothing odd, there was a single error event relating to the above exception that was recorded each time the UI URL was visited.

**Comment by stevespringett** [comment]
I'm not sure how a filesystem issue is the responsibility of Dependency-Track. Have you tried changing the location of the tmp folder to something that may have more space (assuming space is the issue).

I think the more appropriate place to check would be OS logs.

Also, since performance can be tuned, you may want to try that as a temporary measure for #264

**Comment by msymons** [comment]
Our Dependency-Track server was upgraded in December 2018 and is now operating on a [Standard_D2s_v3](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dsv3-series-sup1sup) Azure VM. 

There have been no diskspace (or any other) issues since npm analyser was disabled.

The database is running on a separate service (Azure Database for PostgreSQL)

Nothing else is running on the DT server apart from DT itself and nginx (for reverse proxy).

Whilst there may be something going on with the VM (ie, nothing to do with DT itself),  I logged this issue because DT webserver has gone belly-up for us more than once..  and this time there was the FileNotFoundException.   I was hoping that if there *were* a problem I might be reporting it in time to help with your current hardening exercise that will result in DT v3.5 release.

Is it OK to keep this issue open whilst I keep an eye on things and see if the webserver falls over again?

**Comment by msymons** [comment]
Our Dependency-Track server was upgraded in December 2018 and is now operating on a [Standard_D2s_v3](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dsv3-series-sup1sup) Azure VM. 

There have been no diskspace (or any other) issues since npm analyser was disabled.

The database is running on a separate service (Azure Database for PostgreSQL)

Nothing else is running on the DT server apart from DT itself and nginx (for reverse proxy).

Whilst there may be something going on with the VM (ie, nothing to do with DT itself),  I logged this issue because DT webserver has gone belly-up for us more than once..  and this time there was the FileNotFoundException.   I was hoping that if there *were* a problem I might be reporting it in time to help with your current hardening exercise that will result in DT v3.5 release.

Is it OK to keep this issue open whilst I keep an eye on things and see if the webserver falls over again?

**Comment by stevespringett** [comment]
Yes, you can keep the ticket open.

One thing that would REALLY help out a lot are folks willing to beta test 3.5 snapshots and do so without affecting production data. Basically having a standalone 3.5 installation with a dedicated database just for 3.5 to test the progress that's being made.

Docker snapshots are always available. Traditional and executable wars currently need to be compiled from source, but I'll likely create a snapshot repo for those as well.

A lot of work has gone into refactoring use of HttpClient usage - so all outbound connections such as NPM Audit, OSSIndex, Slack, MSTeams, etc should see noticable improvements. There's also 4 new configuration properties for configuring database connection pool settings and the timeout for the maxLifetime has changed from 30 minutes to 10 minutes. It's important to keep this number slightly shorter than the value imposed by the database server or any network device capable of terminating persistent connections.

These changes along with minor bug fixes and the snapshot releases are likely a bit more stable than the 3.4 released version. But confirmation of that would be really helpful.

**Comment by msymons** [comment]
If an executable war is available then I can spin up a new VM and test.

**Comment by msymons** [comment]
@stevespringett, now that I am running 3.5 snapshot I am double-checking configuration, even though I am using PostgreSQL in production and embedded H2 database. 

> 4 new configuration properties for configuring database connection pool settings and the timeout for the maxLifetime has changed from 30 minutes to 10 minutes

What are these 4 new configuration properties?  I see 4 properties in [configuration documentation](https://docs.dependencytrack.org/getting-started/configuration/):

```
alpine.database.pool.enabled=true
alpine.database.pool.max.size=10
alpine.database.pool.idle.timeout=600000
alpine.database.pool.max.lifetime=600000
```
...that I assume were added in v3.4.0, as they are missing from my own `application.properties` file, datestamped November 2018 (and thus created based on v3.3.1 documentation).

Aside: I have logged #283 as a small enhancement request for documenting such changes.

**Comment by stevespringett** [comment]
These properties were added to 3.5 and got pushed to the documentation by accident. However, I'm leaving them out there since some folks are testing 3.5 and will need to refer to the docs for them.

**Comment by msymons** [comment]
@stevespringett, I am afraid that Dependency-Track v3.5.0 UI has crashed for me today for the first time, after running perfectly for 10 days.

**server.log:**
```
2019-06-07 10:31:10,923 [] INFO [org.eclipse.jetty.server.Server] Started @45360ms
2019-06-17 16:32:46,458 [] WARN [org.eclipse.jetty.server.HttpChannel] /vulnerability/ java.io.FileNotFoundException: /tmp/jetty-0.0.0.0-8080-dependency-track-embedded.war-_-any-4783278788638272453.dir/webapp/WEB-INF/lib/encoder-jsp-1.2.2.jar (No such file or directory)
2019-06-17 16:33:19,103 [] WARN [org.eclipse.jetty.server.HttpChannel] /vulnerability/ java.io.FileNotFoundException: /tmp/jetty-0.0.0.0-8080-dependency-track-embedded.war-_-any-4783278788638272453.dir/webapp/WEB-INF/lib/encoder-jsp-1.2.2.jar (No such file or directory)
2019-06-17 16:43:35,746 [] INFO [org.eclipse.jetty.server.AbstractConnector] Stopped ServerConnector@5b275dab{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-06-17 16:43:35,747 [] INFO [org.eclipse.jetty.server.session] node0 Stopped scavenging
2019-06-17 16:43:35,779 [] INFO [org.eclipse.jetty.server.handler.ContextHandler] Stopped o.e.j.w.WebAppContext@476a38d9{/,file:///tmp/jetty-0.0.0.0-8080-dependency-track-embedded.war-_-any-4783278788638272453.dir/webapp/,UNAVAILABLE}{file:/opt/dep-track/dependency-track-embedded.war}
```
**dependency-track.log**, showing an ERROR at 16:32, but also showing that backend (eg MetricsUpdateTask) is still perfectly fine until the server was manually shut down for restart.
```
2019-06-17 16:32:11,393 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: null
2019-06-17 16:32:11,459 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: 1fa1a6af-31af-4934-8a59-990ec1a80521
...
2019-06-17 16:43:30,440 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: 5a0f62fe-c347-4e6b-bef6-1d36faa10c4d
2019-06-17 16:43:35,749 [] INFO [alpine.AlpineServlet] Stopping Dependency-Track
```
Per previous updates, there is no diskspace issue on the server.

**Comment by stevespringett** [comment]
What happens when the executable war is restarted?

**Comment by msymons** [comment]
A restart always succesfully returns everything to normal working order....  until the next UI crash 10 days or so later.

**Comment by stevespringett** [comment]
This is likely due to the temp directory being cleaned up by an OS process (or similar).

Try changing the temp directory Jetty uses to something other than temp. For example:

```
-Djava.io.tmpdir=/path/to/alternateTempDir
```

```
java -Xmx4G -Djava.io.tmpdir=/path/to/alternateTempDir -jar dependency-track-embedded.war
```

**Comment by msymons** [comment]
@stevespringett, I have reconfigured per your suggestion and restarted.  So now I just need to wait for 14+ days (from today) before I'll know whether or not the UI keeps running without the crash.

**Comment by msymons** [comment]
@stevespringett, exactly one hour after restart using tweaked `/etc/sysconfig/dependency-track`, the dependency-track.log recorded:

`JAVA_OPTS=-Xmx4G -Dalpine.application.properties=~/.dependency-track/application.properties -Djava.io.tmpdir=/opt/dep-track/temp -Dlogback.configurationFile=/opt/dep-track/.dependency-track/logback.xml
`
```
2019-06-21 13:12:01,350 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: 39c514da-6025-4ffa-b527-aef762ee5892
2019-06-21 13:12:02,031 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
kong.unirest.UnirestException: org.apache.http.client.ClientProtocolException
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:121)
	at kong.unirest.BaseRequest.asJson(BaseRequest.java:194)
	at org.dependencytrack.notification.publisher.AbstractWebhookPublisher.publish(AbstractWebhookPublisher.java:51)
	at org.dependencytrack.notification.publisher.WebhookPublisher.inform(WebhookPublisher.java:32)
	at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:63)
	at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.client.ClientProtocolException: null
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:113)
	... 8 common frames omitted
Caused by: org.apache.http.ProtocolException: Target host is not specified
	at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71)
	at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 12 common frames omitted
...
(Repeated another 4 times in space of few milliseconds)
2019-06-21 13:12:02,619 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: ba1f1fb7-b870-419c-a715-1b7e2ec167f4
```
The new tmpdir specified is owned by user dep-track.

Possible cause and effect, or should I log a new issue?

**Comment by stevespringett** [comment]
That appears to be a webhook related configuration issue

**Comment by msymons** [comment]
It was webhooks.  Sorry... I should have read further down the exception!   A "Slack" Alert had been created and left without the `Destination` specified (whilst awaiting help from our Slack admin).

is it worth logging a (low priority) defect for this, in that the result of such config omission results in over 2,000 lines of Exception ERROR logging in the space of 30 seconds?

**Comment by stevespringett** [comment]
Yeah, go ahead. I think some minor improvement could be made to catch the destination being omitted and to simplify logging a bit.

**Comment by msymons** [comment]
@stevespringett, my DT server required a restart today (3.5.1 upgrade).

Until this restart, it had been running without problem for 27 days without a UI crash... using the alternate temp directory really seems to have helped.

It surprises me that no one else seems to have had similar issues...  our DT is running on a standard Azure VM and I am pretty certain that no adjustments were made to standard tempdir management.

**Comment by stevespringett** [comment]
Thats great news. In a perfect world, there would be no need for a restart. But if the server continues to stay up for extended periods of time, then go ahead close this ticket. I do think the temp dir issue would be good to document however. I will likely be restructuring the docs when 3.6 is released and including a FAQ or troubleshooting doc as part of it. I think this issue should be documented there.
