### ISSUE TITLE
404 Not Found repeating error in API Logs in K8s

### ISSUE THREAD

**Issue by p0457** [DependencyTrack/dependency-track#2775]
### Current Behavior

Greetings,
I am standing up Dependency-Track in a Kubernetes cluster and utilizing the Docker instructions (for the most part). I managed to get through some of the other issues, but I've got a new one where we're getting a 404 Not Found recurring in the logs for the API. For whatever reason, this is causing the Frontend to not respond either. Nothing in the Frontend logs. 

API logs are below, this is the repeating error. As you can see, it's not that helpful and I don't know what the issue might be. Any ideas? 

BTW I am fully aware Kubernetes is not "officially supported", I'm more of looking for info as to what this unhelpful error is representing so I can better understand where to look for the problem in the stack. Is this from reaching out to an external endpoint? Is this the API failing to resolve from the Frontend? Is it some issue with the CVE/NVD parsing? 

BTW I'm running the latest Docker image as of this writing: https://hub.docker.com/layers/dependencytrack/apiserver/latest/images/sha256-326d5480938c97ba4661218227a17ceba9a485d181e689126c3f73851efa2e88 

```
2023-05-18 20:10:39,807 ERROR [GlobalExceptionHandler] Uncaught internal server error
javax.ws.rs.NotFoundException: HTTP 404 Not Found
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
        at alpine.server.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:225)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at alpine.server.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:93)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at alpine.server.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:166)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1385)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1307)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to Reproduce

The full yaml for the K8s deployment is below, I'm not expecting someone to just fix it for me, but maybe it will give a hint?

```
apiVersion: v1
kind: Namespace
metadata:
  name: dtrack
  labels:
    name: dtrack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dtrack-api
  namespace: dtrack
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dtrack-api
  name: dtrack-api
  namespace: dtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtrack-api
  template:
    metadata:
      labels:
        app: dtrack-api
    spec:
      containers:
      - env:
        - name: ALPINE_CORS_ENABLED
          value: "true"
        - name: ALPINE_CORS_ALLOW_ORIGIN
          value: "*"
        - name: ALPINE_CORS_ALLOW_METHODS
          value: "GET, POST, PUT, DELETE, OPTIONS"
        - name: ALPINE_CORS_ALLOW_HEADERS
          value: "Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count, *"
        - name: ALPINE_CORS_EXPOSE_HEADERS
          value: "Origin, Content-Type, Authorization, X-Requested-With, Content-Length, Accept, Origin, X-Api-Key, X-Total-Count"
        - name: ALPINE_CORS_ALLOW_CREDENTIALS
          value: "true"
        - name: ALPINE_CORS_MAX_AGE
          value: "3600"
        image: dependencytrack/apiserver:latest
        imagePullPolicy: IfNotPresent
        name: dtrack-api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 8Gi
          requests:
            cpu: 2
            memory: 4.5Gi
        volumeMounts:
        - mountPath: /data
          name: dtrack-api
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      volumes:
      - name: dtrack-api
        persistentVolumeClaim:
          claimName: dtrack-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dtrack-api
  name: dtrack-api
  namespace: dtrack
spec:
  type: ClusterIP
  clusterIP: 172.20.0.100
  clusterIPs:
  - 172.20.0.100
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dtrack-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dtrack-api
  namespace: dtrack
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/security-groups: REDACTED
    alb.ingress.kubernetes.io/healthcheck-path: /api/system/status
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '2'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    external-dns.alpha.kubernetes.io/hostname: REDACTED
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=120
  labels:
    app: dtrack-api
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType:
          ImplementationSpecific
        backend:
          service:
            name: dtrack-api
            port: 
              number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dtrack-app
  name: dtrack-app
  namespace: dtrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dtrack-app
  template:
    metadata:
      labels:
        app: dtrack-app
    spec:
      containers:
      - env:
        - name: API_BASE_URL
          value: REDACTED
        image: dependencytrack/frontend
        imagePullPolicy: IfNotPresent
        name: dtrack-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 2
            memory: 1Gi
          requests:
            cpu: 1
            memory: 512M
      restartPolicy: Always
      schedulerName: default-scheduler
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dtrack-app
  name: dtrack-app
  namespace: dtrack
spec:
  type: ClusterIP
  clusterIP: 172.20.0.101
  clusterIPs:
  - 172.20.0.101
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dtrack-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dtrack-app
  namespace: dtrack
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/security-groups: REDACTED
    alb.ingress.kubernetes.io/healthcheck-path: /api/system/status
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '2'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    external-dns.alpha.kubernetes.io/hostname: REDACTED
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=120
  labels:
    app: dtrack-app
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType:
          ImplementationSpecific
        backend:
          service:
            name: dtrack-app
            port: 
              number: 8080
```

### Expected Behavior

I expect the Dependency-Track API and Frontend to be able to start up without error. 

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

H2

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by syalioune** [comment]
Hello @p0457 

My best guess would be `alb.ingress.kubernetes.io/healthcheck-path: /api/system/status` that point to a non matching path for both api-server and frontend container leading to the periodic 404 error and the ALB (I'm guessing from AWS EKS) deregistering the container instances.
You can try with `alb.ingress.kubernetes.io/healthcheck-path: /health`
