### ISSUE TITLE
CycloneDX import fails when authors is present

### ISSUE THREAD

**Issue by jblu42** [DependencyTrack/dependency-track#2820]
### Current Behavior

I try to import a CycloneDX SBOM that has been generated by the python CycloneDX library.
The SBOM contains the following values:

, "metadata": {"authors": ["A M"], "timestamp": "2023-06-14T14:11:33.372355+00:00", "tools": [{"name": "python-bom", "vendor": "XY", "version": "5.0.1"}, {"externalReferences": [{"type": "build-system", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/actions"}, {"type": "distribution", "url": "https://pypi.org/project/cyclonedx-python-lib/"}, {"type": "documentation", "url": "https://cyclonedx.github.io/cyclonedx-python-lib/"}, {"type": "issue-tracker", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/issues"}, {"type": "license", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/LICENSE"}, {"type": "release-notes", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CHANGELOG.md"}, {"type": "vcs", "url": "https://github.com/CycloneDX/cyclonedx-python-lib"}, {"type": "website", "url": "https://cyclonedx.org"}], "name": "cyclonedx-python-lib", "vendor": "CycloneDX", "version": "4.0.0"}, {"name": "ABC", "vendor": "DEF", "version": "2022.1.1#17708"}]}, "serialNumber": "urn:uuid:fe093ce2-3539-4b14-8bde-7a9f692fd75f", "version": 1, "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json", "bomFormat": "CycloneDX", "specVersion": "1.4"}

which lead to the following error:

2023-06-15 07:40:22,645 ERROR [BomUploadProcessingTask] Error while processing bom
org.cyclonedx.exception.ParseException: Unable to parse BOM from byte array
        at org.cyclonedx.parsers.JsonParser.parse(JsonParser.java:70)
        at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:105)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.cyclonedx.model.OrganizationalContact` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('A M')
 at [Source: (byte[])"{"components": [{"bom-ref": "0ea9d165-315b-49a5-82e2-b483ac76d08a", "cpe": "", "licenses": [{"name": "Dallas-Semiconductor-License"}], "name": "1-Wire Software Development Kit", "type": "library", "version": "Unspecified"}, {"bom-ref": "6567cd12-ab92-4a65-8187-a4d23432d4b8", "cpe": "", "licenses": [{"name": "License-for-ASN.1-object-dumping-code-by-Peter-Gutmann"}], "name": "ASN.1 object dumping code by Peter Gutmann", "type": "library", "version": "Unspecified"}, {"bom-ref": "776f19d1-596f-4d03"[truncated 27493 bytes]; line: 1, column: 26797] (through reference chain: org.cyclonedx.model.Bom["metadata"]->org.cyclonedx.model.Metadata["authors"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1733)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1358)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1500)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:197)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3738)
        at org.cyclonedx.parsers.JsonParser.parse(JsonParser.java:68)
        ... 5 common frames omitted

when the authors field is removed, the SBOM is successfully imported

### Steps to Reproduce

1. Use authors as defined in SBOM above

### Expected Behavior

No Errors on SBOM import

### Dependency-Track Version

4.8.2

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
This is expected behavior as the BOM is invalid. `metadata.authors` [is an array of objects](https://cyclonedx.org/docs/1.4/json/#metadata_authors), not an array of strings.

**Comment by jblu42** [comment]
@nscuro : Thanks for the quick reply, then I have to look why the CycloneDX python library is producing this invalid SBOM
