### ISSUE TITLE
Does the smtp mailing work from inside a docker container?

### ISSUE THREAD

**Issue by Drewster727** [DependencyTrack/dependency-track#284]
I have set the smtp mail settings exactly like many of my other applications. However, dependency-track does not appear to be capable of sending to my smtp box on port 25. Anything on the host box that I need to do or inside the container itself?

I am starting the container like this:
```
docker run -d -p 8080:8080 --name dependency-track -v dependency-track:/data owasp/dependency-track
```

The error in the container logs:
```
18:16:10.123 ERROR [SendMailPublisher] An error occurred sending output email notification
alpine.mail.SendMailException: An error occurred while sending email
        at alpine.mail.SendMail.send(SendMail.java:235)
        at org.dependencytrack.notification.publisher.SendMailPublisher.inform(SendMailPublisher.java:78)
        at org.dependencytrack.resources.v1.NotificationPublisherResource.testSmtpPublisherConfig(NotificationPublisherResource.java:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:200)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at alpine.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:223)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at alpine.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:91)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at alpine.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:113)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:502)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port:  srv_prod_mail.drewsterdomain.com, 25; timeout -1
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at javax.mail.Service.connect(Service.java:195)
        at javax.mail.Transport.send0(Transport.java:254)
        at javax.mail.Transport.send(Transport.java:124)
        at alpine.mail.SendMail.send(SendMail.java:233)
        ... 65 common frames omitted
Caused by: java.net.UnknownHostException:  srv_prod_mail.drewsterdomain.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:359)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2175)
        ... 72 common frames omitted
```

### Environment:
  
  - Dependency-Track Version: 3.4.0
  - Distribution: Docker
  - BOM Format & Version: latest
  - Database Server: Built-in
  - Browser: Chrome

**Comment by stevespringett** [comment]
Not a Dependency-Track issue as it seems that Java itself is not able to resolve the hostname. However, I came across this thread that may shed some light.

https://stackoverflow.com/questions/37367781/getting-java-net-unknownhostexception-while-running-gocd-docker-container-in-qna

The Dependency-Track Dockerfile specifies a non-root `dtrack` user to run as. This user may not have read access to /etc/hosts and /etc/resolve.conf

If you could experiment and let me know I'd really appreciate it. If it turns out that ACLs are the issue, I'll push an updated Docker image that solves the issue.

**Comment by Drewster727** [comment]
Looks like you could be dead-on with that user access issue:
![image](https://user-images.githubusercontent.com/4528753/52741352-bcc4e480-2f9a-11e9-9d1c-9f25d8c169a4.png)

Let me know how I can further assist with this.

Thanks,
Drew

**Comment by stevespringett** [comment]
it just occurred to me, if /etc/hosts or /etc/resolve.conf was an issue, then nothing would work. NVD mirroring, NPM Audit mirroring, etc.

I verified that read permissions are set on both files and fired up the 3.4.0 container - it works just fine. I'm able to setup an SMTP server and send a test email. So I cannot reproduce this issue. The only SMTP server that I use (outside of day job) is smtp.gmail.com, so that's what I tested with.

If this is an internal SMTP server that requires an internal DNS server be setup, then perhaps this is a Docker host and networking issue. But that doesn't explain why Java is having issues accessing it and netcat is not. I'm at a loss.

**Comment by Drewster727** [comment]
Hmm, could it be that the java code is expecting an auth username/password? I am not supplying those as I don't need to do that internally on my network.

**Comment by davidscottschroeder** [comment]
Greetings everyone!

I am running into a similar issue. I am not as fortunate to be able to ping our smtp box from within the dependency track container. I am however able to ping our smtp box from other containers that are set up the same way.  

@Drewster727 My thinking here is something is wrong with the networking setup for this container but was hoping to get your insight on this first. Was there anything discovered from requiring authentication or networking issues on your end?

**Environment:**
- Dependency-Track Version: 3.8.0
- Distribution: Docker
- BOM Format & Version: latest
- Database Server: Built-in
- Browser: Chrome

**Comment by Mistic92** [comment]
Hi, I'm running it in container too and getting error `SMTP is not enabled`. How to solve this issue?
