### ISSUE TITLE
Uncaught internal server error when authenticating

### ISSUE THREAD

**Issue by webmutation** [DependencyTrack/dependency-track#2947]
### Current Behavior

sbom login stopped working no changes to the system, the only response is 500
Uncaught internal server error

Rest calls also stopped responding.

### Steps to Reproduce

Can't really reproduce the issue. There is no information in the logs

### Expected Behavior

Should be able to login

### Dependency-Track Version

4.7.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by webmutation** [comment]
Additionally here are the logs, no errors are showing up on the apiserver console... on the frontend pod also no logs, but the page renders fine and I can reach the swagger and version information via REST call... 

{"timestamp":"2022-03-04T20:43:17Z","version":"4.4.2","uuid":"7c18dc02-591d-401b-a1a0-7017d2338191","systemUuid":"f6856500-bc60-4008-9f59-43c7b7055172","application":"Dependency-Track","framework":{"timestamp":"2022-03-02T21:59:26Z","version":"1.10.5","uuid":"efb66775-e3f9-4a29-93c1-02f88bf8ad82","name":"Alpine"}}

[dependency-track-apiserver-658c74c446-7pthm.log](https://github.com/DependencyTrack/dependency-track/files/12317282/dependency-track-apiserver-658c74c446-7pthm.log)

I am not sure where this 500 is coming from.

**Comment by antoinbo** [comment]
Hi @webmutation, can you enable the debug trace by adding the `LOGGING_LEVEL=DEBUG` environment variable to your `apiserver` container?

**Comment by nscuro** [comment]
@webmutation Have you tried @antoinbo's suggestion? I remember you were speculating whether storage running full could be a factor in Slack, have you checked that?

Separately, the DT version you're using is *super* old.

**Comment by webmutation** [comment]
There is available storage, the PVs are not even at a third capacity... less than 2G out of 8G total.

I will try to change the logging level... but when I try to edit it throws an error, I probably have to patch the deployment

Indeed the deployment is 491d old, but it run without any issues until earlier this month.

**Comment by webmutation** [comment]
Here are the Logs with Debug enabled... still no clue what is going on, the 500 and the exception do not show up in the logs.

[dependency-track-apiserver-85ddd76cdd-84sf9.log](https://github.com/DependencyTrack/dependency-track/files/12360827/dependency-track-apiserver-85ddd76cdd-84sf9.log)

**Comment by nscuro** [comment]
Maybe it's an issue with the embedded Jetty. I just remembered that Jetty logs are written to a file, but not to STDOUT per default.

Can you please inspect the log file at `/data/.dependency-track/server.log`?

**Comment by webmutation** [comment]
Here is the server log.

[dt-server.log](https://github.com/DependencyTrack/dependency-track/files/12360977/dt-server.log)

**Comment by webmutation** [comment]
I see some errors there not sure what they are related to...

```
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.http.HttpGenerator] EOF_CONTENT
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpConnection] generate: FLUSH for SendCallback@2198fe32[PROCESSING][i=HTTP/1.1{s=200,h=6,cl=393},cb=org.eclipse.jetty.server.HttpChannel$SendCallback@d51fb95] ([p=0,l=189,c=8192,r=189],[p=0,l=393,c=393,r=393],true)@COMPLETING
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.io.WriteFlusher] write: WriteFlusher@5bca4e42{IDLE}->null [DirectByteBuffer@1bd554fd[p=0,l=189,c=8192,r=189]={<<<HTTP/1.1 200 OK\r\nDate: We...Content-Length: 393\r\n\r\n>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00},DirectByteBufferR@7885c914[p=0,l=393,c=393,r=393]={<<<<!DOCTYPE html>\n<html>\n<h... </ul>\n</body>\n</html>\n>>>}]
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.io.WriteFlusher] update WriteFlusher@5bca4e42{WRITING}->null:IDLE-->WRITING
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.io.SocketChannelEndPoint] flushed 582 SocketChannelEndPoint@56641540[{l=/192.168.129.16:8080,r=/192.168.158.155:44410,OPEN,fill=-,flush=W,to=1/30000}{io=0/0,kio=0,kro=1}]->[HttpConnection@66c0ca5a[p=HttpParser{s=CONTENT,0 of -1},g=HttpGenerator@50c41f28{s=COMPLETING}]=>HttpChannelOverHttp@180c8c{s=HttpChannelState@516543ea{s=HANDLING rs=BLOCKING os=COMMITTED is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=HANDLING,uri=http://192.168.129.16:8080/index.html,age=2}]
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.io.WriteFlusher] Flushed=true written=582 remaining=0 WriteFlusher@5bca4e42{WRITING}->null
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.io.WriteFlusher] update WriteFlusher@5bca4e42{IDLE}->null:WRITING-->IDLE
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpConnection] generate: SHUTDOWN_OUT for SendCallback@2198fe32[PROCESSING][i=HTTP/1.1{s=200,h=6,cl=393},cb=org.eclipse.jetty.server.HttpChannel$SendCallback@d51fb95] ([p=189,l=189,c=8192,r=0],[p=393,l=393,c=393,r=0],true)@END
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpConnection] generate: DONE for SendCallback@2198fe32[PROCESSING][i=HTTP/1.1{s=200,h=6,cl=393},cb=org.eclipse.jetty.server.HttpChannel$SendCallback@d51fb95] ([p=189,l=189,c=8192,r=0],[p=393,l=393,c=393,r=0],true)@END
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpOutput] onWriteComplete(true,null) s=CLOSING,api=PENDING,sc=false,e=null->s=CLOSED,api=ASYNC,sc=false,e=null c=null cb=null w=false
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.io.AbstractEndPoint] shutdownOutput SocketChannelEndPoint@56641540[{l=/192.168.129.16:8080,r=/192.168.158.155:44410,OPEN,fill=-,flush=-,to=0/30000}{io=0/0,kio=0,kro=1}]->[HttpConnection@66c0ca5a[p=HttpParser{s=CONTENT,0 of -1},g=HttpGenerator@50c41f28{s=END}]=>HttpChannelOverHttp@180c8c{s=HttpChannelState@516543ea{s=HANDLING rs=BLOCKING os=COMPLETED is=IDLE awp=false se=false i=true al=0},r=1,c=false/true,a=HANDLING,uri=http://192.168.129.16:8080/index.html,age=2}]
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.session.SessionHandler] Leaving scope org.eclipse.jetty.server.session.SessionHandler1910438136==dftMaxIdleSec=60 dispatch=FORWARD, async=false, session=null, oldsession=null, oldsessionhandler=org.eclipse.jetty.server.session.SessionHandler1910438136==dftMaxIdleSec=60
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.session.SessionHandler] Leaving scope org.eclipse.jetty.server.session.SessionHandler1910438136==dftMaxIdleSec=60 dispatch=REQUEST, async=false, session=null, oldsession=null, oldsessionhandler=null
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.Server] handled=true async=false committed=true on HttpChannelOverHttp@180c8c{s=HttpChannelState@516543ea{s=HANDLING rs=BLOCKING os=COMPLETED is=IDLE awp=false se=false i=true al=0},r=1,c=false/true,a=HANDLING,uri=http://192.168.129.16:8080/,age=2}
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannelState] unhandle HttpChannelState@516543ea{s=HANDLING rs=BLOCKING os=COMPLETED is=IDLE awp=false se=false i=true al=0}
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannelState] nextAction(false) COMPLETE HttpChannelState@516543ea{s=HANDLING rs=COMPLETING os=COMPLETED is=IDLE awp=false se=false i=false al=0}
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannel] action COMPLETE HttpChannelOverHttp@180c8c{s=HttpChannelState@516543ea{s=HANDLING rs=COMPLETING os=COMPLETED is=IDLE awp=false se=false i=false al=0},r=1,c=false/true,a=HANDLING,uri=http://192.168.129.16:8080/,age=2}
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpOutput] complete(org.eclipse.jetty.util.Callback$3@37392816) s=CLOSED,api=ASYNC,sc=false,e=null s=true e=null, c=null
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannelState] completed HttpChannelState@516543ea{s=HANDLING rs=COMPLETING os=COMPLETED is=IDLE awp=false se=false i=false al=0}
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannelState] unhandle HttpChannelState@516543ea{s=HANDLING rs=COMPLETED os=COMPLETED is=IDLE awp=false se=false i=false al=0}
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannelState] nextAction(false) TERMINATED HttpChannelState@516543ea{s=IDLE rs=COMPLETED os=COMPLETED is=IDLE awp=false se=false i=false al=0}
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannel] action TERMINATED HttpChannelOverHttp@180c8c{s=HttpChannelState@516543ea{s=IDLE rs=COMPLETED os=COMPLETED is=IDLE awp=false se=false i=false al=0},r=1,c=true/true,a=IDLE,uri=http://192.168.129.16:8080/,age=2}
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannel] onCompleted for / written=393
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpInput] consumeAll HttpInput@341535447 cs=HttpChannelState@516543ea{s=IDLE rs=COMPLETED os=COMPLETED is=IDLE awp=false se=false i=false al=0} cp=org.eclipse.jetty.server.BlockingContentProducer@49fc68c6 eof=false
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpOutput] write(array HeapByteBuffer@c5eba32[p=0,l=315,c=8192,r=315]={<<<{"version":"4.4.2","times...ad82","name":"Alpine"}}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00})
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.AsyncContentProducer] consumeAll AsyncContentProducer@47d48e82[r=null,t=null,i=null,error=false,c=HttpChannelOverHttp@180c8c{s=HttpChannelState@516543ea{s=IDLE rs=COMPLETED os=COMPLETED is=IDLE awp=false se=false i=false al=0},r=1,c=true/true,a=IDLE,uri=http://192.168.129.16:8080/,age=2}]
java.io.IOException: Unconsumed content
	at org.eclipse.jetty.server.AsyncContentProducer.consumeAll(AsyncContentProducer.java:193)
	at org.eclipse.jetty.server.BlockingContentProducer.consumeAll(BlockingContentProducer.java:93)
	at org.eclipse.jetty.server.HttpInput.consumeAll(HttpInput.java:159)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:455)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:968)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:485)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpOutput] write(array) s=CLOSING,api=BLOCKED,sc=false,e=null last=true agg=false flush=true async=false, len=315 null
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannelOverHttp] failing all content with java.io.IOException: Unconsumed content HttpChannelOverHttp@180c8c{s=HttpChannelState@516543ea{s=IDLE rs=COMPLETED os=COMPLETED is=IDLE awp=false se=false i=false al=0},r=1,c=true/true,a=IDLE,uri=http://192.168.129.16:8080/,age=2}
2023-08-16 15:25:42,118 [] DEBUG [org.eclipse.jetty.server.HttpChannelOverHttp] produceContent has no content, parsing and filling
2023-08-16 15:25:42,117 [] DEBUG [org.eclipse.jetty.server.HttpChannel] sendResponse info=null content=HeapByteBuffer@676f96ac[p=0,l=315,c=8192,r=315]={<<<{"version":"4.4.2","times...ad82","name":"Alpine"}}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00} complete=true committing=true callback=Blocker@2ca936b1{null}
2023-08-16 15:25:42,118 [] DEBUG [org.eclipse.jetty.server.HttpChannel] COMMIT for /api/version on HttpChannelOverHttp@4a4afb41{s=HttpChannelState@7e420b70{s=HANDLING rs=BLOCKING os=COMMITTED is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=HANDLING,uri=http://192.168.129.16:8080/api/version,age=3}

```

**Comment by webmutation** [comment]
Any clue on what is going on... where I should look next, or if needed I can attach the full jetty log.

**Comment by webmutation** [comment]
So in the end I lost all information and had to create a new instance, I don't understand where this is coming from... I am not very concerned about the long term stability of DT.

**Comment by msymons** [comment]
@webmutation, it is hard to diagnose problems remotely in cases like this where there is nothing obvious in the log that would help.

I am sorry that you needed to create a new instance.  The important question now is....  did doing this solve your problem?

I would like to reassure you that we pay a lot of attention to ensuring that Dependency-Track is stable.  This is important as it is used in tens of thousands of organisations.

**Comment by webmutation** [comment]
Indeed I also cannot find any obvious errors except the ones on the logs that do not seem related to authentication. So this 500 error is uncertain where it is coming from.

creating a new instance solved the problem.

DT worked for over a year flawlessly until this problem... I also  tried to restore data from a backup but that did not work... I have added some additional monitoring to try and catch this type of problem earlier.

**Comment by msymons** [comment]
I am going to close this issue and we can re-open if it occurs again,
