### ISSUE TITLE
Transaction deadlock when processing concurrent BOM uploads using MSSQL

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/dependency-track#3133]
### Discussed in https://github.com/DependencyTrack/dependency-track/discussions/3132

<div type='discussions-op-text'>

<sup>Originally posted by **JoergBruenner** October 24, 2023</sup>
@nscuro 

```
2023-10-24 08:40:04,514 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: acf9ff38-b64e-423f-8480-05bc21f3dc2a

2023-10-24 08:40:04,779 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: 1bc528ce-ff16-4f5b-967a-ea19893e779c

2023-10-24 08:40:05,284 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: 0624be72-aa7d-41df-b393-3a193eddcf46

2023-10-24 08:40:05,883 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: 69accf2d-176e-48d9-8835-6c3264ac808c

2023-10-24 08:40:06,208 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: 0410b81b-2436-4c42-b238-2d05bb8d084a

2023-10-24 08:40:28,291 ERROR [Persistence] org.datanucleus.exceptions.NucleusDataStoreException: An error occurred during the current command (Done status 0). Transaction (Process ID 96) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

2023-10-24 08:40:28,293 ERROR [BomUploadProcessingTask] Error while processing bom

javax.jdo.JDODataStoreException: An error occurred during the current command (Done status 0). Transaction (Process ID 96) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

                at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:605)

                at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:157)

                at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:428)

                at org.dependencytrack.persistence.ComponentQueryManager.createComponent(ComponentQueryManager.java:306)

                at org.dependencytrack.persistence.QueryManager.createComponent(QueryManager.java:516)

                at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:206)

                at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:141)

                at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)

                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

                at java.base/java.lang.Thread.run(Unknown Source)

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: An error occurred during the current command (Done status 0). Transaction (Process ID 96) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

                at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer$FetchBufferTokenHandler.onDone(SQLServerResultSet.java:5403)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5501)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1801)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1059)

                at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)

                at org.datanucleus.store.rdbms.scostore.ListStoreIterator.next(ListStoreIterator.java:198)

                at org.datanucleus.store.rdbms.scostore.ListStoreIterator.<init>(ListStoreIterator.java:68)

                at org.datanucleus.store.rdbms.scostore.FKListStore.listIterator(FKListStore.java:1230)

                at org.datanucleus.store.rdbms.scostore.AbstractListStore.listIterator(AbstractListStore.java:82)

                at org.datanucleus.store.rdbms.scostore.AbstractListStore.iterator(AbstractListStore.java:76)

                at org.datanucleus.store.types.wrappers.backed.List.loadFromStore(List.java:281)

                at org.datanucleus.store.types.wrappers.backed.List.iterator(List.java:500)

                at org.datanucleus.store.types.containers.JDKCollectionAdapter.iterator(JDKCollectionAdapter.java:32)

                at org.datanucleus.store.fieldmanager.ReachabilityFieldManager.processContainer(ReachabilityFieldManager.java:116)

                at org.datanucleus.store.fieldmanager.ReachabilityFieldManager.storeObjectField(ReachabilityFieldManager.java:142)

                at org.datanucleus.state.StateManagerImpl.providedObjectField(StateManagerImpl.java:1915)

                at org.dependencytrack.model.Component.dnProvideField(Component.java)

                at org.dependencytrack.model.Component.dnProvideFields(Component.java)

                at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:2559)

                at org.datanucleus.ReachabilityAtCommitHandler.execute(ReachabilityAtCommitHandler.java:201)

                at org.datanucleus.ExecutionContextImpl.preCommit(ExecutionContextImpl.java:4080)

                at org.datanucleus.ExecutionContextImpl.transactionPreCommit(ExecutionContextImpl.java:740)

                at org.datanucleus.transaction.TransactionImpl.internalPreCommit(TransactionImpl.java:398)

                at org.datanucleus.transaction.TransactionImpl.commit(TransactionImpl.java:288)

                at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:94)

                ... 9 common frames omitted

2023-10-24 08:40:40,800 ERROR [Persistence] org.datanucleus.exceptions.NucleusDataStoreException: An error occurred during the current command (Done status 0). Transaction (Process ID 136) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

2023-10-24 08:40:40,802 ERROR [BomUploadProcessingTask] Error while processing bom

javax.jdo.JDODataStoreException: An error occurred during the current command (Done status 0). Transaction (Process ID 136) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

                at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:605)

                at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:157)

                at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:428)

                at org.dependencytrack.persistence.ComponentQueryManager.createComponent(ComponentQueryManager.java:306)

                at org.dependencytrack.persistence.QueryManager.createComponent(QueryManager.java:516)

                at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:206)

                at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:141)

                at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)

                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

                at java.base/java.lang.Thread.run(Unknown Source)

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: An error occurred during the current command (Done status 0). Transaction (Process ID 136) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

                at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer$FetchBufferTokenHandler.onDone(SQLServerResultSet.java:5403)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5501)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1801)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1059)

                at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)

                at org.datanucleus.store.rdbms.scostore.ListStoreIterator.next(ListStoreIterator.java:198)

                at org.datanucleus.store.rdbms.scostore.ListStoreIterator.<init>(ListStoreIterator.java:68)

                at org.datanucleus.store.rdbms.scostore.FKListStore.listIterator(FKListStore.java:1230)

                at org.datanucleus.store.rdbms.scostore.AbstractListStore.listIterator(AbstractListStore.java:82)

                at org.datanucleus.store.rdbms.scostore.AbstractListStore.iterator(AbstractListStore.java:76)

                at org.datanucleus.store.types.wrappers.backed.List.loadFromStore(List.java:281)

                at org.datanucleus.store.types.wrappers.backed.List.iterator(List.java:500)

                at org.datanucleus.store.types.containers.JDKCollectionAdapter.iterator(JDKCollectionAdapter.java:32)

                at org.datanucleus.store.fieldmanager.ReachabilityFieldManager.processContainer(ReachabilityFieldManager.java:116)

                at org.datanucleus.store.fieldmanager.ReachabilityFieldManager.storeObjectField(ReachabilityFieldManager.java:142)

                at org.datanucleus.state.StateManagerImpl.providedObjectField(StateManagerImpl.java:1915)

                at org.dependencytrack.model.Component.dnProvideField(Component.java)

                at org.dependencytrack.model.Component.dnProvideFields(Component.java)

                at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:2559)

                at org.datanucleus.ReachabilityAtCommitHandler.execute(ReachabilityAtCommitHandler.java:201)

                at org.datanucleus.ExecutionContextImpl.preCommit(ExecutionContextImpl.java:4080)

                at org.datanucleus.ExecutionContextImpl.transactionPreCommit(ExecutionContextImpl.java:740)

                at org.datanucleus.transaction.TransactionImpl.internalPreCommit(TransactionImpl.java:398)

                at org.datanucleus.transaction.TransactionImpl.commit(TransactionImpl.java:288)

                at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:94)

                ... 9 common frames omitted

2023-10-24 08:41:03,302 ERROR [Persistence] org.datanucleus.exceptions.NucleusDataStoreException: An error occurred during the current command (Done status 0). Transaction (Process ID 136) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

2023-10-24 08:41:03,304 ERROR [BomUploadProcessingTask] Error while processing bom

javax.jdo.JDODataStoreException: An error occurred during the current command (Done status 0). Transaction (Process ID 136) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

                at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:605)

                at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:157)

                at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:428)

                at org.dependencytrack.persistence.ComponentQueryManager.createComponent(ComponentQueryManager.java:306)

                at org.dependencytrack.persistence.QueryManager.createComponent(QueryManager.java:516)

                at org.dependencytrack.tasks.BomUploadProcessingTask.processComponent(BomUploadProcessingTask.java:206)

                at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:141)

                at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:101)

                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

                at java.base/java.lang.Thread.run(Unknown Source)

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: An error occurred during the current command (Done status 0). Transaction (Process ID 136) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

                at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:265)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer$FetchBufferTokenHandler.onDone(SQLServerResultSet.java:5403)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:99)

                at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:37)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:5501)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1801)

                at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1059)

                at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)

                at org.datanucleus.store.rdbms.scostore.ListStoreIterator.next(ListStoreIterator.java:198)

                at org.datanucleus.store.rdbms.scostore.ListStoreIterator.<init>(ListStoreIterator.java:68)

                at org.datanucleus.store.rdbms.scostore.FKListStore.listIterator(FKListStore.java:1230)

                at org.datanucleus.store.rdbms.scostore.AbstractListStore.listIterator(AbstractListStore.java:82)

                at org.datanucleus.store.rdbms.scostore.AbstractListStore.iterator(AbstractListStore.java:76)

                at org.datanucleus.store.types.wrappers.backed.List.loadFromStore(List.java:281)

                at org.datanucleus.store.types.wrappers.backed.List.iterator(List.java:500)

                at org.datanucleus.store.types.containers.JDKCollectionAdapter.iterator(JDKCollectionAdapter.java:32)

                at org.datanucleus.store.fieldmanager.ReachabilityFieldManager.processContainer(ReachabilityFieldManager.java:116)

                at org.datanucleus.store.fieldmanager.ReachabilityFieldManager.storeObjectField(ReachabilityFieldManager.java:142)

                at org.datanucleus.state.StateManagerImpl.providedObjectField(StateManagerImpl.java:1915)

                at org.dependencytrack.model.Component.dnProvideField(Component.java)

                at org.dependencytrack.model.Component.dnProvideFields(Component.java)

                at org.datanucleus.state.StateManagerImpl.provideFields(StateManagerImpl.java:2559)

                at org.datanucleus.ReachabilityAtCommitHandler.execute(ReachabilityAtCommitHandler.java:201)

                at org.datanucleus.ExecutionContextImpl.preCommit(ExecutionContextImpl.java:4080)

                at org.datanucleus.ExecutionContextImpl.transactionPreCommit(ExecutionContextImpl.java:740)

                at org.datanucleus.transaction.TransactionImpl.internalPreCommit(TransactionImpl.java:398)

                at org.datanucleus.transaction.TransactionImpl.commit(TransactionImpl.java:288)

                at org.datanucleus.api.jdo.JDOTransaction.commit(JDOTransaction.java:94)

                ... 9 common frames omitted

2023-10-24 08:41:43,235 INFO [BomUploadProcessingTask] Identified 348 new components
```</div>

**Comment by valentijnscholten** [comment]
Or maybe it can be solved by DROP SUPPORT FOR MSSQL? :-D

**Comment by nscuro** [comment]
> Not sure if it's the same scenario, but in the past I have had troubles with deadlocks in MSSQL when indexes were not being used in queries. This lead to transactions locking the whole table. With the correct index (or better WHERE clause), these problems were solved.

Ha, that's a good hint! It may be related to #3123 then, which caused indexes to be bypassed when processing components. So best case this should be reproducible with DT <= `4.9.0`, but not with `4.10.0-SNAPSHOT`.

> Or maybe it can be solved by DROP SUPPORT FOR MSSQL? :-D

Indeed the future of DT will be more elephant-centric :)

**Comment by nscuro** [comment]
So I am able to reproduce this with DT `4.9.0` and `4.10.0-SNAPSHOT`. https://github.com/DependencyTrack/dependency-track/pull/3123 did not fix this. Works fine with PostgreSQL, so what about MSSQL is different...

**Comment by valentijnscholten** [comment]
I vaguely remember enabling logging of deadlocks to help debug them: https://www.sqlshack.com/what-are-sql-server-deadlocks-and-how-to-monitor-them/

But some people just enable SNAPSHOT isolation and never look back.

**Comment by nscuro** [comment]
Thanks, I'll have a look at the debugging tools available. Maybe the root cause is something obvious that I'm just not seeing without those,

RE: SNAPSHOT isolation - Interesting, that looks like Postgres' MVCC behavior so might be worth recommending that in our docs. Surely there are downsides to this as otherwise it would be enabled by default.

**Comment by nscuro** [comment]
I was able to verify that setting the transaction isolation to `READ_COMMITTED_SNAPSHOT` indeed resolves the problem. 

@JoergBruenner, have your database admins execute the following statement on the Dependency-Track database:

```sql
ALTER DATABASE dtrack SET READ_COMMITTED_SNAPSHOT ON
```

Replace `dtrack` with your database's name of course.

I will add a recommendation for this in our documentation.

**Comment by nscuro** [comment]
Closing as changing the transaction isolation fixes the issue. If it keeps appearing, please raise a new issue.
