### ISSUE TITLE
Error in MailPublisher

### ISSUE THREAD

**Issue by rkg-mm** [DependencyTrack/dependency-track#3197]
### Current Behavior

While troubleshooting a missing mail issue I found one error several times each day in our logs. Its always first a BOM parsing error (I assume this is due to a malformed BOM since it only happens in 2 Project IDs). But this error is followed by another error which seems to be related with email sending and should not happen I think (see last error):

```
2023-11-08 16:03:19,391 [] ERROR [org.dependencytrack.tasks.BomUploadProcessingTask] Error while processing bom
org.cyclonedx.exception.ParseException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.cyclonedx.model.Bom["components"]->java.util.ArrayList[447]->org.cyclonedx.model.Component["licenses"]->org.cyclonedx.model.License["name"])
	at org.cyclonedx.parsers.XmlParser.parse(XmlParser.java:89)
	at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:106)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:107)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: org.cyclonedx.model.Bom["components"]->java.util.ArrayList[447]->org.cyclonedx.model.Component["licenses"]->org.cyclonedx.model.License["name"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromArray(StdDeserializer.java:222)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:46)
	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:122)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4801)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2974)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3438)
	at org.cyclonedx.util.deserializer.LicenseDeserializer.processLicenseNode(LicenseDeserializer.java:60)
	at org.cyclonedx.util.deserializer.LicenseDeserializer.deserialize(LicenseDeserializer.java:44)
	at org.cyclonedx.util.deserializer.LicenseDeserializer.deserialize(LicenseDeserializer.java:31)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:122)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:122)
	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:91)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3833)
	at org.cyclonedx.parsers.XmlParser.parse(XmlParser.java:87)
	... 5 common frames omitted


2023-11-08 16:03:20,919 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: Value in JsonObjects name/value pair cannot be null
	at org.glassfish.json.JsonObjectBuilderImpl.validateValue(JsonObjectBuilderImpl.java:222)
	at org.glassfish.json.JsonObjectBuilderImpl.add(JsonObjectBuilderImpl.java:90)
	at org.dependencytrack.util.NotificationUtil.toJson(NotificationUtil.java:455)
	at org.dependencytrack.notification.publisher.Publisher.prepareTemplate(Publisher.java:121)
	at org.dependencytrack.notification.publisher.SendMailPublisher.sendNotification(SendMailPublisher.java:80)
	at org.dependencytrack.notification.publisher.SendMailPublisher.inform(SendMailPublisher.java:65)
	at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:82)
	at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:117)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Steps to Reproduce

I don't know :( 

### Expected Behavior

No error in logs :) 

### Dependency-Track Version

4.9.1

### Dependency-Track Distribution

Container Image

### Database Server

Microsoft SQL Server

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Thanks for reporting, and thanks for providing the stack trace. I can see what the problem in the notification logic is and will fix it.

As for the original failure in BOM parsing, I suspect this is a bug in the CycloneDX library we're using. If it is an option, try changing the BOM format to JSON, it may work that way. 

Are you able to share the BOM that was uploaded? Perhaps send it to me in private via Slack if sharing publicly is not an option. If I am able to reproduce, I can submit a PR to the CDX library.
