### ISSUE TITLE
SPDX BOM Upload is not reflected

### ISSUE THREAD

**Issue by udaykor** [DependencyTrack/dependency-track#329]
Hello :)

### Current Behavior:
BOM upload is not shown as successful although UI notification comes up.

### Steps to Reproduce:
1. Clone a random maven project. (https://github.com/CSPF-Founder/JavaVulnerableLab) 
2. Generate SPDX BOM Using mavne spdx plugin (https://github.com/spdx/spdx-maven-plugin)
3. Upload the SPDX to Dependency Track, wait for the notification to show green (successful import) and blue (queued for processing).
4. After few mins if nothing happens, goto overview for the project and queue manually. 
5. Head back to projects to notice that BOM upload details are not published. (but why)

### Environment:
  
  - Dependency-Track Version:
  - Distribution: [ Docker | Executable WAR | Traditional WAR ]
  - BOM Format & Version:
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ]
  - Browser: 

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Best
Uday

**Comment by stevespringett** [comment]
Can you attach the SPDX BOM you're attempting to upload please?

**Comment by stevespringett** [comment]
I was able to reproduce the issue by generating an SPDX from the project

```bash
mvn org.spdx:spdx-maven-plugin:0.5.2:createSPDX
```
[JavaVulnerableLab Maven Webapp-0.0.1-SNAPSHOT.spdx.zip](https://github.com/DependencyTrack/dependency-track/files/3129751/JavaVulnerableLab.Maven.Webapp-0.0.1-SNAPSHOT.spdx.zip)

The resulting BOM generates the following stacktrace when uploaded to Dependency-Track:

```
[WARN] [line: 6, col: 89] {W124} Non-ascii characters in a namespace URI may not be completely portable: <http://spdx.org/spdxpackages/JavaVulnerableLab Maven Webapp-0.0.1-SNAPSHOT#>. Resulting RDF URI references are legal.
[ERROR] Bad character in IRI (space): <http://spdx.org/spdxpackages/JavaVulnerableLab[space]...>
[ERROR] Error while processing bom
org.apache.jena.riot.RiotException: Bad character in IRI (space): <http://spdx.org/spdxpackages/JavaVulnerableLab[space]...>
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:140)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.convert(ReaderRIOTRDFXML.java:256)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.convert(ReaderRIOTRDFXML.java:273)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML$HandlerSink.statement(ReaderRIOTRDFXML.java:225)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.triple(XMLHandler.java:72)
	at org.apache.jena.rdfxml.xmlinput.impl.ParserSupport.triple(ParserSupport.java:233)
	at org.apache.jena.rdfxml.xmlinput.states.WantDescription.startElement(WantDescription.java:92)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.startElement(XMLHandler.java:111)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.jena.rdfxml.xmlinput.impl.RDFXMLParser.parse(RDFXMLParser.java:101)
	at org.apache.jena.rdfxml.xmlinput.ARP.load(ARP.java:118)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML.parse(ReaderRIOTRDFXML.java:188)
	at org.apache.jena.riot.lang.ReaderRIOTRDFXML.read(ReaderRIOTRDFXML.java:86)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:352)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:342)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:291)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:500)
	at org.apache.jena.riot.RDFDataMgr.parseFromInputStream(RDFDataMgr.java:870)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:268)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:254)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:305)
	at org.spdx.rdfparser.SPDXDocumentFactory.createSpdxDocument(SPDXDocumentFactory.java:113)
	at org.dependencytrack.parser.spdx.rdf.SpdxDocumentParser.parse(SpdxDocumentParser.java:118)
	at org.dependencytrack.parser.spdx.rdf.SpdxDocumentParser.parse(SpdxDocumentParser.java:82)
	at org.dependencytrack.tasks.BomUploadProcessingTask.inform(BomUploadProcessingTask.java:74)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It appears the Maven plugin may be generating invalid SPDX files. For reference, Dependency-Track uses SPDX-Tools v2.1.16 to parse SPDX files. So I would recommend submitting a defect to either the SPDX Maven plugin or the SPDX Tools project and reference this ticket.

https://github.com/spdx/spdx-maven-plugin
https://github.com/spdx/tools

---
See also: https://docs.dependencytrack.org/best-practices/

Generating a CycloneDX BOM from the same project produces a valid BOM which can be successfully imported into Dependency-Track.

```bash
mvn org.cyclonedx:cyclonedx-maven-plugin:1.3.1:makeAggregateBom
```

**Comment by stevespringett** [comment]
@goneall This looks like a SPDX Maven plugin issue. Without knowing how it works, my best guess would be that the Maven plugin may not be URL encoding the project name. What are your thoughts?

**Comment by goneall** [comment]
@stevespringett Agree - I added https://github.com/spdx/spdx-maven-plugin/issues/13 to track the issue.
