### ISSUE TITLE
Null Exception on GitHub PURL

### ISSUE THREAD

**Issue by lnksz** [DependencyTrack/dependency-track#3299]
### Current Behavior

After updating to v4.10.0 I added PURLs  to the components which maintain their releases on GitHub.
E.g. cjson (`pkg:github/DaveGamble/cJSON` )

Watching the logs of the docker deployed apiserver, I can see that upon saving the component details, an internal analysis task is started, which hits a NullPointerException pretty quickly

The one strange thing that I noticed is: the purl is converted into lowercase! See the log below, and also if one opens the component details, the PURL is displayed lowercase. Maybe this is the culprit of an empty response and that causes a NullException because of a missing check? (Most probably not, otherwise it would succeed with the PURL which is all lowercase: `pkg:github/cesanta/mongoose`)

Note: I tried with both on and off for "Authentication Required" for the GitHub Repository Admin settings

```
dependency-track_apiserver  | 2023-12-13 14:29:11,387 INFO [InternalAnalysisTask] Starting internal analysis task
dependency-track_apiserver  | 2023-12-13 14:29:11,387 INFO [InternalAnalysisTask] Analyzing 1 component(s)
dependency-track_apiserver  | 2023-12-13 14:29:11,404 INFO [InternalAnalysisTask] Internal analysis complete
dependency-track_apiserver  | 2023-12-13 14:29:11,408 INFO [RepositoryMetaAnalyzerTask] Performing component repository metadata analysis against 1 components
dependency-track_apiserver  | 2023-12-13 14:29:11,412 WARN [CacheStampedeBlocker] An error occurred while populating cache repositoryMetaCache for key pkg:github/davegamble/cjson : java.lang.NullPointerException
dependency-track_apiserver  | org.dependencytrack.exception.MetaAnalyzerException: java.lang.NullPointerException
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.GithubMetaAnalyzer.analyze(GithubMetaAnalyzer.java:142)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.analyze(RepositoryMetaAnalyzerTask.java:177)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.lambda$analyze$0(RepositoryMetaAnalyzerTask.java:121)
dependency-track_apiserver  | 	at io.github.resilience4j.retry.Retry.lambda$decorateCallable$5(Retry.java:237)
dependency-track_apiserver  | 	at io.github.resilience4j.retry.Retry.executeCallable(Retry.java:373)
dependency-track_apiserver  | 	at org.dependencytrack.util.CacheStampedeBlocker.readThroughOrPopulateCache(CacheStampedeBlocker.java:201)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.analyze(RepositoryMetaAnalyzerTask.java:126)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.inform(RepositoryMetaAnalyzerTask.java:91)
dependency-track_apiserver  | 	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:110)
dependency-track_apiserver  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
dependency-track_apiserver  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
dependency-track_apiserver  | 	at java.base/java.lang.Thread.run(Unknown Source)
dependency-track_apiserver  | Caused by: java.lang.NullPointerException: null
dependency-track_apiserver  | 2023-12-13 14:29:11,413 INFO [RepositoryMetaAnalyzerTask] Completed component repository metadata analysis against 1 components
```

### Steps to Reproduce

1. Find package with releases on github (e.g. https://github.com/DaveGamble/cJSON)
2. Tail the logs of the api server `docker compose logs -f`
3. Create a component with the matching PURL ( `pkg:github/DaveGamble/cJSON`)
4. Save the component (details)

### Expected Behavior

The GitHub PURL is parsed, and the latest version is successfully queried and displayed in the project's component overview table

### Dependency-Track Version

4.10.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

15

### Browser

Mozilla Firefox

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
I think this is happening because the analyzer expects the version part of the PURL to be present, but in your PURL it is not.

**Comment by lnksz** [comment]
After a restart a maybe helpful hint could be seen in the exception

```
dependency-track_apiserver  | 2023-12-13 14:58:31,430 INFO [InternalAnalysisTask] Starting internal analysis task
dependency-track_apiserver  | 2023-12-13 14:58:31,430 INFO [InternalAnalysisTask] Analyzing 1 component(s)
dependency-track_apiserver  | 2023-12-13 14:58:31,455 INFO [InternalAnalysisTask] Internal analysis complete
dependency-track_apiserver  | 2023-12-13 14:58:31,478 INFO [RepositoryMetaAnalyzerTask] Performing component repository metadata analysis against 1 components
dependency-track_apiserver  | 2023-12-13 14:58:31,553 WARN [CacheStampedeBlocker] An error occurred while populating cache repositoryMetaCache for key pkg:github/davegamble/cjson : java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
dependency-track_apiserver  | org.dependencytrack.exception.MetaAnalyzerException: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.GithubMetaAnalyzer.analyze(GithubMetaAnalyzer.java:142)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.analyze(RepositoryMetaAnalyzerTask.java:177)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.lambda$analyze$0(RepositoryMetaAnalyzerTask.java:121)
dependency-track_apiserver  | 	at io.github.resilience4j.retry.Retry.lambda$decorateCallable$5(Retry.java:237)
dependency-track_apiserver  | 	at io.github.resilience4j.retry.Retry.executeCallable(Retry.java:373)
dependency-track_apiserver  | 	at org.dependencytrack.util.CacheStampedeBlocker.readThroughOrPopulateCache(CacheStampedeBlocker.java:201)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.analyze(RepositoryMetaAnalyzerTask.java:126)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.inform(RepositoryMetaAnalyzerTask.java:91)
dependency-track_apiserver  | 	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:110)
dependency-track_apiserver  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
dependency-track_apiserver  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
dependency-track_apiserver  | 	at java.base/java.lang.Thread.run(Unknown Source)
dependency-track_apiserver  | Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
dependency-track_apiserver  | 	at java.base/java.util.regex.Matcher.getTextLength(Unknown Source)
dependency-track_apiserver  | 	at java.base/java.util.regex.Matcher.reset(Unknown Source)
dependency-track_apiserver  | 	at java.base/java.util.regex.Matcher.<init>(Unknown Source)
dependency-track_apiserver  | 	at java.base/java.util.regex.Pattern.matcher(Unknown Source)
dependency-track_apiserver  | 	at org.dependencytrack.tasks.repositories.GithubMetaAnalyzer.analyze(GithubMetaAnalyzer.java:109)
dependency-track_apiserver  | 	... 11 common frames omitted
dependency-track_apiserver  | 2023-12-13 14:58:31,553 INFO [RepositoryMetaAnalyzerTask] Completed component repository metadata analysis against 1 components
```

the new part beeing:
```
dependency-track_apiserver  | 2023-12-13 14:58:31,553 WARN [CacheStampedeBlocker] An error occurred while populating cache repositoryMetaCache for key pkg:github/davegamble/cjson : java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
dependency-track_apiserver  | org.dependencytrack.exception.MetaAnalyzerException: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
```

**Comment by lnksz** [comment]
> I think this is happening because the analyzer expects the version part of the PURL to be present, but in your PURL it is not.

Thanks, will try out ASAP

**Comment by lnksz** [comment]
With the version added to the PURL, the analysis works as expected!

Thank you @nscuro for the extremely quick support!

May I ask, whether there is a possibility, that DT takes the version info from the required version field of the component? Or that one could reference it in the other fields (something like `...cjson/@${version}`?
Currently it is duplicated in both PURL and CPE.
![image](https://github.com/DependencyTrack/dependency-track/assets/15908859/3d5eb7fd-2d05-45ba-ad60-9a5ebcad7a1e)

Also https://docs.dependencytrack.org/datasources/routing/#package-url-purl lists `Version` as optional but here it is currently required. Is it always required? 

In https://docs.dependencytrack.org/datasources/repositories/#github are there any noteable differences for the user, given that only publicly available repos are referenced, whether he provides a PAT or not?

**Comment by jadyndev** [comment]
The current implementation decides, based on the version sting, whether the latest release or the latest commit in the default branch is shown as the latest version in DT. (https://github.com/DependencyTrack/dependency-track/pull/3112/files#diff-869bcadc3c81bb5e9fe742f406058583a7bc5a26e89c8878323ae538ea1f0159R106)

It would be possible to default to either latest commit or latest release in case no version is set.
I think it should default to the latest release, any opinions?
