### ISSUE TITLE
PSQLException: ERROR: cannot drop table "CWE" because other objects depend on it

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#3301]
### Current Behavior

On startup, 4.11.0-SNAPSHOT has the following in log:

```
2023-12-11 14:32:08,676 INFO [Config] --------------------------------------------------------------------------------
2023-12-11 14:32:08,677 INFO [Config] Application:  Dependency-Track
2023-12-11 14:32:08,677 INFO [Config] Version:      4.11.0-SNAPSHOT
2023-12-11 14:32:08,677 INFO [Config] Built-on:     2023-12-11T14:24:17Z
2023-12-11 14:32:08,677 INFO [Config] --------------------------------------------------------------------------------
2023-12-11 14:32:08,678 INFO [Config] Framework:    Alpine
2023-12-11 14:32:08,678 INFO [Config] Version :     2.2.4
2023-12-11 14:32:08,678 INFO [Config] Built-on:     2023-12-06T15:54:14Z
2023-12-11 14:32:08,678 INFO [Config] --------------------------------------------------------------------------------
2023-12-11 14:32:08,821 WARN [ExecutorServiceMetrics] Failed to bind as java.util.concurrent.Executors$AutoShutdownDelegatedExecutorService is unsupported.
2023-12-11 14:32:08,876 INFO [RequirementsVerifier] Initializing requirements verifier
2023-12-11 14:32:08,876 INFO [MetricsInitializer] Registering system metrics
2023-12-11 14:32:09,036 INFO [UpgradeInitializer] Initializing upgrade framework
2023-12-11 14:32:12,519 WARN [Schema] Retrieved ForeignKey from datastore for table="VULNERABILITY" referencing table CWE but not found internally. Is there some catalog/schema or quoting causing problems?
2023-12-11 14:32:12,934 INFO [UpgradeExecutor] Upgrade class org.dependencytrack.upgrade.v4110.v4110Updater about to run.
2023-12-11 14:32:12,935 INFO [v4110Updater] Dropping CWE table
2023-12-11 14:32:12,949 ERROR [UpgradeExecutor] Error in executing upgrade class: org.dependencytrack.upgrade.v4110.v4110Updater
org.postgresql.util.PSQLException: ERROR: cannot drop table "CWE" because other objects depend on it
  Detail: constraint VULNERABILITY_FK1 on table "VULNERABILITY" depends on table "CWE"
  Hint: Use DROP ... CASCADE to drop the dependent objects too.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:335)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:321)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:297)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:292)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
	at org.datanucleus.store.rdbms.datasource.dbcp2.DelegatingStatement.execute(DelegatingStatement.java:194)
	at org.dependencytrack.upgrade.v4110.v4110Updater.dropCweTable(v4110Updater.java:45)
	at org.dependencytrack.upgrade.v4110.v4110Updater.executeUpgrade(v4110Updater.java:39)
	at alpine.server.upgrade.UpgradeExecutor.executeUpgrades(UpgradeExecutor.java:88)
	at org.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(UpgradeInitializer.java:83)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1049)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:984)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:740)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:901)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:470)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
	at org.eclipse.jetty.server.Server.doStart(Server.java:415)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:100)
2023-12-11 14:32:12,949 ERROR [UpgradeInitializer] An error occurred performing upgrade processing. org.postgresql.util.PSQLException: ERROR: cannot drop table "CWE" because other objects depend on it  Detail: constraint VULNERABILITY_FK1 on table "VULNERABILITY" depends on table "CWE"  Hint: Use DROP ... CASCADE to drop the dependent objects too.
2023-12-11 14:32:12,957 INFO [PersistenceManagerFactory] Initializing persistence framework
```

### Steps to Reproduce

1. Deploy 4.11.0-SNAPSHOT
2. Examine API log

### Expected Behavior

No database exception on startup

### Dependency-Track Version

4.11.0-SNAPSHOT

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

14.4

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
@msymons This will be fixed in #3304. It does not affect 4.10.x, because the change that added the CWE table removal was only introduced for 4.11.0-SNAPSHOT (#3284).

FTR, when in doubt this can be fixed manually using this SQL script:

```sql
BEGIN;
ALTER TABLE "VULNERABILITY" DROP CONSTRAINT IF EXISTS "VULNERABILITY_FK1";
DROP INDEX IF EXISTS "VULNERABILITY"."VULNERABILITY_CWE_IDX";
ALTER TABLE "VULNERABILITY" DROP COLUMN IF EXISTS "CWE";
DROP TABLE IF EXISTS "CWE";
COMMIT;
```
