### ISSUE TITLE
[UI]  Vulnerability Analysis is not done 

### ISSUE THREAD

**Issue by mwilfried** [DependencyTrack/dependency-track#3363]
### Current Behavior

Hi 

I have issue regarding Vulnerability Scanning on my Dependency Track Server. After pushing the Sbom, the Vulnerabilities seems to not be done and vulnerabilities are not shown.  

I tried to restart the analyse through we UI.
![image](https://github.com/DependencyTrack/dependency-track/assets/32105900/e67ed1f0-db78-4f3d-aca9-30357bd815da)

I see something is happening succesfully in lhe logs but no vulnerabities are  shown is UI
![image](https://github.com/DependencyTrack/dependency-track/assets/32105900/cb621df6-c909-4d4b-95c9-ec2650f4fa77)
![image](https://github.com/DependencyTrack/dependency-track/assets/32105900/6e814ba2-b194-4003-bb5e-5e52b84adb4c)

2024-01-09 12:55:19,327 [] DEBUG [org.dependencytrack.common.HttpClientPool] Stats: [leased: 0; pending: 0; available: 0; max: 200]
2024-01-09 12:55:24,327 [] DEBUG [org.dependencytrack.common.HttpClientPool] Stats: [leased: 0; pending: 0; available: 0; max: 200]
2024-01-09 12:55:29,328 [] DEBUG [org.dependencytrack.common.HttpClientPool] Stats: [leased: 0; pending: 0; available: 0; max: 200]
2024-01-09 12:55:32,362 [] DEBUG [alpine.event.framework.EventService] Dispatching event: class org.dependencytrack.event.ProjectMetricsUpdateEvent
2024-01-09 12:55:32,362 [] DEBUG [alpine.event.framework.EventService] Alerting subscriber org.dependencytrack.tasks.metrics.ProjectMetricsUpdateTask
2024-01-09 12:55:32,362 [] INFO [org.dependencytrack.tasks.metrics.ProjectMetricsUpdateTask] Executing metrics update for project 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 12:55:32,362 [] DEBUG [org.dependencytrack.tasks.metrics.ProjectMetricsUpdateTask] Fetching first components page for project 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 12:55:32,364 [] DEBUG [org.dependencytrack.tasks.metrics.ComponentMetricsUpdateTask] Executing metrics update for component 5240018d-b0fe-4d78-812c-8baabf2dae7c
2024-01-09 12:55:32,366 [] DEBUG [org.dependencytrack.tasks.metrics.ComponentMetricsUpdateTask] Metrics of component 5240018d-b0fe-4d78-812c-8baabf2dae7c did not change
....
..
2024-01-09 12:55:32,477 [] DEBUG [alpine.event.framework.EventService] Calling onSuccess

**When I download the sbom and i re-upload it I get the same behaviour** 
2024-01-09 13:01:04,339 [] INFO [org.dependencytrack.tasks.BomUploadProcessingTask] Identified 0 new components
2024-01-09 13:01:04,339 [] INFO [org.dependencytrack.tasks.BomUploadProcessingTask] Processing CycloneDX dependency graph for project: 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 13:01:04,339 [] DEBUG [org.dependencytrack.tasks.BomUploadProcessingTask] Reconciling components for project 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 13:01:04,339 [] DEBUG [org.dependencytrack.tasks.BomUploadProcessingTask] Reconciling services for project 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 13:01:04,340 [] DEBUG [org.dependencytrack.tasks.BomUploadProcessingTask] Updating last import date for project 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 13:01:04,345 [] DEBUG [alpine.event.framework.EventService] Dispatching event: class org.dependencytrack.event.VulnerabilityAnalysisEvent
2024-01-09 13:01:04,345 [] DEBUG [alpine.event.framework.EventService] Alerting subscriber org.dependencytrack.tasks.VulnerabilityAnalysisTask
2024-01-09 13:01:04,345 [] DEBUG [alpine.event.framework.EventService] Dispatching event: class org.dependencytrack.event.RepositoryMetaEvent
2024-01-09 13:01:04,345 [] DEBUG [alpine.event.framework.EventService] Alerting subscriber org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask
2024-01-09 13:01:04,346 [] INFO [org.dependencytrack.tasks.BomUploadProcessingTask] Processed 118 components and 0 services uploaded to project 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 13:01:04,346 [] DEBUG [alpine.notification.NotificationService] Dispatching notification: class alpine.notification.Notification
2024-01-09 13:01:04,346 [] DEBUG [alpine.notification.NotificationService] Alerting subscriber org.dependencytrack.notification.NotificationRouter
2024-01-09 13:01:04,346 [] DEBUG [alpine.event.framework.EventService] Dispatching event: class org.dependencytrack.event.IndexEvent
2024-01-09 13:01:04,346 [] DEBUG [alpine.event.framework.EventService] Alerting subscriber org.dependencytrack.tasks.IndexTask
2024-01-09 13:01:04,346 [] DEBUG [alpine.event.framework.EventService] Dispatching event: class org.dependencytrack.event.IndexEvent
2024-01-09 13:01:04,346 [] DEBUG [alpine.event.framework.EventService] Alerting subscriber org.dependencytrack.tasks.IndexTask
2024-01-09 13:01:04,346 [] DEBUG [alpine.event.framework.EventService] Calling onSuccess
2024-01-09 13:01:04,346 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component repository metadata
2024-01-09 13:01:04,347 [] INFO [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Performing component repository metadata analysis against 118 components
2024-01-09 13:01:04,347 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component: bda597a0-899f-4f2d-92d5-0b8a990ec82b
2024-01-09 13:01:04,347 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component: 192cc870-cc3c-4979-8be0-b6b33fc78ac2
2024-01-09 13:01:04,348 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component: 45341271-3da6-40d3-933a-d1531223cc3c
2024-01-09 13:01:04,348 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component: ad1b8e2a-4904-431a-9769-c59233750d6c
2024-01-09 13:01:04,348 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component: ....
2024-01-09 13:01:04,377 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component: ae8c1d91-0f86-4a51-b4b3-2e8277252de4
2024-01-09 13:01:04,377 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component: 43ae3a48-be3a-4f4e-8cf6-5a7f7d3062b6
2024-01-09 13:01:04,377 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Analyzing component: 5240018d-b0fe-4d78-812c-8baabf2dae7c
2024-01-09 13:01:04,377 [] INFO [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Completed component repository metadata analysis against 118 components
2024-01-09 13:01:04,378 [] DEBUG [org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask] Component repository metadata analysis complete
2024-01-09 13:01:04,388 [] INFO [org.dependencytrack.tasks.scanners.InternalAnalysisTask] Starting internal analysis task
2024-01-09 13:01:04,388 [] INFO [org.dependencytrack.tasks.scanners.InternalAnalysisTask] Analyzing 118 component(s)
2024-01-09 13:01:04,396 [] DEBUG [alpine.event.framework.EventService] Calling onSuccess
2024-01-09 13:01:04,396 [] DEBUG [alpine.event.framework.EventService] Calling onSuccess
2024-01-09 13:01:04,503 [] INFO [org.dependencytrack.tasks.scanners.InternalAnalysisTask] Internal analysis complete
2024-01-09 13:01:04,503 [] DEBUG [org.dependencytrack.tasks.VulnerabilityAnalysisTask] Time taken by perform analysis task by INTERNAL_ANALYZER : 115 milliseconds
2024-01-09 13:01:04,505 [] INFO [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
2024-01-09 13:01:04,505 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/accessibility-developer-tools@2.12.0
2024-01-09 13:01:04,506 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is not current. Analysis should be performed (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/ace-builds@1.13.1
2024-01-09 13:01:04,506 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/ag-grid@18.0.1
2024-01-09 13:01:04,507 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/ag-grid-polymer@18.0.0
2024-01-09 13:01:04,507 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/app-localize-behavior@2.0.1
2024-01-09 13:01:04,508 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/app-route@2.1.0
2024-01-09 13:01:04,508 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/async@1.5.2
2024-01-09 13:01:04,508 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/chai@3.5.0
2024-01-09 13:01:04,509 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/color-input@2.1.7
2024-01-09 13:01:04,510 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/color-picker@2.0.11
....
2024-01-09 13:01:04,559 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is not current. Analysis should be performed (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/web-component-tester@6.5.1
2024-01-09 13:01:04,559 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/webcomponentsjs@1.3.3
2024-01-09 13:01:04,560 [] DEBUG [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Cache is current. Skipping analysis. (source: OSSINDEX / targetHost: https://ossindex.sonatype.org/api/v3/component-report / target: pkg:bower/websocket-component@2.1.2
2024-01-09 13:01:09,106 [] DEBUG [org.dependencytrack.parser.ossindex.OssIndexParser] Parsing JSON response
2024-01-09 13:01:09,113 [] INFO [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Analyzing 7 component(s)
2024-01-09 13:01:09,113 [] INFO [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Sonatype OSS Index analysis complete
2024-01-09 13:01:09,113 [] DEBUG [org.dependencytrack.tasks.VulnerabilityAnalysisTask] Time taken by perform analysis task by OSSINDEX_ANALYZER : 4609 milliseconds
2024-01-09 13:01:09,114 [] INFO [org.dependencytrack.policy.PolicyEngine] Evaluating 118 component(s) against applicable policies
2024-01-09 13:01:09,253 [] INFO [org.dependencytrack.policy.PolicyEngine] Policy analysis complete
2024-01-09 13:01:09,253 [] DEBUG [alpine.event.framework.EventService] Dispatching event: class org.dependencytrack.event.ProjectMetricsUpdateEvent
2024-01-09 13:01:09,253 [] DEBUG [alpine.event.framework.EventService] Alerting subscriber org.dependencytrack.tasks.metrics.ProjectMetricsUpdateTask
2024-01-09 13:01:09,253 [] DEBUG [alpine.event.framework.EventService] Calling onSuccess
2024-01-09 13:01:09,253 [] INFO [org.dependencytrack.tasks.metrics.ProjectMetricsUpdateTask] Executing metrics update for project 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 13:01:09,253 [] DEBUG [org.dependencytrack.tasks.metrics.ProjectMetricsUpdateTask] Fetching first components page for project 234b9c84-e38b-4d50-8e31-330e7127d249
2024-01-09 13:01:09,254 [] DEBUG [org.dependencytrack.tasks.metrics.ComponentMetricsUpdateTask] Executing metrics update for component 5240018d-b0fe-4d78-812c-8baabf2dae7c
2024-01-09 13:01:09,256 [] DEBUG [org.dependencytrack.tasks.metrics.ComponentMetricsUpdateTask] Metrics of component 5240018d-b0fe-4d78-812c-8baabf2dae7c did not change
2024-01-09 13:01:09,256 [] DEBUG [org.dependencytrack.tasks.metrics.ComponentMetricsUpdateTask] Completed metrics update for component 5240018d-b0fe-4d78-812c-8baabf2dae7c in 00:00:001
...
2024-01-09 13:01:09,356 [] DEBUG [org.dependencytrack.tasks.metrics.ProjectMetricsUpdateTask] Metrics of project 234b9c84-e38b-4d50-8e31-330e7127d249 did not change
2024-01-09 13:01:09,356 [] DEBUG [org.dependencytrack.tasks.metrics.ProjectMetricsUpdateTask] Completed metrics update for project 234b9c84-e38b-4d50-8e31-330e7127d249 in 00:00:103
2024-01-09 13:01:09,356 [] DEBUG [alpine.event.framework.EventService] Calling onSuccess

**Is this behaviour related to HttpClientPool max reached ? how to increase it or flush it  ?**

2024-01-09 13:01:09,373 [] DEBUG [org.dependencytrack.common.HttpClientPool] Stats: [leased: 0; pending: 0; available: 1; max: 200]
2024-01-09 13:01:14,374 [] DEBUG [org.dependencytrack.common.HttpClientPool] Stats: [leased: 0; pending: 0; available: 1; max: 200]
2024-01-09 13:01:17,948 [] DEBUG [alpine.server.servlets.HealthServlet] Calling health check: alpine.server.health.checks.DatabaseHealthCheck
2024-01-09 13:01:17,948 [] DEBUG [alpine.server.health.checks.DatabaseHealthCheck] Checking non-transactional connection pool
2024-01-09 13:01:17,948 [] DEBUG [alpine.server.health.checks.DatabaseHealthCheck] Checking transactional connection pool

**I've also noticed some errors in server.log  like :** 
37937[p=HttpParser{s=CLOSED,0 of -1},g=HttpGenerator@43c5faa3{s=START}]=>HttpChannelOverHttp@6b8b9f56{s=HttpChannelState@2db6ad18{s=IDLE rs=BLOCKING os=OPEN is=IDLE awp=false se=false i=true al=0},r=1,c=false/false,a=IDLE,uri=null,age=0}]
java.nio.channels.CancelledKeyException: null
	at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(Unknown Source)
	at java.base/sun.nio.ch.SelectionKeyImpl.interestOps(Unknown Source)
	at org.eclipse.jetty.io.SelectableChannelEndPoint.updateKey(SelectableChannelEndPoint.java:271)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.updateKeys(ManagedSelector.java:713)
	at org.eclipse.jetty.io.ManagedSelector$SelectorProducer.produce(ManagedSelector.java:539)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:450)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:243)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Unknown Source)

### Steps to Reproduce

1. sbom generation using CycloneDX
2. upload of the sbom

### Expected Behavior

Analysis is done and vulnerabilities are shown

### Dependency-Track Version

4.8.x

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by matclab** [comment]
Similar problem here.
I notice that clicking on the "restart the analysis button" leads to lot of logs line like:
```
[ComponentMetricsUpdateTask] Metrics of component 7fac3ba9-5fdc-4bcb-a404-d23de5fbf1eb did not change
```

**Comment by matclab** [comment]
Also while importing SBOM, I see debug message like: 

```
dtrack-apiserver-1  | 2024-02-05 13:52:52,350 DEBUG [RepositoryMetaAnalyzerTask] RepositoryMetaComponent has not been checked since 43200000 ms. Analysis should be performed (source: PYPI / Namespace: null / Name: setuptools)
dtrack-apiserver-1  | 2024-02-05 13:52:52,351 DEBUG [CacheStampedeBlocker] Trying to read through/populate cache repositoryMetaCache for key pkg:pypi/setuptools@40.6.2
dtrack-apiserver-1  | 2024-02-05 13:52:52,351 DEBUG [CacheStampedeBlocker] Acquiring readLock for cache repositoryMetaCache and key pkg:pypi/setuptools@40.6.2
dtrack-apiserver-1  | 2024-02-05 13:52:52,351 DEBUG [CacheStampedeBlocker] ReadLock acquired for cache repositoryMetaCache and key pkg:pypi/setuptools@40.6.2
dtrack-apiserver-1  | 2024-02-05 13:52:52,351 DEBUG [CacheStampedeBlocker] No ongoing population for cache repositoryMetaCache and key pkg:pypi/setuptools@40.6.2 or entry has expired ! Trying to acquire writeLock
dtrack-apiserver-1  | 2024-02-05 13:52:52,352 DEBUG [CacheStampedeBlocker] WriteLock acquired for cache repositoryMetaCache and key pkg:pypi/setuptools@40.6.2
dtrack-apiserver-1  | 2024-02-05 13:52:52,352 DEBUG [CacheStampedeBlocker] Populating cache repositoryMetaCache for key pkg:pypi/setuptools@40.6.2 and returning value
dtrack-apiserver-1  | 2024-02-05 13:52:52,357 DEBUG [RepositoryMetaAnalyzerTask] Skipping analysis of component: ba6d9e56-6c60-454c-918b-a66e815f61eb using repository: pypi.org (PYPI)
dtrack-apiserver-1  | 2024-02-05 13:52:52,358 DEBUG [RepositoryMetaAnalyzerTask] Analyzing component: f12bb9b4-af64-417b-9370-d4912303510f
```
Wondering if it says there is a problem with Python repository ?

**Comment by spon94** [comment]
Hi, I encountered the same problem, is there any solution?

**Comment by matclab** [comment]
It looks like the component not analysed were marked as private.
Making them not private allow the analysis to run again.
