### ISSUE TITLE
Failed to decrypt API key (NVD - NistApiMirrorTask)

### ISSUE THREAD

**Issue by nluzgin** [DependencyTrack/dependency-track#3397]
### Current Behavior

On a new installation of the application, errors are observed when interacting with the API
`2024-01-19 15:27:16,519 WARN [NistApiMirrorTask] Failed to decrypt API key; Continuing without authentication
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
        at java.base/com.sun.crypto.provider.CipherCore.unpad(Unknown Source)
        at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(Unknown Source)
        at java.base/com.sun.crypto.provider.CipherCore.doFinal(Unknown Source)
        at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(Unknown Source)
        at java.base/javax.crypto.Cipher.doFinal(Unknown Source)
        at alpine.security.crypto.DataEncryption.decryptAsBytes(DataEncryption.java:136)
        at alpine.security.crypto.DataEncryption.decryptAsBytes(DataEncryption.java:148)
        at alpine.security.crypto.DataEncryption.decryptAsString(DataEncryption.java:176)
        at org.dependencytrack.tasks.NistApiMirrorTask.lambda$inform$1(NistApiMirrorTask.java:129)
        at java.base/java.util.Optional.map(Unknown Source)
        at org.dependencytrack.tasks.NistApiMirrorTask.inform(NistApiMirrorTask.java:127)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:110)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2024-01-19 15:27:16,521 WARN [NistApiMirrorTask] No API key configured; Aggressive rate limiting to be expected`

I tried to request the token again, but facing the same error.
Key looks like c9xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx4a78
Double checked for whitespace and etc.

### Steps to Reproduce

1. Create an API Token at https://nvd.nist.gov/developers/request-an-api-key
2. Enter the API token in Vulnerability Sources -> National Vulnerability Database -> API key
3. Restart Dependency Track
4. Face "Failed to decrypt API key" error in log

### Expected Behavior

API key used for communicate with NVD

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

postgres:14.10-alpine3.18

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Closing as duplicate of #2366 since the underlying issue is the same.

See also https://github.com/DependencyTrack/dependency-track/issues/2366#issuecomment-2113040946 for the current state on this issue.
