### ISSUE TITLE
VulnDB parser fails to import vulnerability files from 'vulndb-data-mirror'

### ISSUE THREAD

**Issue by lukas-braune** [DependencyTrack/dependency-track#3436]
### Current Behavior

When Dependency-Track's VulnDB parser attempts to parse output from the [vulndb-data-mirror](https://github.com/stevespringett/vulndb-data-mirror) project, it encounters the following error:

```
2024-02-01 10:18:41,393 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
org.json.JSONException: JSONArray[-1] not found.
at org.json.JSONArray.get(JSONArray.java:244)
at org.json.JSONArray.getJSONObject(JSONArray.java:457)
at org.dependencytrack.parser.vulndb.VulnDbParser.parseVulnerabilities(VulnDbParser.java:316)
at org.dependencytrack.parser.vulndb.VulnDbParser.parse(VulnDbParser.java:93)
at org.dependencytrack.parser.vulndb.VulnDbParser.parse(VulnDbParser.java:121)
at org.dependencytrack.tasks.VulnDbSyncTask.inform(VulnDbSyncTask.java:87)
at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:110)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
```

Moreover, no vulnerability records could be imported.

### Steps to Reproduce

1. Perform a full mirror of VulnDB's contents with the [vulndb-data-mirror](https://github.com/stevespringett/vulndb-data-mirror) (vulndb-data-mirror-1.0.2-SNAPSHOT)
2. Let Dependency-Track's VulnDB parser consume the resulting vulnerability files of step (1), e.g. `vulnerabilities_xxx.json`

### Expected Behavior

All vulnerability files (`vulnerabilities_xxx.json`) should be parsed and ingested into Dependency-Track as described in the [documentation](https://docs.dependencytrack.org/datasources/vulndb/#using-the-internal-analyzer).

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

15.5

### Browser

N/A

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
Currently blocked because VulnDB documentation is behind a paywall. We're working with the VulnDB team to regain access.
