### ISSUE TITLE
Upload SBOM via API Not working

### ISSUE THREAD

**Issue by visagansanthanam-unisys** [DependencyTrack/dependency-track#3443]
### Current Behavior

While running the API call to submit an SBOM file (XML/JSON) into a project fails with the following error
```
2024-02-06 14:21:07,168 ERROR [GlobalExceptionHandler] Uncaught internal server error
javax.jdo.JDODataStoreException: Insert of object "[org.dependencytrack.model.Project@2dfdfdbf](mailto:org.dependencytrack.model.Project@2dfdfdbf)" using statement "INSERT INTO "PROJECT" ("ACTIVE","AUTHOR","CLASSIFIER","CPE","DESCRIPTION","DIRECT_DEPENDENCIES","EXTERNAL_REFERENCES","GROUP","LAST_BOM_IMPORTED","LAST_BOM_IMPORTED_FORMAT","LAST_RISKSCORE","MANUFACTURER","NAME","PARENT_PROJECT_ID","PUBLISHER","PURL","SUPPLIER","SWIDTAGID","UUID","VERSION") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)" failed : ERROR: null value in column "NAME" violates not-null constraint
  Detail: Failing row contains (170, t, null, null, null, null, null, null, null, null, null, null, 55, null, null, null, f335a2b6-cbb7-4864-867a-b51d1f54f406, 1.1.3, null, null, null).
      at org.datanucleus.api.jdo.JDOAdapter.getJDOExceptionForNucleusException(JDOAdapter.java:605)
      at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:702)
      at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:722)
      at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:427)
      at org.dependencytrack.persistence.ProjectQueryManager.createProject(ProjectQueryManager.java:472)
      at org.dependencytrack.persistence.QueryManager.createProject(QueryManager.java:427)
      at org.dependencytrack.resources.v1.BomResource.uploadBom(BomResource.java:311)
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
      at java.base/java.lang.reflect.Method.invoke(Unknown Source)
      at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
      at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
      at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
      at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
      at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
      at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
      at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
      at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
      at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
      at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
      at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
      at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
      at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
      at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
      at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
      at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
      at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
      at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
      at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
      at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
      at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
      at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
      at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419)
      at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
      at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
      at alpine.server.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:225)
      at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
      at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
      at alpine.server.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:93)
      at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
      at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
      at alpine.server.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:166)
      at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
      at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
      at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
      at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598)
      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
      at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
      at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
      at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
      at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
      at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
      at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
      at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
      at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
      at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
      at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
      at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
      at org.eclipse.jetty.server.Server.handle(Server.java:563)
      at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
      at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
      at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
      at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
      at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
      at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
      at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
      at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
      at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
      at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
      at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
      at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
      at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
      at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
      at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "NAME" violates not-null constraint
  Detail: Failing row contains (170, t, null, null, null, null, null, null, null, null, null, null, 55, null, null, null, f335a2b6-cbb7-4864-867a-b51d1f54f406, 1.1.3, null, null, null).
```

### Steps to Reproduce

1.Run the following API call to submit a SBOM
```
curl -X "POST" 'https://depcheck-1.com/api/v1/bom' \
        -H 'X-API-Key: xxxx' \
        -H 'Content-Type: multipart/form-data' \
        -F 'projectame=APITest' \
        -F 'projectVersion=1.1.3' \
        -F 'parentName=APITest' \
        -F 'autoCreate=true' \
        -F "[bom=@bom1.xml]"

```
SBOM File attached
[bom1.zip](https://github.com/DependencyTrack/dependency-track/files/14178659/bom1.zip)

### Expected Behavior

SBOM Should be successfully uploaded to the project

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
The BOM contains a `component` where the `name` is either empty, or not present at all. [Component names are a mandatory field](https://cyclonedx.org/docs/1.5/json/#components_items_name) according to the specification, so the BOM is not valid.

Once https://github.com/DependencyTrack/dependency-track/issues/3218 is implemented, BOMs such as this one will be rejected immediately upon upload.

**Comment by visagansanthanam-unisys** [comment]
@nscuro But i can upload the same SBOM file into DTrack via the webUI without any issues.
![image](https://github.com/DependencyTrack/dependency-track/assets/100369838/7e812bd1-f52b-4368-85a4-ed9f02e7adca)

**Comment by dirsigler** [comment]
Running into the same issue.

Using the latest dependency-track version via Helm (`v4.13.2`).

Uploading with cURL using the REST API fails, no matter if I use POST, PUT or any other possible way that the Swagger docs provide me.
Uploading via the WebUI is successfull.

My SBOMs are created via Syft and Trivy:
```
trivy image --format cyclonedx --output "${SBOM_BASENAME}.trivy.cdx.json" "${IMAGE_URL}"

syft scan "docker:${IMAGE_URL}" --output cyclonedx-json="${SBOM_BASENAME}.syft.cdx.json"
```

Using the [cyclonedx-cli ](https://github.com/CycloneDX/cyclonedx-cli?tab=readme-ov-file#validate-command) I validated both my SBOMs successfully for their spec.

**Comment by nscuro** [comment]
@dirsigler 

> Uploading via the WebUI is successfull.

Since the frontend merely calls the REST API, that means likely your cURL command has a problem. Can you share the command, and the error you're receiving?

**Comment by dirsigler** [comment]
Hey @nscuro ,

thanks for reaching out. You are right, the cURL command was wrong, even tho I was pretty sure it was right.
