### ISSUE TITLE
Uploading a scan from Jenkins via dependency-track-plugin fails an INSERT

### ISSUE THREAD

**Issue by jonbrohauge** [DependencyTrack/dependency-track#345]
### Current Behavior:
Insert Failed

### Expected Behavior:
Insert OK

### Environment:
  
  - Dependency-Track Version: 3.4.1
  - Distribution: Docker
  - BOM Format & Version: N/A - Uploading a scan created by Dependency-Scan maven plugin
  - Database Server: PostgreSQL
  - Browser: N/A

### Additional Details:

Running a Pipeline job with the following stage:
```groovy
{
...
dependencyTrackPublisher projectName: "${pom.artifactId}", projectVersion: "${pom.version}", artifact: "target/site/dependency-check-report.xml", artifactType: 'scanResult', synchronous: false
...
}
```
The Dependency-Scan maven plugin is set like this:
```
  <build>
        <plugins>
.....
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.7.1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <version>3.0.0</version>
            </plugin>
        </plugins>
  </build>
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>5.0.0-M3</version>
                <configuration>
                    <failOnError>false</failOnError>
                    <format>ALL</format>     
                </configuration>
                <reportSets>
                    <reportSet>
                        <reports>
                            <report>aggregate</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
</reporting>
```

Dependency-Track log shows the following exception:
```
12:19:31.187 WARN [Persist] Insert of object "org.dependencytrack.model.Scan@3bdee940" using statement "INSERT INTO "SCAN" ("EXECUTED","IMPORTED","PROJECT_ID","UUID") VALUES (?,?,?,?)" failed : ERROR: null value in column "EXECUTED" violates not-null constraint
  Detail: Failing row contains (5, null, 2019-05-23 12:19:31.182+00, 2, dc8032dd-90f2-4df1-a7dc-3c1437a9ecb2).
12:19:31.190 ERROR [ScanUploadProcessingTask] Error while processing scan result
javax.jdo.JDODataStoreException: Insert of object "org.dependencytrack.model.Scan@3bdee940" using statement "INSERT INTO "SCAN" ("EXECUTED","IMPORTED","PROJECT_ID","UUID") VALUES (?,?,?,?)" failed : ERROR: null value in column "EXECUTED" violates not-null constraint
  Detail: Failing row contains (5, null, 2019-05-23 12:19:31.182+00, 2, dc8032dd-90f2-4df1-a7dc-3c1437a9ecb2).
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:542)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:717)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)
	at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:393)
	at org.dependencytrack.persistence.QueryManager.createScan(QueryManager.java:518)
	at org.dependencytrack.tasks.ScanUploadProcessingTask.inform(ScanUploadProcessingTask.java:80)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "EXECUTED" violates not-null constraint
  Detail: Failing row contains (5, null, 2019-05-23 12:19:31.182+00, 2, dc8032dd-90f2-4df1-a7dc-3c1437a9ecb2).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:427)
	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:417)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4551)
	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4528)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2025)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1868)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1723)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
	... 8 common frames omitted
12:19:31.191 WARN [General] ExecutionContext closed with active transaction, so rolling back the active transaction

```

**Comment by jonbrohauge** [comment]
Executing a similar step using BOM instead, works:
```groovy
sh('mvn org.cyclonedx:cyclonedx-maven-plugin:makeBom')
dependencyTrackPublisher projectName: "${pom.artifactId}", projectVersion: "${pom.version}", artifact: "target/bom.xml", artifactType: 'bom', synchronous: false
```

**Comment by stevespringett** [comment]
It's possible the timestamp in 5.0.0-M3 may be missing or in a different format than previous versions. Unfortunately, the timestamp is defined as a string so it's not possible to validate correctly prior to attempting to import.

https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/resources/schema/dependency-check.2.1.xsd

Also, Dependency-Track does not support importing of Dependency-Check 5.0 scan results. See https://docs.dependencytrack.org/best-practices/

**Comment by jonbrohauge** [comment]
Using version 4.0.2 of Dependency-Check makes the error go away. Thanks for the info.
