### ISSUE TITLE
LDAP auth doesn't work for users with cyrillic names

### ISSUE THREAD

**Issue by DmitriyGrebenshikoff** [DependencyTrack/dependency-track#3503]
### Current Behavior

LDAP authorization does not work for users with cyrillic names, but auto provisioning works.

In logs I have correct distinguished name on first login:
```
2024-02-27 21:22:05,249 DEBUG [Authenticator] Attempting to authenticate user: dmitriy.grebenshikov
2024-02-27 21:22:05,250 DEBUG [ManagedUserAuthenticationService] Attempting to authenticate user: dmitriy.grebenshikov
2024-02-27 21:22:05,263 DEBUG [LdapAuthenticationService] Attempting to authenticate user: dmitriy.grebenshikov
2024-02-27 21:22:05,263 DEBUG [LdapAuthenticationService] Validating credentials for: dmitriy.grebenshikov
2024-02-27 21:22:05,271 DEBUG [LdapConnectionWrapper] Creating directory service context (DirContext)
2024-02-27 21:22:05,308 DEBUG [LdapConnectionWrapper] Performing a directory search for: dmitriy.grebenshikov
2024-02-27 21:22:05,309 DEBUG [LdapConnectionWrapper] Searching for: userPrincipalName=dmitriy.grebenshikov@******.ru
2024-02-27 21:22:05,318 DEBUG [LdapConnectionWrapper] Search for (dmitriy.grebenshikov) produced a result
2024-02-27 21:22:05,318 DEBUG [LdapConnectionWrapper] Creating LDAP context for: CN=Дмитрий Гребенщиков,OU=IT,OU=Users,OU=******,DC=*****,DC=lan
2024-02-27 21:22:05,364 DEBUG [LdapAuthenticationService] The supplied credentials are invalid for: dmitriy.grebenshikov
2024-02-27 21:22:05,376 DEBUG [LdapAuthenticationService] The user (dmitriy.grebenshikov) authenticated successfully but the account has not been provisioned
2024-02-27 21:22:05,377 DEBUG [LdapAuthenticationService] Provisioning: dmitriy.grebenshikov
2024-02-27 21:22:05,377 DEBUG [LdapConnectionWrapper] Creating directory service context (DirContext)
2024-02-27 21:22:05,417 DEBUG [LdapConnectionWrapper] Performing a directory search for: dmitriy.grebenshikov
2024-02-27 21:22:05,417 DEBUG [LdapConnectionWrapper] Searching for: userPrincipalName=dmitriy.grebenshikov@******.ru
2024-02-27 21:22:05,425 DEBUG [LdapConnectionWrapper] Search for (dmitriy.grebenshikov) produced a result
2024-02-27 21:22:05,466 DEBUG [LdapConnectionWrapper] Retrieving groups for: CN=??????? ???????????,OU=IT,OU=Users,OU=******,DC=*****,DC=lan
2024-02-27 21:22:05,468 DEBUG [AlpineQueryManager] Synchronizing team membership for dmitriy.grebenshikov
```

And on next try I have `????` instead of cyrillic part of distinguished name:
```
2024-02-27 21:22:23,839 DEBUG [Authenticator] Attempting to authenticate user: dmitriy.grebenshikov
2024-02-27 21:22:23,839 DEBUG [ManagedUserAuthenticationService] Attempting to authenticate user: dmitriy.grebenshikov
2024-02-27 21:22:23,846 DEBUG [LdapAuthenticationService] Attempting to authenticate user: dmitriy.grebenshikov
2024-02-27 21:22:23,846 DEBUG [LdapAuthenticationService] Validating credentials for: dmitriy.grebenshikov
2024-02-27 21:22:23,853 DEBUG [LdapConnectionWrapper] Creating LDAP context for: CN=??????? ???????????,OU=IT,OU=Users,OU=******,DC=*****,DC=lan
2024-02-27 21:22:23,881 DEBUG [LdapAuthenticationService] An error occurred while attempting to validate credentials
javax.naming.NamingException: Failed to authenticate user
        at alpine.server.auth.LdapConnectionWrapper.createLdapContext(LdapConnectionWrapper.java:108)
        at alpine.server.auth.LdapAuthenticationService.validateCredentials(LdapAuthenticationService.java:155)
        at alpine.server.auth.LdapAuthenticationService.authenticate(LdapAuthenticationService.java:81)
        at alpine.server.auth.Authenticator.authenticate(Authenticator.java:80)
        at org.dependencytrack.resources.v1.UserResource.validateCredentials(UserResource.java:94)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1419)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
        at alpine.server.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:225)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at alpine.server.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:93)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at alpine.server.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:166)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:598)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
        at org.eclipse.jetty.server.Server.handle(Server.java:563)
        at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
        at java.base/java.lang.Thread.run(Unknown Source)
2024-02-27 21:22:23,882 INFO [UserResource] Unauthorized login attempt / invalid credentials / username: dmitriy.grebenshikov / IP Address: 192.168.10.195 / User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
```

Also in UI user shows with `??????` in distinguished name
![image](https://github.com/DependencyTrack/dependency-track/assets/19803145/9bee3d76-55fb-452b-b5b0-b2a326f2b9e4)

### Steps to Reproduce

1. Сreate a user with a сyrillic name, for example "Дмитрий" as the first name and "Гребенщиков" as the last name
2. Try to login

### Expected Behavior

log in

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Container Image

### Database Server

Microsoft SQL Server

### Database Server Version

2012

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nluzgin** [comment]
looks like a strange one.
![image](https://github.com/DependencyTrack/dependency-track/assets/66725266/1a2323a4-6c27-479e-8466-925a01e74d5a)

Im using a docker compose with postgree

**Comment by DmitriyGrebenshikoff** [comment]
Looks like it is a problem with database collation. I tried to update CN in database, but nothing change - in database stores `???` instead of cyrillic names

**Comment by DmitriyGrebenshikoff** [comment]
Changed database collation to `Cyrillic_General_CS_AI` and it works
