### ISSUE TITLE
Issue connecting a AWS RDS Postgres instance to Dependency Track Api Server

### ISSUE THREAD

**Issue by pshakespeare** [DependencyTrack/dependency-track#3575]
### Current Behavior

I've created a helm chart that will run the api server and the front-end application in our kubernetes cluster. The decision was made to use a managed postgres database from AWS( RDS Postgres). After acquire the postgres connection string I assigned it to "ALPINE_DATABASE_URL" then deploying the helm chart, I decided to observe the logs from the api server. 
Logs:
``` string
2024-03-22 15:59:39,591 INFO [EmbeddedJettyServer] alpine-executable-war v2.2.4 (8d84d2cd-5055-4cbc-bfff-50bb7e5a2268) built on: 2023-12-06T15:54:14Z
2024-03-22 15:59:41,956 INFO [Config] --------------------------------------------------------------------------------
2024-03-22 15:59:41,962 INFO [Config] OS Name:      Linux
2024-03-22 15:59:41,964 INFO [Config] OS Version:   5.15.128
2024-03-22 15:59:41,968 INFO [Config] OS Arch:      amd64
2024-03-22 15:59:41,968 INFO [Config] CPU Cores:    4
2024-03-22 15:59:41,981 INFO [Config] Max Memory:   11.6 GB (12,491,685,888.0 bytes)
2024-03-22 15:59:41,982 INFO [Config] Java Vendor:  Eclipse Adoptium
2024-03-22 15:59:41,984 INFO [Config] Java Version: 21.0.1+12-LTS
2024-03-22 15:59:41,984 INFO [Config] Java Home:    /opt/java/openjdk
2024-03-22 15:59:41,984 INFO [Config] Java Temp:    /tmp
2024-03-22 15:59:41,985 INFO [Config] User:         dtrack
2024-03-22 15:59:41,985 INFO [Config] User Home:    /data/
2024-03-22 15:59:41,985 INFO [Config] --------------------------------------------------------------------------------
2024-03-22 15:59:41,985 INFO [Config] Initializing Configuration
2024-03-22 15:59:41,986 INFO [Config] System property alpine.application.properties not specified
2024-03-22 15:59:41,987 INFO [Config] Loading application.properties from classpath
2024-03-22 15:59:41,999 INFO [Config] --------------------------------------------------------------------------------
2024-03-22 15:59:41,999 INFO [Config] Application:  Dependency-Track
2024-03-22 15:59:41,999 INFO [Config] Version:      4.10.1
2024-03-22 15:59:42,000 INFO [Config] Built-on:     2023-12-19T10:56:01Z
2024-03-22 15:59:42,000 INFO [Config] --------------------------------------------------------------------------------
2024-03-22 15:59:42,000 INFO [Config] Framework:    Alpine
2024-03-22 15:59:42,000 INFO [Config] Version :     2.2.4
2024-03-22 15:59:42,000 INFO [Config] Built-on:     2023-12-06T15:54:14Z
2024-03-22 15:59:42,000 INFO [Config] --------------------------------------------------------------------------------
2024-03-22 15:59:42,110 INFO [RequirementsVerifier] Initializing requirements verifier
2024-03-22 15:59:42,110 INFO [UpgradeInitializer] Initializing upgrade framework
2024-03-22 15:59:52,432 ERROR [UpgradeMetaProcessor] An error occurred connecting to the database.
org.postgresql.util.PSQLException: The connection attempt failed.
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
    at org.postgresql.Driver.makeConnection(Driver.java:443)
    at org.postgresql.Driver.connect(Driver.java:297)
    at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
    at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
    at alpine.server.upgrade.UpgradeMetaProcessor.createConnection(UpgradeMetaProcessor.java:187)
    at alpine.server.upgrade.UpgradeMetaProcessor.<init>(UpgradeMetaProcessor.java:63)
    at org.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(UpgradeInitializer.java:56)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1049)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)
    at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:984)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:740)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:901)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
    at org.eclipse.jetty.server.Server.start(Server.java:470)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
    at org.eclipse.jetty.server.Server.doStart(Server.java:415)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
    at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:100)
Caused by: java.net.SocketTimeoutException: Connect timed out
    at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
    at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
    at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
    at java.base/java.net.Socket.connect(Unknown Source)
    at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
    at org.postgresql.core.PGStream.<init>(PGStream.java:98)
    at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
    ... 26 common frames omitted
2024-03-22 15:59:52,437 ERROR [UpgradeInitializer] An error occurred determining database schema version. Unable to continue.
alpine.server.upgrade.UpgradeException: An error occurred connecting to the database.
    at alpine.server.upgrade.UpgradeMetaProcessor.createConnection(UpgradeMetaProcessor.java:193)
    at alpine.server.upgrade.UpgradeMetaProcessor.<init>(UpgradeMetaProcessor.java:63)
    at org.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(UpgradeInitializer.java:56)
    at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1049)
    at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)
    at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:984)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:740)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:901)
    at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
    at org.eclipse.jetty.server.Server.start(Server.java:470)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89)
    at org.eclipse.jetty.server.Server.doStart(Server.java:415)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
    at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:100)
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
    at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
    at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
    at org.postgresql.Driver.makeConnection(Driver.java:443)
    at org.postgresql.Driver.connect(Driver.java:297)
    at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
    at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
    at alpine.server.upgrade.UpgradeMetaProcessor.createConnection(UpgradeMetaProcessor.java:187)
    ... 19 common frames omitted
Caused by: java.net.SocketTimeoutException: Connect timed out
    at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
    at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
    at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
    at java.base/java.net.Socket.connect(Unknown Source)
    at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
    at org.postgresql.core.PGStream.<init>(PGStream.java:98)
    at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
    at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
    ... 26 common frames omitted
Stream closed EOF for dep-track/apiserver-deployment-5bb8cccc7-4stwv (apiserver)
```

I did see this [thread](https://github.com/DependencyTrack/dependency-track/issues/3240) on the subject, but there wasn't a solution.

AWS RDS Postgres connection string provided:  jdbc:postgresql://provided-hostname-from-aws:5342/dtrack

Environment Variables Settings:
```yaml
                - name: ALPINE_DATABASE_DRIVER
                  value: org.postgresql.Driver
                - name: ALPINE_DATABASE_POOL_ENABLED
                  value: "true"
                - name: ALPINE_DATABASE_POOL_IDLE_TIMEOUT
                  value: "300000"
                - name: ALPINE_DATABASE_POOL_MAX_LIFETIME
                  value: "600000"
                - name: ALPINE_DATABASE_POOL_MAX_SIZE
                  value: "20"
                - name: ALPINE_DATABASE_POOL_MIN_IDLE
                  value: "10"
                - name: ALPINE_DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: apiserver-secret
                      key: POSTGRES_DB_URL
                - name: ALPINE_DATABASE_USERNAME
                  value: postgres
                - name: ALPINE_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: apiserver-secret
                      key: DB_PASSWORD
                - name: ALPINE_DATABASE_NAME
                  value: dtrack
                - name: ALPINE_DATABASE_MODE
                  value: external 
```

I tried resolving the connection string from the node the api server was scheduled to, and I had success -- so I'm stomped as to why the api server is having issues connecting. 

### Steps to Reproduce

Even though I'm using a helm chart

This issue can be reproduced using the provided docker-compose file from Dependency Track

1. In the docker-compose file, assign the environment variable "ALPINE_DATABASE_URL" with a managed postgres database connection string.
2.  In the same directory run: docker-compose up -d 
3.  docker logs <container-name>

### Expected Behavior

I expected the api server to make a connection to the postgres instance in AWS

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

16.1

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by valentijnscholten** [comment]
>In the docker-compose file, assign the environment variable "ALPINE_DATABASE_URL" with a managed postgres database connection string.

Did you also specify username and password? I am using RDS Postgres on my 11 instances of DT without issue. Are you 100% sure the container can reach the RDS instance?

**Comment by pshakespeare** [comment]
@valentijnscholten, thanks for reaching out -- Yes, I've provided both. In the "Environment Variables Settings" above you'll find my current environment variables.

**Comment by valentijnscholten** [comment]
I meant for docker compose, you only mention the URL.

**Comment by pshakespeare** [comment]
@valentijnscholten, testing today.

**Comment by pshakespeare** [comment]
@valentijnscholten, after further review, I needed to update the inbound/outbound rules in the VPC security group

**Comment by pshakespeare** [comment]
the apiserver had troubles connecting to the AWS RDS Postgres instance due to outbound rules not being set in the VPC security group
