### ISSUE TITLE
issues with team notifications

### ISSUE THREAD

**Issue by khaledgithubwl** [DependencyTrack/dependency-track#3626]
### Current Behavior

when I use "Select team as recipient" for notification I get this error: 
ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.ClassCastException: class javax.json.JsonValueImpl cannot be cast to class javax.json.JsonString (javax.json.JsonValueImpl and javax.json.JsonString are in unnamed module of loader

### Steps to Reproduce

1.use Select team as recipient

### Expected Behavior

receiving notification

### Dependency-Track Version

4.10.1

### Dependency-Track Distribution

Executable WAR

### Database Server

PostgreSQL

### Browser

Google Chrome

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
@khaledgithubwl Can you share the complete stack trace please?

**Comment by khaledgithubwl** [comment]
@nscuro 
ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.ClassCastException: class javax.json.JsonValueImpl cannot be cast to class javax.json.JsonString (javax.json.JsonValueImpl and javax.json.JsonString are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @1fa268de)
	at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(JsonObjectBuilderImpl.java:252)
	at org.dependencytrack.notification.publisher.SendMailPublisher.lambda$parseDestination$1(SendMailPublisher.java:178)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at org.dependencytrack.notification.publisher.SendMailPublisher.parseDestination(SendMailPublisher.java:191)
	at org.dependencytrack.notification.publisher.SendMailPublisher.inform(SendMailPublisher.java:73)
	at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:91)
	at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:117)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by nscuro** [comment]
@khaledgithubwl Does the offending alert rule have a destination specified?
<img width="513" alt="image" src="https://github.com/DependencyTrack/dependency-track/assets/5693141/8683fe27-b293-4d5c-ac4f-2f4273628f6c">

**Comment by nscuro** [comment]
For reference, every alert rule has a `publisherConfig` JSON object where the *Destination* is stored. The *Destination* can be empty, `null`, or not exist at all. The error you're experiencing would not happen in those cases.

However, if the `destination` field of the JSON object is a number, the error would be triggered. Through configuration via UI, `destination` should never end up being a number, since the UI will always treat is as string.

Was this particular rule created through automation? Perhaps the `destination` was set to a number by accident? Maybe the `"` for denoting a string are missing?

![Untitled](https://github.com/DependencyTrack/dependency-track/assets/5693141/8b7840bb-1cb4-4167-bc56-6e3af8a3fc40)

**Comment by nscuro** [comment]
@khaledgithubwl Kind ping to please provide more information.

**Comment by khaledgithubwl** [comment]
hello @nscuro sorry for the late response, the destination field is empty only the team recipient is indicated. 
in the publisherConfig i have this publisherConfig: "{\"destination\":\"\"}"
the team selected appears only under teams: .. name: 

Thank you for your help :)

**Comment by khaledgithubwl** [comment]
hello @nscuro any news on this ? 
best regards,

**Comment by nscuro** [comment]
The configuration you showed matches what I tried during my initial attempts to reproduce the issue. I haven't tried reproducing it since. Is it still occurring with v4.11.1?

**Comment by khaledgithubwl** [comment]
hello @nscuro I did not do the upgrade it yet .. do you think the issue will be solved in this newer version ? 
Best Regards,

**Comment by nscuro** [comment]
Closing as stale.
