### ISSUE TITLE
NVD Mirror Returned Status Code: 503

### ISSUE THREAD

**Issue by RobSHK** [DependencyTrack/dependency-track#3927]
### Current Behavior

2024-07-08 10:08:08,443 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 5 time
2024-07-08 10:08:10,049 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 6 time
2024-07-08 10:08:11,955 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 7 time
2024-07-08 10:08:24,709 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 8 time
2024-07-08 10:09:33,776 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 5 time
2024-07-08 10:09:35,382 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 6 time
2024-07-08 10:09:37,296 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 7 time
2024-07-08 10:09:39,503 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 8 time
2024-07-08 10:09:42,009 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 9 time
2024-07-08 10:09:44,814 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 10 time
2024-07-08 10:09:47,920 [] WARN [io.github.jeremylong.openvulnerability.client.nvd.NvdApiRetryStrategy] NVD API request failures are occurring; retrying request for the 11 time
2024-07-08 10:09:48,137 [] ERROR [org.dependencytrack.tasks.NistApiMirrorTask] An unexpected error occurred while mirroring the contents of the National Vulnerability Database
io.github.jeremylong.openvulnerability.client.nvd.NvdApiException: NVD Returned Status Code: 503
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:359)
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:343)
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:343)
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:343)
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:343)
        at io.github.jeremylong.openvulnerability.client.nvd.NvdCveClient.next(NvdCveClient.java:343)
        at org.dependencytrack.tasks.NistApiMirrorTask.inform(NistApiMirrorTask.java:157)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:110)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024-07-08 10:09:48,137 [] INFO [org.dependencytrack.tasks.NistApiMirrorTask] Mirroring of 0 CVEs completed in PT4M47.995753241S

### Steps to Reproduce

1.Start DT 
2. DT tries to Mirror the NVD DB

### Expected Behavior

Successfully NVD Mirroring

### Dependency-Track Version

4.11.3

### Dependency-Track Distribution

Executable WAR

### Database Server

Microsoft SQL Server

### Browser

Microsoft Edge

### Checklist

- [X] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [X] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by otbe** [comment]
I think this can be related to https://github.com/DependencyTrack/dependency-track/pull/3926 and everything around it. I assume https://github.com/DependencyTrack/dependency-track/pull/3926 is going to fix this. At least since NVD roleld out the new field in their API there was never a successful update of the NVD CVEs anymore in my dtrack installation.

**Comment by nscuro** [comment]
Sadly the NVD API has been flaky from the very beginning. Related DC issue would be https://github.com/jeremylong/DependencyCheck/issues/6758. The API returning 503s is not something we can do anything about. The library that interacts with the API is already performing numerous retries.

FWIW, remember that you can still mirror the NVD via the feed file based approach - simply disable API mirroring in the settings. We left that capability in for precisely this reason.

**Comment by otbe** [comment]
I think even with NVD Api key theres no successful ingest of NVD data via API right now because the lib dtrack uses under the hood is broken in that version and fails with these "retry" errors even though theres an exception. Same was true for the mvn/gradle plugins of dependency check. https://github.com/DependencyTrack/dependency-track/pull/3926 is going to fix this.

**Comment by nscuro** [comment]
*Sigh* I guess you're right. Tested API mirroring with v4.11.4 and `master` and it worked with `master` but not v4.11.4. Looks like we'll need a bugfix release...

**Comment by RobSHK** [comment]
I've tested the v4.11.5, seems that it fixed the issue.
