### ISSUE TITLE
NPE on BomUploadProcessingTask at StateManagerImpl.transitionReadField

### ISSUE THREAD

**Issue by thorin** [DependencyTrack/dependency-track#395]
### Current Behavior:
Once in while when a Jenkins uploads synchronously the generated BOM to dependency track we fail to get a response from Dependency-Track

On Dependency-Track we see a NullPointerException.

### Steps to Reproduce:
Occurs randomly when uploading a BOM generated by **@cyclonedx/bom** by appending its results to the results generated by **cyclonedx-gradle-plugin**.

### Environment:
  - Dependency-Track Version: v3.5.1
  - Distribution: Docker
  - BOM Format & Version: CycloneDX BOM
  - Database Server: PostgreSQL
  - Browser: N/A

### Additional Details:
Stack Trace:
```
09:53:56.922 INFO [MetricsUpdateTask] Executing metrics update on project: d90cf0bc-71ee-4140-8cbb-a542eafeda44
10:29:48.913 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: fea6f545-c45c-43d1-a6df-a9821f544187
10:30:08.576 INFO [BomUploadProcessingTask] Processed 1215 components uploaded to project fea6f545-c45c-43d1-a6df-a9821f544187
10:30:08.580 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: null
        at org.datanucleus.state.StateManagerImpl.transitionReadField(StateManagerImpl.java:1047)
        at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:4091)
        at org.dependencytrack.model.Component.dnGetpurl(Component.java)
        at org.dependencytrack.model.Component.getPurl(Component.java:355)
        at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:61)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:97)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by thorin** [comment]
Please note that to view this complete stack trace I needed to had `-XX:-OmitStackTraceInFastThrow` to the JVM startup arguments. 
Otherwise I would only see "java.lang.NullPointerException: null" on the logs.

**Comment by stevespringett** [comment]
Thanks for the report. I noticed this about a week ago. I don't think the contents of the bom have anything to do with it, nor do I think the issue is database-specific, as when I encountered the issue, I was using the embedded h2 instance.

Will need to investigate, but thanks for the stack trace. That gives me a really good idea about what's going on.

**Comment by stevespringett** [comment]
Note to self:

- Ensure QueryManager objects are fresh and not passed around
- Ensure the Component object (if being passed around) is being refreshed from each new QM instance
- Check PURL logic to ensure the case of PURLs existing in a BOM but not valid is in place

**Comment by thorin** [comment]
I'm not familiar with **datanucleus** and the problem comes from deep inside it.

From the stack trace I would guess the field `StateManagerImpl.myEC` is null.
Which might mean that `getPurl` was called when the `StateManager` was disconnected.

**Comment by msymons** [comment]
I saw a very similar exception yesterday with DT 3.5.1 and a v1.1. BOM generated by cyclonedx-maven-plugin.

```
2019-07-21 22:00:12,684 [] INFO [org.dependencytrack.tasks.BomUploadProcessingTask] Processed 184 components uploaded to project 7b2edc73-9b4a-4a10-8178-24f6fa3cb5df
2019-07-21 22:00:12,696 [] INFO [org.dependencytrack.tasks.scanners.OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
2019-07-21 22:00:12,698 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: null
	at org.datanucleus.state.StateManagerImpl.transitionReadField(StateManagerImpl.java:1047)
	at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:4091)
	at org.dependencytrack.model.Component.dnGetpurl(Component.java)
	at org.dependencytrack.model.Component.getPurl(Component.java:355)
	at org.dependencytrack.tasks.scanners.OssIndexAnalysisTask.analyze(OssIndexAnalysisTask.java:140)
	at org.dependencytrack.tasks.scanners.OssIndexAnalysisTask.inform(OssIndexAnalysisTask.java:110)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I have seen 716 occurrences of "An unknown error occurred in an asynchronous event or notification thread" since 16 May.  The above exception is associated with just 10 of these (normally there is no Exception)  and it looks like the problem did occur in DT v3.4.1 (albeit for `StateManagerImpl.java:1035`).

**Comment by stevespringett** [comment]
@msymons When you've seen the error, was synchronous publishing mode used?

Have either of you seen the error without synchronous mode?

**Comment by msymons** [comment]
I think that I have seen the error `StateManagerImpl.transitionReadField` for projects that do **NOT** have synchronous mode.

My DT is now tracking 177 projects.  
* At least 120 use scripted pipelines based on name and version, with no synchronous mode (waiting for fix/enhancement in  DT v3.6).
* About 12 projects use declarative pipelines with synchronous mode,
* The remaining projects are Maven/Freestyle and use synchronous mode.

If the exception log in my earlier message is linked to project `7b2edc73-9b4a-4a10-8178-24f6fa3cb5df` then that project is one that is not using synchronous mode.  

For this example...

```
2019-06-16 21:44:34,233 [] INFO [org.dependencytrack.tasks.MetricsUpdateTask] Executing metrics update on project: 46fcb625-2602-4996-aa06-b3c5774ab9f2
2019-06-16 21:44:37,652 [] INFO [org.dependencytrack.tasks.BomUploadProcessingTask] Processed 188 components uploaded to project 1908f306-2323-460e-8447-fd69f1b6c8d3
2019-06-16 21:44:37,659 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.NullPointerException: null
	at org.datanucleus.state.StateManagerImpl.transitionReadField(StateManagerImpl.java:1047)
	at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:4091)
	at org.dependencytrack.model.Component.dnGetpurl(Component.java)
```
...I would assume that the project of interest is `1908f306-2323-460e-8447-fd69f1b6c8d3`.  If so, that's also not using synchronous mode.

**Comment by thorin** [comment]
I don't have many projects yet, and the only ones I have are synchronous.

**Comment by stevespringett** [comment]
I was able to replicate the issue simply by uploading several BOMs to the same project over and over again.

With the changes implemented in https://github.com/DependencyTrack/dependency-track/commit/b39d2a71593ca64f129afa24074e6068c25c4e5e, I haven't been able to reproduce. Therefore, I believe this issue is resolved.
