### ISSUE TITLE
bom.xml parsing exception

### ISSUE THREAD

**Issue by baraths84** [DependencyTrack/dependency-track#418]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
When the bom.xml element url for " issue-tracker" is with query param it is throwing a exception. 

`<component type="library">
                <name>weinre</name>
                <version>2.0.0-pre-I0Z7U9OV</version>
                <description>
                    <![CDATA[WEb INspector REmote]]>
                </description>
                <hashes>
                    <hash alg="SHA-1">fef8aa223921f7b40bbbbd4c3ed4302f6fd0a813</hash>
                </hashes>
                <purl>pkg:npm/weinre@2.0.0-pre-I0Z7U9OV</purl>
                <externalReferences>
                    <reference type="website">
                        <url>http://people.apache.org/~pmuellr/weinre/</url>
                    </reference>
                    <reference type="issue-tracker">
                        <url>https://issues.apache.org/jira/secure/IssueNavigator!executeAdvanced.jspa?jqlQuery=project%3DCB+and+component%3Dweinre&runQuery=true&clear=true</url>
                    </reference>
                    <reference type="vcs">
                        <url>https://git-wip-us.apache.org/repos/asf/cordova-weinre.git</url>
                    </reference>
                </externalReferences>
            </component>`

----
<reference type="issue-tracker">  with url with query param is throwing  an exception

Caused by: com.thoughtworks.xstream.io.StreamException:
	at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:73)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readRealEvent(AbstractPullReader.java:148)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.readEvent(AbstractPullReader.java:135)
	at com.thoughtworks.xstream.io.xml.AbstractPullReader.getValue(AbstractPullReader.java:197)
	at com.thoughtworks.xstream.io.ReaderWrapper.getValue(ReaderWrapper.java:48)
	at com.thoughtworks.xstream.converters.SingleValueConverterWrapper.unmarshal(SingleValueConverterWrapper.java:49)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	... 52 common frames omitted
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[45182,157]
Message: **The reference to entity "runQuery" must end with the ';' delimiter.**
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:604)
	at com.thoughtworks.xstream.io.xml.StaxReader.pullNextEvent(StaxReader.java:58)
	... 58 common frames omitted

### Steps to Reproduce:

Add this line to any 

`<reference type="issue-tracker">
                        <url>https://issues.apache.org/jira/secure/IssueNavigator!executeAdvanced.jspa?jqlQuery=project%3DCB+and+component%3Dweinre&runQuery=true&clear=true</url>
                    </reference>`

### Expected Behavior:
 No parsing exception on auto generated bom .

### Environment:
  
  - Dependency-Track Version: latest stable version
  - Distribution: docker
  - BOM Format & Version:
<bom xmlns="http://cyclonedx.org/schema/bom/1.1" version="1" serialNumber="urn:uuid:f16decbb-a9fe-4a22-aa62-fb03a2b52f58">

  - Database Server: [  PostgreSQL ]
  - Browser: Chrome

**Comment by stevespringett** [comment]
This is not an issue with Dependency-Track. The CycloneDX Node module was creating invalid XML. Version 1.0.3 of the Node module was released which solves this issue.
