### ISSUE TITLE
NullPointerException in Trivy Analyzer if Component doesn't have a Version

### ISSUE THREAD

**Issue by FFichtner** [DependencyTrack/dependency-track#4257]
### Current Behavior

Hello,

I noticed that since the migration to Protobuf for the Trivy Integration a NullPointerException is thrown if at least one component doesn't have a version which completely stops the analysis for all other components.
We are using CyloneDX 1.5

Server Error
```
2024-10-15 07:55:41,708 ERROR [VulnerabilityAnalysisTask] An unexpected error occurred performing a vulnerability analysis task
java.lang.NullPointerException: null
    at trivy.proto.common.Package$Builder.setVersion(Package.java:1730)
    at org.dependencytrack.tasks.scanners.TrivyAnalysisTask.analyze(TrivyAnalysisTask.java:275)
    at org.dependencytrack.tasks.scanners.TrivyAnalysisTask.inform(TrivyAnalysisTask.java:158)
    at org.dependencytrack.tasks.VulnerabilityAnalysisTask.performAnalysis(VulnerabilityAnalysisTask.java:168)
    at org.dependencytrack.tasks.VulnerabilityAnalysisTask.analyzeComponents(VulnerabilityAnalysisTask.java:128)
    at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:72)
    at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:110)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
```

For now I reverted dependency-track to 4.11.5 and Trivy to 0.53.0 as it still works properly there.

### Steps to Reproduce

1. Upload a SBOM with at least one component without a Version e.g.
```
{
  "bomFormat" : "CycloneDX",
  "specVersion" : "1.5",
  "serialNumber" : "urn:uuid:975bf412-c238-415d-be65-cf8eb1acab54",
  "version" : 1,
  "metadata" : {
    "timestamp" : "2024-10-15T07:58:12Z",
    "tools" : [
      {
        "vendor" : "OWASP",
        "name" : "Dependency-Track",
        "version" : "4.12.0"
      }
    ],
    "component" : {
      "type" : "application",
      "bom-ref" : "73a0b27c-101f-4f02-8dc7-603531b83444",
      "name" : "some-application-name",
      "version" : "1.0.0"
    }
  },
  "components" : [
    {
      "type" : "application",
      "bom-ref" : "16ada406-dbc9-45de-8e8f-bb9025e34b8f",
      "name" : "some-component-name",
      "properties" : [
        {
          "name" : "aquasecurity:trivy:SchemaVersion",
          "value" : "2"
        }
      ]
    },
   ...
  ],
  ...
}
```
2. Trigger "Reanalyze" under "Audit Vulnerabilities"

### Expected Behavior

Even if one component has no Version the rest of the components get analysed properly.

I suppose if no Version exists it should be possibly to completely skip the analysis since no vulnerability information would be found either way.

### Dependency-Track Version

4.12.0

### Dependency-Track Distribution

Container Image

### Database Server

PostgreSQL

### Database Server Version

16.4

### Browser

Google Chrome

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by FFichtner** [comment]
Thanks a lot for the quick update. Will retest this issue as soon as 4.12.1 is available.
If it reappears I will deeper reinvestigate the issue.
