### ISSUE TITLE
Not able to upload SBOM with REST API if ACCESS_MANAGEMENT permission is not set

### ISSUE THREAD

**Issue by WillTeasle** [DependencyTrack/dependency-track#4341]
### Current Behavior

We are not able to upload a SBOM via REST API if ACCESS_MANAGEMENT permission is not set to the Team from which the API Key is generated.
If the permission is not defined dependency-track response is HTTP 403 (Forbidden)

### Steps to Reproduce

1. Assign BOM_UPLOAD and PROJECT_CREATION_UPLOAD permissions only to a given team and generate the API_KEY
2. call latest cdxgen to generate a sbom and upload it to server using the API_KEY: `cdxgen --recurse --type universal --spec-version 1.5 -o sbom.json --server-url "https://dependencytrackapi.myserver.test" --api-key "API_KEY" --project-name "projectname" --project-id "f654677b-cf5b-48d3-8fec-b128f658a6a7" --project-version 1.0`

Get a HTTPError 403 (Forbidden):

`Submitting BOM to https://dependencytrackapi.myserver.test/api/v1/bom params projectname 1.0
Unable to submit the SBOM to the Dependency-Track server using POST method HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (file:///usr/local/lib/node_modules/@cyclonedx/cdxgen/node_modules/got/dist/source/as-promise/index.js:92:42)
    at Object.onceWrapper (node:events:632:26)
    at Request.emit (node:events:529:35)
    at Request.emit (node:domain:489:12)
    at Request._onResponseBase (file:///usr/local/lib/node_modules/@cyclonedx/cdxgen/node_modules/got/dist/source/core/index.js:603:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///usr/local/lib/node_modules/@cyclonedx/cdxgen/node_modules/got/dist/source/core/index.js:643:13) {
  input: undefined,`

3. add ACCESS_MANAGEMENT to team permissions and redo step 2
The SBOM is uploaded  as expected.

### Expected Behavior

It should not be required to set ACCESS_MANAGEMENT permissions to publish a SBOM.
By enabling this permission, a corrupted CI pipeline publishing SBOM could also allow an attacker to add unauthorized access to dependency-track.

### Dependency-Track Version

4.11.x

### Dependency-Track Distribution

Container Image

### Database Server

Microsoft SQL Server

### Browser

Google Chrome

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by WillTeasle** [comment]
After investigations, this happens only if project-id is specified on the command-line. Not sure if this is an expected behaviour or not.

**Comment by valentijnscholten** [comment]
What error message do you get from DT? (There should be more than just the 403 code).

The code that processed the BOM and might trigger 403s is here: https://github.com/DependencyTrack/dependency-track/blob/854744776f5e1836d60fbef51584981fa540a01a/src/main/java/org/dependencytrack/resources/v1/BomResource.java#L288

**Comment by WillTeasle** [comment]
After redeployment of the dependencytrackapi container and regeneration of API KEYs, I was not able to reproduce. Since there is no repro with the new setup I close the ticket.

**Comment by WillTeasle** [comment]
After redeployment of the dependencytrackapi container and regeneration of API KEYs, I was not able to reproduce. Since there is no repro with the new setup I close the ticket.

**Comment by iscrutton** [comment]
We experienced the same problem starting on Sept 22, 2024.

We did not have "ACCESS_MANAGEMENT" enabled for the REST API and we received "Access Denied" messages on our projects.
After enabling "ACESS_MANAGEMENT" the SBOM could be uploaded.

This permission was not enabled in the past for the upload user and we did not experience that problem.
