### ISSUE TITLE
Uncaught internal server error when retrieving projects' findings

### ISSUE THREAD

**Issue by antoinbo** [DependencyTrack/dependency-track#4351]
### Current Behavior

Multiple projects are failing to load the findings, the "Audit Vulnerabilities" tab indicates [6] [0] instead of [6] [6]:
![Image](https://github.com/user-attachments/assets/0516a5a8-cde6-4d09-8ab2-606c175b6d1e)

While the table stays empty:
![Image](https://github.com/user-attachments/assets/f83fc4bd-3905-4037-81bd-b23905b10935)

Two requests are failing:
![Image](https://github.com/user-attachments/assets/c17b3f7f-3b3e-4d7b-bd10-ef953492b458)

Here are the errors for the two failing requests:
```
dependencytrack-apiserver  | 2024-10-30 09:47:43,222 ERROR [GlobalExceptionHandler] Uncaught internal server error [requestId=025f0240-060a-4739-a894-79a1f51b6ea5]
dependencytrack-apiserver  | java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "affectedFindings" is null
dependencytrack-apiserver  |    at org.dependencytrack.persistence.FindingsQueryManager.lambda$getFindings$4(FindingsQueryManager.java:331)
dependencytrack-apiserver  |    at java.base/java.lang.Iterable.forEach(Unknown Source)
dependencytrack-apiserver  |    at org.dependencytrack.persistence.FindingsQueryManager.getFindings(FindingsQueryManager.java:328)
dependencytrack-apiserver  |    at org.dependencytrack.persistence.QueryManager.getFindings(QueryManager.java:1162)
dependencytrack-apiserver  |    at org.dependencytrack.resources.v1.FindingResource.getFindingsByProject(FindingResource.java:125)
dependencytrack-apiserver  |    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
dependencytrack-apiserver  |    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
dependencytrack-apiserver  |    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:397)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:349)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:312)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1379)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
dependencytrack-apiserver  |    at alpine.server.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:225)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
dependencytrack-apiserver  |    at alpine.server.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:93)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
dependencytrack-apiserver  |    at alpine.server.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:166)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:208)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
dependencytrack-apiserver  |    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
dependencytrack-apiserver  |    at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
dependencytrack-apiserver  |    at org.eclipse.jetty.server.Server.handle(Server.java:182)
dependencytrack-apiserver  |    at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
dependencytrack-apiserver  |    at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:414)
dependencytrack-apiserver  |    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
dependencytrack-apiserver  |    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
dependencytrack-apiserver  |    at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
dependencytrack-apiserver  |    at java.base/java.lang.Thread.run(Unknown Source)
dependencytrack-apiserver  | 2024-10-30 09:47:43,224 ERROR [GlobalExceptionHandler] Uncaught internal server error [requestId=ddb1d535-789d-4daa-9882-0ff492d7179a]
dependencytrack-apiserver  | java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "affectedFindings" is null
dependencytrack-apiserver  |    at org.dependencytrack.persistence.FindingsQueryManager.lambda$getFindings$4(FindingsQueryManager.java:331)
dependencytrack-apiserver  |    at java.base/java.lang.Iterable.forEach(Unknown Source)
dependencytrack-apiserver  |    at org.dependencytrack.persistence.FindingsQueryManager.getFindings(FindingsQueryManager.java:328)
dependencytrack-apiserver  |    at org.dependencytrack.persistence.QueryManager.getFindings(QueryManager.java:1162)
dependencytrack-apiserver  |    at org.dependencytrack.resources.v1.FindingResource.getFindingsByProject(FindingResource.java:125)
dependencytrack-apiserver  |    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
dependencytrack-apiserver  |    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:274)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
dependencytrack-apiserver  |    at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
dependencytrack-apiserver  |    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:266)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:253)
dependencytrack-apiserver  |    at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:696)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:397)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:349)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:312)
dependencytrack-apiserver  |    at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1379)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
dependencytrack-apiserver  |    at alpine.server.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:225)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
dependencytrack-apiserver  |    at alpine.server.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:93)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
dependencytrack-apiserver  |    at alpine.server.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:166)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:208)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
dependencytrack-apiserver  |    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
dependencytrack-apiserver  |    at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)
dependencytrack-apiserver  |    at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)
dependencytrack-apiserver  |    at org.eclipse.jetty.server.Server.handle(Server.java:182)
dependencytrack-apiserver  |    at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)
dependencytrack-apiserver  |    at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:414)
dependencytrack-apiserver  |    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
dependencytrack-apiserver  |    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
dependencytrack-apiserver  |    at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)
dependencytrack-apiserver  |    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)
dependencytrack-apiserver  |    at java.base/java.lang.Thread.run(Unknown Source)
```

As a side effect vulnerability upload to DefectDojo also crashes:
```
dependencytrack-apiserver  | 2024-10-30 10:56:54,090 DEBUG [VulnerabilityManagementUploadTask] Initializing integration point: DefectDojo for project: 28724e38-0366-45c2-a860-d1971cc93f7e
dependencytrack-apiserver  | 2024-10-30 10:56:54,105 DEBUG [VulnerabilityManagementUploadTask] Uploading findings to DefectDojo for project: 28724e38-0366-45c2-a860-d1971cc93f7e
dependencytrack-apiserver  | 2024-10-30 10:56:54,116 DEBUG [DefectDojoClient] Pulling DefectDojo Tests API ...
dependencytrack-apiserver  | 2024-10-30 10:56:54,116 DEBUG [DefectDojoClient] Make the first pagination call
dependencytrack-apiserver  | 2024-10-30 10:56:54,172 DEBUG [DefectDojoClient] Successfully retrieved the test list
dependencytrack-apiserver  | 2024-10-30 10:56:54,172 DEBUG [DefectDojoUploader] Found existing test Id: 2186
dependencytrack-apiserver  | 2024-10-30 10:56:54,174 DEBUG [DefectDojoClient] Re-reimport Dependency-Track findings to DefectDojo per Engagement
dependencytrack-apiserver  | 2024-10-30 10:56:54,362 DEBUG [DefectDojoClient] Successfully reimport findings to DefectDojo
dependencytrack-apiserver  | 2024-10-30 10:56:54,367 DEBUG [VulnerabilityManagementUploadTask] Initializing integration point: DefectDojo for project: bb9f8143-3ec2-4c2d-ac61-5ff60413e3ce
dependencytrack-apiserver  | 2024-10-30 10:56:54,410 ERROR [VulnerabilityManagementUploadTask] Cannot invoke "java.util.List.iterator()" because "affectedFindings" is null
dependencytrack-apiserver  | 2024-10-30 10:56:54,410 DEBUG [DefectDojoUploadTask] DefectDojo upload complete
```

### Steps to Reproduce

1. Create a new project.
2. Upload [418554ad-9b3c-4dd9-a487-f08e6fa5c8e1-inventory.cdx.json](https://github.com/user-attachments/files/17630467/418554ad-9b3c-4dd9-a487-f08e6fa5c8e1-inventory.cdx.json) in new project's "Components" tab.
3. Wait few seconds so the BOM is processed, then refresh the page.
4. The tab "Audit Vulnerabilities" should report findings [5] [0], but the list is empty.

### Expected Behavior

No null exception happens.
An error message is displayed to the user (without looking in logs), when:
* An error happens during the project loading.
* An error happens during the vulnerability upload (especially to DefectDojo).

### Dependency-Track Version

4.12.1

### Dependency-Track Distribution

Container Image

### Database Server

Microsoft SQL Server

### Browser

Microsoft Edge

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by antoinbo** [comment]
Hi @nscuro, thanks for the fix!

I wanted to test it using the last snapshot, but I hit the same #4267 issue with no vulnerabilities found in System.IO.Packaging component, while two are expected.
Therefore, I realise reproducing that issue was not possible and hope this fix is not hiding a different problem.

Best regards,
Antoine
