### ISSUE TITLE
Cloning of project throws NullPointerException

### ISSUE THREAD

**Issue by rbt-mm** [DependencyTrack/dependency-track#4413]
### Current Behavior

While cloning one of our projects, the `CloningProjectTask` is successfully started and the API returns a `200`, but the cloning operation is unsuccessful because of the following error:
```
2024-11-27 13:50:38,251 [] INFO [org.dependencytrack.resources.v1.ProjectResource] Project Acme : 3.4.1 is being cloned by ***** [requestId=6370ba37-2c81-45aa-b8d3-b4eb42dc4611]
2024-11-27 13:50:38,253 [] INFO [org.dependencytrack.tasks.CloneProjectTask] Cloning project for version 3.5.0 [eventToken=4f8b98b7-6b9d-45d7-a3cf-1f387380ec2a, projectUuid=5d008304-0f38-497c-9fa7-6ca820cb7676]
2024-11-27 13:50:40,503 [] ERROR [org.dependencytrack.tasks.CloneProjectTask] Failed to clone project
java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "clonedComponentUuid" is null
	at org.dependencytrack.persistence.ProjectQueryManager.lambda$clone$2(ProjectQueryManager.java:714)
	at alpine.persistence.Transaction.call(Transaction.java:139)
	at alpine.persistence.AbstractAlpineQueryManager.callInTransaction(AbstractAlpineQueryManager.java:542)
	at alpine.persistence.AbstractAlpineQueryManager.callInTransaction(AbstractAlpineQueryManager.java:553)
	at org.dependencytrack.persistence.ProjectQueryManager.clone(ProjectQueryManager.java:600)
	at org.dependencytrack.persistence.QueryManager.clone(QueryManager.java:511)
	at org.dependencytrack.tasks.CloneProjectTask.inform(CloneProjectTask.java:49)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:110)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

This is the only project where this error occurred so far. Two other `CloningProjectTask` were found in our logs for different projects which worked fine.
This error occurred when trying to clone via API and via UI.

Did anyone else experience a similar project or has any idea why this could happen?

### Steps to Reproduce

Not sure how to reproduce this, because right now it only happened for one specific project where I couldn't find any anomalies or other weird stuff during a quick investigation :(

### Expected Behavior

Cloning of the project via API and UI should be successful.

### Dependency-Track Version

4.12.1

### Dependency-Track Distribution

Container Image

### Database Server

Microsoft SQL Server

### Browser

Mozilla Firefox

### Checklist

- [x] I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/dependency-track/blob/master/CONTRIBUTING.md#filing-issues)
- [x] I have checked the [existing issues](https://github.com/DependencyTrack/dependency-track/issues) for whether this defect was already reported

**Comment by nscuro** [comment]
The failure happens in the code responsible for re-wiring the dependency graph of the cloned project, more precisely the project's direct dependencies: 

https://github.com/DependencyTrack/dependency-track/blob/193d0f9c93f9b90a777b9dc050cd4e3bab7cd776/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java#L710-L718

The source component UUIDs in the above snippet are taken from the project's `directDependencies` JSON: https://github.com/DependencyTrack/dependency-track/blob/193d0f9c93f9b90a777b9dc050cd4e3bab7cd776/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java#L674-L678

So this is caused by the project referring to UUIDs of components that do not exist.

I will add a `null` check here and log a warning instead. But ultimately the the data is broken / incomplete. I suspect this could happen if the to-be-cloned project was itself cloned before the dependency graph re-wiring was introduced (IIRC that was in v4.12.0).

**Comment by nscuro** [comment]
@rbt-mm Short-term, you can fix this by importing a new BOM into the project you're trying to clone. That should repair the dependency graph.
