### ISSUE TITLE
Exception while parsing nvdcve

### ISSUE THREAD

**Issue by relnah** [DependencyTrack/dependency-track#468]
When dtrack initializes NIST mirroring the parser can't handle format of certain cve identifiers.
Log with stack trace provided below.

### Current Behavior:
Exception is thrown when parsing nvdcve-1.0-2014.json

### Steps to Reproduce:
Trigger download and parsing of NVD

### Expected Behavior:
Successful parse

### Environment:
  
  - Dependency-Track Version: 3.6.1
  - Distribution: Docker
  - BOM Format & Version: N/A
  - Database Server: PostgreSQL
  - Browser: N/A

### Additional Details:
```
09:07:41.955 INFO [NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.json.gz
09:07:42.065 INFO [NistMirrorTask] Downloading...
09:07:42.267 INFO [NistMirrorTask] Uncompressing nvdcve-1.0-2014.json.gz
09:07:41.955 INFO [NistMirrorTask] Initiating download of https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.json.gz
09:07:42.599 INFO [NvdParser] Parsing nvdcve-1.0-2014.json
09:11:49.186 ERROR [NvdParser] An error occurred while parsing: cpe:2.3:a:disney:where\'s_my_perry?_free:1.5.1:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid product component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:230)
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:191)
	at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:55)
	at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23Uri(ModelConverter.java:34)
	at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23UriToVulnerableSoftware(ModelConverter.java:58)
	at org.dependencytrack.parser.nvd.NvdParser.generateVulnerableSoftware(NvdParser.java:275)
	at org.dependencytrack.parser.nvd.NvdParser.parseCpes(NvdParser.java:252)
	at org.dependencytrack.parser.nvd.NvdParser.lambda$parse$0(NvdParser.java:167)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at org.dependencytrack.parser.nvd.NvdParser.parse(NvdParser.java:71)
	at org.dependencytrack.tasks.NistMirrorTask.uncompress(NistMirrorTask.java:264)
	at org.dependencytrack.tasks.NistMirrorTask.doDownload(NistMirrorTask.java:203)
	at org.dependencytrack.tasks.NistMirrorTask.getAllFiles(NistMirrorTask.java:117)
	at org.dependencytrack.tasks.NistMirrorTask.inform(NistMirrorTask.java:96)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
09:11:49.275 ERROR [NvdParser] An error occurred while parsing: cpe:2.3:a:disney:where\'s_my_water?_free:1.9.1:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid product component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:230)
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:191)
	at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:55)
	at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23Uri(ModelConverter.java:34)
	at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23UriToVulnerableSoftware(ModelConverter.java:58)
	at org.dependencytrack.parser.nvd.NvdParser.generateVulnerableSoftware(NvdParser.java:275)
	at org.dependencytrack.parser.nvd.NvdParser.parseCpes(NvdParser.java:252)
	at org.dependencytrack.parser.nvd.NvdParser.lambda$parse$0(NvdParser.java:167)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at org.dependencytrack.parser.nvd.NvdParser.parse(NvdParser.java:71)
	at org.dependencytrack.tasks.NistMirrorTask.uncompress(NistMirrorTask.java:264)
	at org.dependencytrack.tasks.NistMirrorTask.doDownload(NistMirrorTask.java:203)
	at org.dependencytrack.tasks.NistMirrorTask.getAllFiles(NistMirrorTask.java:117)
	at org.dependencytrack.tasks.NistMirrorTask.inform(NistMirrorTask.java:96)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
09:12:13.779 ERROR [NvdParser] An error occurred while parsing: cpe:2.3:a:gratta_\&_vinci?_project:gratta_\&_vinci?:0.21.13167.93474:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid vendor component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:230)
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:191)
	at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:55)
	at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23Uri(ModelConverter.java:34)
	at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23UriToVulnerableSoftware(ModelConverter.java:58)
	at org.dependencytrack.parser.nvd.NvdParser.generateVulnerableSoftware(NvdParser.java:275)
	at org.dependencytrack.parser.nvd.NvdParser.parseCpes(NvdParser.java:252)
	at org.dependencytrack.parser.nvd.NvdParser.lambda$parse$0(NvdParser.java:167)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at org.dependencytrack.parser.nvd.NvdParser.parse(NvdParser.java:71)
	at org.dependencytrack.tasks.NistMirrorTask.uncompress(NistMirrorTask.java:264)
	at org.dependencytrack.tasks.NistMirrorTask.doDownload(NistMirrorTask.java:203)
	at org.dependencytrack.tasks.NistMirrorTask.getAllFiles(NistMirrorTask.java:117)
	at org.dependencytrack.tasks.NistMirrorTask.inform(NistMirrorTask.java:96)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
09:13:15.388 ERROR [NvdParser] An error occurred while parsing: cpe:2.3:a:whoisit:who-is-it?_lite_name_caller_time_limited_free:1:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid product component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:230)
	at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:191)
	at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:55)
	at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23Uri(ModelConverter.java:34)
	at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23UriToVulnerableSoftware(ModelConverter.java:58)
	at org.dependencytrack.parser.nvd.NvdParser.generateVulnerableSoftware(NvdParser.java:275)
	at org.dependencytrack.parser.nvd.NvdParser.parseCpes(NvdParser.java:252)
	at org.dependencytrack.parser.nvd.NvdParser.lambda$parse$0(NvdParser.java:167)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467)
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:650)
	at org.dependencytrack.parser.nvd.NvdParser.parse(NvdParser.java:71)
	at org.dependencytrack.tasks.NistMirrorTask.uncompress(NistMirrorTask.java:264)
	at org.dependencytrack.tasks.NistMirrorTask.doDownload(NistMirrorTask.java:203)
	at org.dependencytrack.tasks.NistMirrorTask.getAllFiles(NistMirrorTask.java:117)
	at org.dependencytrack.tasks.NistMirrorTask.inform(NistMirrorTask.java:96)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by stevespringett** [comment]
The NVD contains CPEs that do not conform to the spec. This is not a defect.  There is a lenient mode to the CPE parser. I can try to use that, which may eliminate the errors. But the errors are accurate. If memory serves, there are three CPEs in the NVD with this problem - all in 2014.

**Comment by relnah** [comment]
Looked up one example from the log. In ver 2.2 there are no ? but in 2.3 there is. Should this be reported somewhere else?

**Comment by stevespringett** [comment]
Jeremy Long (of Dependency-Check fame) is the person who created the most recent version of the CPE Parser and ran into several occurrences where the NVD is using invalid CPEs. A Lenient mode was created for this purpose. This may work, I have not tried. However, it would also be necessary for the CPEs in lenient mode to validate against input validation regex in the object model. This regex is provided by the NVD.

https://github.com/DependencyTrack/dependency-track/blob/1917d554979689db785c52dd7e8bda9f8ad7fe7f/src/main/java/org/dependencytrack/model/Component.java#L170

https://csrc.nist.gov/schema/cpe/2.3/cpe-naming_2.3.xsd

If lenient mode works and the resulting CPE validates against this regex, then it would be safe to simply use the CPE in lenient mode and close the issue. If it doesn't work, then the only way forward is to have the NVD correct the invalid CPEs. 

BTW, there are many more invalid CPEs in VulnDB if you opt to integrate it. The problem is not specific to the NVD data but misuse of the CPE specification in general.

**Comment by relnah** [comment]
Thanks for lots of good info. So in the case of breached spec why not just log a warn message and keep the part that says what was breached and not include the stacktrace? As you say, it is not an error in the sense that something broke in the code.

**Comment by stevespringett** [comment]
Thats a good suggestion. Done.
