### ISSUE TITLE
Upload cyclonedx-maven-plugin 1.5.0 BOM gives database unique constraint violation

### ISSUE THREAD

**Issue by msymons** [DependencyTrack/dependency-track#522]
### Current Behavior:
cyclonedx-maven-plugin 1.5.0 was released 20th Nov 2019.  I cannot find release notes but the new functionality of interest here is "Added initial support for dependency graphs and external references".

Uploading a BOM generated by plugin 1.5.0 gives a database unique constraint violation

### Steps to Reproduce:
* Create a project in DT and upload a CycloneDX 1.1 BOM generated using cyclonedx-maven-plugin 1.4.1  (this should succeed)
* Create a new version XXX for this project, checking all boxes (ie, include tags, properties, dependencies, audit history).
* Generate a new BOM for the project, but this time using cyclonedx-maven-plugin 1.5.0.  The BOM 
* Upload to DT project (version XXX).  There is no error... DT reports upload of BOM, etc.  Stats look fine after a couple of minutes.
* Examine `dependency-track.log` and observe database error and roll-back.  (see below for log).

I did then upload the same BOM to the same project/version and got no error this time.
I then created a brand new project/version and uploaded the same BOM.  Again, no error.

### Expected Behavior:
Not quite sure - valid but unsupported elements in BOM caught and warned about before attempting to write to database?  Assuming that was the problem....

### Environment:
  
  - Dependency-Track Version:  3.6.0
  - Distribution: [ Executable WAR ]
  - BOM Format & Version: CycloneDX 1.1 generated by cyclonedx-maven-plugin 1.5.0
  - Database Server: [ PostgreSQL ]

### Additional Details:

Here is the error from `dependency-track.log`:
```
2019-11-20 11:58:23,463 [] INFO [org.dependencytrack.tasks.BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: ff2dfda9-abf2-496c-a35d-7796f657f2a1
2019-11-20 11:58:28,922 [] WARN [DataNucleus.Datastore.Persist] Insert of object "org.dependencytrack.model.Dependency@2cead6d1" using statement "INSERT INTO "DEPENDENCY" ("ADDED_BY","ADDED_ON","COMPONENT_ID","NOTES","PROJECT_ID") VALUES (?,?,?,?,?)" failed : ERROR: duplicate key value violates unique constraint "DEPENDENCY_COMPOSITE_IDX"
  Detail: Key ("PROJECT_ID", "COMPONENT_ID")=(343, 726) already exists.
2019-11-20 11:58:28,923 [] WARN [DataNucleus.General] ExecutionContext closed with active transaction, so rolling back the active transaction
2019-11-20 11:58:28,982 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
javax.jdo.JDODataStoreException: Insert of object "org.dependencytrack.model.Dependency@2cead6d1" using statement "INSERT INTO "DEPENDENCY" ("ADDED_BY","ADDED_ON","COMPONENT_ID","NOTES","PROJECT_ID") VALUES (?,?,?,?,?)" failed : ERROR: duplicate key value violates unique constraint "DEPENDENCY_COMPOSITE_IDX"
  Detail: Key ("PROJECT_ID", "COMPONENT_ID")=(343, 726) already exists.
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:542)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:717)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)
	at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:398)
	at org.dependencytrack.persistence.QueryManager.clone(QueryManager.java:442)
	at org.dependencytrack.tasks.CloneProjectTask.inform(CloneProjectTask.java:43)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "DEPENDENCY_COMPOSITE_IDX"
  Detail: Key ("PROJECT_ID", "COMPONENT_ID")=(343, 726) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:427)
	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:414)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4569)
	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4546)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2026)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1869)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1724)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
	... 8 common frames omitted
```

**Comment by stevespringett** [comment]
is this still an issue?

**Comment by nscuro** [comment]
This was raised for DT 3.x, which had a different data model that made it more likely for these types of constraint violations to happen. I'm assuming this is no longer an issue. If it is, please open a new issue.
