### ISSUE TITLE
An error "An error occurred while parsing" occurs when Parsing nvdcve-1.0-2014.json

### ISSUE THREAD

**Issue by nibiwodong** [DependencyTrack/dependency-track#538]
When I start docker container, the docker log show errors as follows.
`04:09:22.298 INFO [NistMirrorTask] Uncompressing nvdcve-1.0-2014.json.gz
04:09:22.725 INFO [NvdParser] Parsing nvdcve-1.0-2014.json
04:09:24.716 ERROR [NvdParser] An error occurred while parsing: cpe:2.3:a:gratta_\&_vinci?_project:gratta_\&_vinci?:0.21.13167.93474:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid vendor component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string
        at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:230)
        at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:191)
        at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:55)
        at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23Uri(ModelConverter.java:34)
        at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23UriToVulnerableSoftware(ModelConverter.java:58)
        at org.dependencytrack.parser.nvd.NvdParser.generateVulnerableSoftware(NvdParser.java:275)
        at org.dependencytrack.parser.nvd.NvdParser.parseCpes(NvdParser.java:252)
        at org.dependencytrack.parser.nvd.NvdParser.lambda$parse$0(NvdParser.java:167)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
04:09:26.557 ERROR [NvdParser] An error occurred while parsing: cpe:2.3:a:disney:where\'s_my_perry?_free:1.5.1:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid product component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string
        at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:230)
        at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:191)
        at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:55)
        at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23Uri(ModelConverter.java:34)
        at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23UriToVulnerableSoftware(ModelConverter.java:58)
        at org.dependencytrack.parser.nvd.NvdParser.generateVulnerableSoftware(NvdParser.java:275)
        at org.dependencytrack.parser.nvd.NvdParser.parseCpes(NvdParser.java:252)
        at org.dependencytrack.parser.nvd.NvdParser.lambda$parse$0(NvdParser.java:167)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
04:09:26.561 ERROR [NvdParser] An error occurred while parsing: cpe:2.3:a:disney:where\'s_my_water?_free:1.9.1:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid product component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string
        at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:230)
        at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:191)
        at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:55)
        at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23Uri(ModelConverter.java:34)
        at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23UriToVulnerableSoftware(ModelConverter.java:58)
        at org.dependencytrack.parser.nvd.NvdParser.generateVulnerableSoftware(NvdParser.java:275)
        at org.dependencytrack.parser.nvd.NvdParser.parseCpes(NvdParser.java:252)
        at org.dependencytrack.parser.nvd.NvdParser.lambda$parse$0(NvdParser.java:167)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
04:09:27.549 ERROR [NvdParser] An error occurred while parsing: cpe:2.3:a:whoisit:who-is-it?_lite_name_caller_time_limited_free:1:*:*:*:*:android:*:*
us.springett.parsers.cpe.exceptions.CpeParsingException: Invalid product component: CPE Strings may not contain unquoted question marks except at the beginning or end of the string
        at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:230)
        at us.springett.parsers.cpe.CpeParser.parse23(CpeParser.java:191)
        at us.springett.parsers.cpe.CpeParser.parse(CpeParser.java:55)
        at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23Uri(ModelConverter.java:34)
        at org.dependencytrack.parser.nvd.ModelConverter.convertCpe23UriToVulnerableSoftware(ModelConverter.java:58)
        at org.dependencytrack.parser.nvd.NvdParser.generateVulnerableSoftware(NvdParser.java:275)
        at org.dependencytrack.parser.nvd.NvdParser.parseCpes(NvdParser.java:252)
        at org.dependencytrack.parser.nvd.NvdParser.lambda$parse$0(NvdParser.java:167)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

When I upload bom.xml, dependency-track can show the components, but there is no vuls.
However, the log shows internal analysis complete.
`11:07:21.874 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: d872f7d1-89a4-40bc-a959-4cf34852e2e1
11:07:25.142 INFO [BomUploadProcessingTask] Processed 251 components uploaded to project d872f7d1-89a4-40bc-a959-4cf34852e2e1
11:07:25.195 INFO [InternalAnalysisTask] Starting internal analysis task
11:07:25.195 WARN [VulnDbAnalysisTask] An OAuth 1.0a consumer key has not been specified for use with VulnDB. Skipping
11:07:25.195 WARN [OssIndexAnalysisTask] An API username has not been specified for use with OSS Index. Skipping
11:07:25.196 INFO [InternalAnalysisTask] Internal analysis complete
11:07:25.197 INFO [MetricsUpdateTask] Executing metrics update for project: d872f7d1-89a4-40bc-a959-4cf34852e2e1
11:07:25.197 INFO [MetricsUpdateTask] Executing metrics update for project: d872f7d1-89a4-40bc-a959-4cf34852e2e1
11:07:25.197 INFO [MetricsUpdateTask] Executing metrics update for project: d872f7d1-89a4-40bc-a959-4cf34852e2e1
11:07:26.140 INFO [MetricsUpdateTask] Completed metrics update for project: d872f7d1-89a4-40bc-a959-4cf34852e2e1
11:07:26.140 INFO [MetricsUpdateTask] Completed metrics update for project: d872f7d1-89a4-40bc-a959-4cf34852e2e1
11:07:26.148 INFO [MetricsUpdateTask] Completed metrics update for project: d872f7d1-89a4-40bc-a959-4cf34852e2e1`

**Comment by stevespringett** [comment]
Duplicate of #468
