### ISSUE TITLE
DependencyTrack&Fortify SSC(SSL) communication

### ISSUE THREAD

**Issue by aykutaricioglu** [DependencyTrack/dependency-track#589]
Hello, 

Fortify SSC is working SSL. DependencyTrack is working SSL too. I want to upload DependencyTrack results to Fortify SSC. I imported Fortify SSC certificate to DependencyTrack machine JDK and JRE cacerts (keystore). But DependencyTrack gives the following error.  Where should I import the Fortify SSC certificate?

`ERROR [org.dependencytrack.integrations.fortifyssc.FortifySscUploader] An error occurred attempting to upload findings to Fortify Software Security Center

kong.unirest.UnirestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

                at kong.unirest.apache.ApacheClient.request(ApacheClient.java:133)

                at kong.unirest.BaseRequest.asJson(BaseRequest.java:213)

                at org.dependencytrack.integrations.fortifyssc.FortifySscClient.generateOneTimeUploadToken(FortifySscClient.java:52)

                at org.dependencytrack.integrations.fortifyssc.FortifySscUploader.upload(FortifySscUploader.java:82)

                at org.dependencytrack.tasks.VulnerabilityManagementUploadTask.processProjectFindings(VulnerabilityManagementUploadTask.java:65)

                at org.dependencytrack.tasks.VulnerabilityManagementUploadTask.inform(VulnerabilityManagementUploadTask.java:45)

                at org.dependencytrack.tasks.FortifySscUploadTask.inform(FortifySscUploadTask.java:37)

                at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)

                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

                at java.lang.Thread.run(Unknown Source)

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

                at sun.security.ssl.Alerts.getSSLException(Unknown Source)

                at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)

                at sun.security.ssl.Handshaker.fatalSE(Unknown Source)

                at sun.security.ssl.Handshaker.fatalSE(Unknown Source)

                at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)

                at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)

                at sun.security.ssl.Handshaker.processLoop(Unknown Source)

                at sun.security.ssl.Handshaker.process_record(Unknown Source)

                at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)

                at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)

                at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)

                at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)

                at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)

                at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:191)

                at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.upgrade(PoolingHttpClientConnectionManager.java:390)

                at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:428)

                at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)

                at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)

                at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

                at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

                at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

                at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)

                at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

                at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)

                at kong.unirest.apache.ApacheClient.request(ApacheClient.java:125)

                ... 10 common frames omitted

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

                at sun.security.validator.PKIXValidator.doBuild(Unknown Source)

                at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)

                at sun.security.validator.Validator.validate(Unknown Source)

                at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)

                at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)

                at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)

                ... 31 common frames omitted

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

                at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)

                at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)

                at java.security.cert.CertPathBuilder.build(Unknown Source)

                ... 37 common frames omitted`

**Comment by stevespringett** [comment]
This is a common issue with self-signed certificates, including certificates issued from an organizational (non-trusted) CA. If you have an organizational CA, they typically provide cacerts for Java. If not, then you'll need to acquire and import it youself.

The cert needs to be imported into the cacerts truststore on the Dependency-Track server.

Refer to:
https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html

For example:
```
keytool -import -trustcacerts -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -alias FortifySSC -import -file Trustedcaroot.txt
```

I cannot provide additional support for this as it doesn't have any relation to Dependency-Track itself.
