### ISSUE TITLE
Exceptions in Log during runtime

### ISSUE THREAD

**Issue by Vamv** [DependencyTrack/dependency-track#595]
I'm running Dependency-Track on Tomcat with a Postgresql database.

Every now and then the dependency-track.log gets flooded by exceptions. They occur seemingly randomly. Is there any way to find out what's causing them?

Here is one of the exception messages from the log file:

[] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.nio.channels.OverlappingFileLockException: null
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
        at org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:126)
        at org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:41)
        at org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:45)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:728)
        at org.dependencytrack.search.IndexManager.openIndex(IndexManager.java:144)
        at org.dependencytrack.search.IndexManager.getIndexWriter(IndexManager.java:155)
        at org.dependencytrack.search.VulnerabilityIndexer.add(VulnerabilityIndexer.java:76)
        at org.dependencytrack.search.VulnerabilityIndexer.add(VulnerabilityIndexer.java:42)
        at org.dependencytrack.tasks.IndexTask.inform(IndexTask.java:49)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Vamv** [comment]
It seems dependency-track crashed some time back and restarted automatically.

This caused some write.lock files to be left over. After deleting those, everything works normally again.
