### ISSUE TITLE
An error occurred while retrieving findings

### ISSUE THREAD

**Issue by marioja** [DependencyTrack/dependency-track#615]
When I run the Publish BOM to Dependency-Track post build action on a freestyle Jenkins project  or I add a Jenkins dependencyTrackPublisher step in the Jenkinsfile I get the same error.  Below you will find the Multibranch Pipeline output.
### Current Behavior:
```
[DependencyTrack] Publishing artifact to Dependency-Track - http://computer.example.com:8080
[DependencyTrack] The artifact was successfully published
[DependencyTrack] Polling Dependency-Track for BOM processing status
[DependencyTrack] Looking up id of newly created project
[DependencyTrack] Processing findings

...more pipeline stuff...

org.jenkinsci.plugins.DependencyTrack.ApiClientException: An error occurred while retrieving findings - HTTP response code: 403 Forbidden
	at org.jenkinsci.plugins.DependencyTrack.ApiClient.getFindings(ApiClient.java:96)
Caused: org.jenkinsci.plugins.DependencyTrack.ApiClientException: An error occurred while retrieving findings
	at org.jenkinsci.plugins.DependencyTrack.ApiClient.getFindings(ApiClient.java:99)
	at org.jenkinsci.plugins.DependencyTrack.DependencyTrackPublisher.perform(DependencyTrackPublisher.java:226)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1878)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:427)
```
### Steps to Reproduce:
* Configure Jenkins to use the OWAS Dependency-Track plugin v 2.2.1.
* Configure the plugin url to dependency-track and the api key for the automation team which has BOM_UPLOAD and VIEW_PORTFOLIO permissions.
* Configure either freestyle job or Jenkinsfile step to run the maven org.cyclonedx:cyclonedx-maven-plugin:1.6.4:makeAggregateBom target and publish the bom to dependency track
### Expected Behavior:
No errors
### Environment:
  
  - Dependency-Track Version: v3.7.1
  - Distribution: [ Docker | Executable WAR | Traditional WAR ] docker
  - BOM Format & Version: CycloneDX
  - Database Server: [ H2 | MSSQL | MySQL | PostgreSQL ] H2
  - Browser: Microsoft Edge

### Additional Details:

This is my first ever attempt to use dependency track.  It has never worked before.

**Comment by stevespringett** [comment]
Please ensure the API key being used has the permissions listed in the docs
https://docs.dependencytrack.org/integrations/jenkins/

**Comment by marioja** [comment]
Thanks that solved it.  I had read elsewhere that only two permissions were required.  If I find the place I will report it so that it may be changed.
