### ISSUE TITLE
Slow LDAP causes LDAP: error code 3 - Timelimit Exceeded

### ISSUE THREAD

**Issue by marioja** [DependencyTrack/dependency-track#632]
The defect may already be reported! Please search for the defect before creating one.
When setting alpine.ldap.team.synchronization=true on our production environment with a large active directory and high load we get this error for the LdapSyncTask.

### Current Behavior:
```
javax.naming.TimeLimitExceededException: [LDAP: error code 3 - Timelimit Exceeded]
        at com.sun.jndi.ldap.LdapCtx.mapErrorCode(LdapCtx.java:3210)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3100)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2891)
        at com.sun.jndi.ldap.AbstractLdapNamingEnumeration.getNextBatch(AbstractLdapNamingEnumeration.java:148)
        at com.sun.jndi.ldap.AbstractLdapNamingEnumeration.hasMoreImpl(AbstractLdapNamingEnumeration.java:217)
        at com.sun.jndi.ldap.AbstractLdapNamingEnumeration.hasMore(AbstractLdapNamingEnumeration.java:189)
        at alpine.auth.LdapConnectionWrapper.hasMoreEnum(LdapConnectionWrapper.java:371)
        at alpine.auth.LdapConnectionWrapper.getGroups(LdapConnectionWrapper.java:145)
        at alpine.tasks.LdapSyncTask.sync(LdapSyncTask.java:99)
        at alpine.tasks.LdapSyncTask.inform(LdapSyncTask.java:63)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
21:07:51.750 INFO [LdapSyncTask] LDAP synchronization complete
```

### Steps to Reproduce:

Just start DT with team synchronization set to true and you may or may not get this.  If you get it, the users will not get their group membership upon logging on.
### Expected Behavior:

Team membership to be associated for LDAP users.
### Environment:
  
  - Dependency-Track Version: 3.8.0
  - Distribution: Docker
  - BOM Format & Version:
  - Database Server: H2
  - Browser: 

### Additional Details:

There is no indication in the UI that this error took place and there is no way other than restarting DT for this error to be corrected.  Is it possible for the timeout value to be configurable and is there a way that the UI be notified of the error and could re-initiate the LdapSyncTask?

**Comment by stevespringett** [comment]
If you have a large LDAP directory or under-performing LDAP servers, there isn't anything DT can do about it. User defined timeouts will not be implemented.

Your best best is to improve LDAP performance or to onboard LDAP users without team synchronization.

**Comment by marioja** [comment]
Upon further investigation, in line 142 of LdapConnectionWrapper you instantiates a SearchControls class with default constructor (time limit is set to 0 which means no time limit) and you do not change that value using the setTimeLimit method.  How is it possible to have a TimeLimitExceededException later during the NamingEnumeration hasMore() method?  I don't get it.
