### ISSUE TITLE
Error when parsing NPM advisories

### ISSUE THREAD

**Issue by savek-cc** [DependencyTrack/dependency-track#676]
> dtrack_1  | 09:42:38.787 INFO [NpmAdvisoryMirrorTask] Retrieving NPM advisories from https://registry.npmjs.org/-/npm/v1/security/advisories
> dtrack_1  | 09:42:39.718 INFO [NpmAdvisoryMirrorTask] Updating datasource with NPM advisories
> dtrack_1  | 09:42:39.732 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
> dtrack_1  | java.time.format.DateTimeParseException: Text '2020-04-14T21:44:49.82' could not be parsed at index 22
> dtrack_1  |     at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
> dtrack_1  |     at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
> dtrack_1  |     at java.time.OffsetDateTime.parse(OffsetDateTime.java:402)
> dtrack_1  |     at java.time.OffsetDateTime.parse(OffsetDateTime.java:387)
> dtrack_1  |     at org.dependencytrack.tasks.NpmAdvisoryMirrorTask.mapAdvisoryToVulnerability(NpmAdvisoryMirrorTask.java:163)
> dtrack_1  |     at org.dependencytrack.tasks.NpmAdvisoryMirrorTask.updateDatasource(NpmAdvisoryMirrorTask.java:143)
> dtrack_1  |     at org.dependencytrack.tasks.NpmAdvisoryMirrorTask.getAdvisories(NpmAdvisoryMirrorTask.java:104)
> dtrack_1  |     at org.dependencytrack.tasks.NpmAdvisoryMirrorTask.inform(NpmAdvisoryMirrorTask.java:68)
> dtrack_1  |     at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
> dtrack_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> dtrack_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> dtrack_1  |     at java.lang.Thread.run(Thread.java:748)

apparenty the format of the date field in the NPM advisories can not be parsed by the "OffsetDateTime.parse" function as it is an absolute date without any offset(?).

Environment is a freshly deployed current snapshot docker image.

**Comment by savek-cc** [comment]
This might be due to a change in the NPM advisory format - as a current (and previously working) 3.8.0 instance is also affected

**Comment by stevespringett** [comment]
Looks like NPM is no longer producing ISO date formats with offsets. DT is expecting ISO 8601 dates with offsets. NPM is no longer including the timezones so DT is failing.

**Comment by stevespringett** [comment]
I have code that fixes this issue (not yet checked in), however, it also looks like NPM is violating their API versioning policy. 

For example: 
https://registry.npmjs.org/-/npm/v1/security/advisories has a 'next' and 'prev' field so that you can paginate through the results. The links for next and prev are now incorrect and refer to URLs such as `/v1/advisories?perPage=20&page=1` which do not exist.

This will now produce a 405 preventing DT from mirroring NPM. I would think NPM would not change the behavior of /v1/ but apparently they have. Bad practice. :-(

I can fix this by obtaining the querystring from the next and prev fields and ignoring the rest. That would give me URLs such as `https://registry.npmjs.org/-/npm/v1/security/advisories?perPage=20&page=1` which do work, but that's a workaround at best. NPM needs to fix this.

I would recommend creating an issue with NPM to resolve.

**Comment by savek-cc** [comment]
I tried to find a documentation of the API - but was unable to do so (I'm more of an embedded C dev. So my knowledge of npm is rather non-existent)

**Comment by stevespringett** [comment]
I don't think the advisories API is heavily documented which may explain why they broke API compatibility, or at least did not test it, as it's not widely used.

**Comment by savek-cc** [comment]
reference: https://github.com/npm/cli/issues/1291

**Comment by savek-cc** [comment]
https://github.com/npm/cli/issues/1291#issuecomment-631081377 says the format is back to normal and directs towards the github security tracker; maybe worth looking into in the future.
