### ISSUE TITLE
What's the appropriate way to determine if an analysis is completed ?

### ISSUE THREAD

**Issue by nortondefeis** [DependencyTrack/dependency-track#726]
Hello,

I am using REST API _api/v1/finding/project/{uuid}/export_ to retrieve the FPF file containing the results/findings of an analysis. However, I've noticed that the JSON response does not let us know if the analysis is complete or not. For example, if the analysis is still running "findings" will bem empty ("findings":[]); and once it is completed it will contain the findings.

What's the appropriate way to determine if an analysis is completed ?

Thanks and best regards.

PS: I've tried to use notification via Outbound Webhook but it fails with the error below:

_14:38:01.859 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
kong.unirest.UnirestException: java.net.SocketTimeoutException: Read timed out
        at kong.unirest.apache.ApacheClient.request(ApacheClient.java:133)
        at kong.unirest.BaseRequest.asJson(BaseRequest.java:213)
        at org.dependencytrack.notification.publisher.AbstractWebhookPublisher.publish(AbstractWebhookPublisher.java:51)
        at org.dependencytrack.notification.publisher.WebhookPublisher.inform(WebhookPublisher.java:32)
        at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:63)
        at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:100)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at kong.unirest.apache.ApacheClient.request(ApacheClient.java:125)
        ... 8 common frames omitted_

**Comment by stevespringett** [comment]
Submitting a bom returns a UUID which can be tracked to determine if it is complete. Refer to the Swagger for info.

**Comment by nortondefeis** [comment]
Thank you very much, Steve !
