### ISSUE TITLE
Lucene error a Million times in dependency-track.log

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#747]
Hi, At one point I run Dependency-Track embedded and now I am running Dependency-Track as ROOT in Tomcat.  The problem is that I am seeing the following error a million times in ~/.dependency-track/dependency-track.log file.  What do I need to do to resolve the error. Do  I really need to go find the lucene-backward-codes.jar file from somewhere and put it somewhere?  is this a BUG?

java.lang.IllegalArgumentException: Could not load codec 'Lucene70'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:420)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:352)
        at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:289)
        at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:846)
        at org.dependencytrack.search.IndexManager.openIndex(IndexManager.java:144)
        at org.dependencytrack.search.IndexManager.getIndexWriter(IndexManager.java:155)
        at org.dependencytrack.search.VulnerabilityIndexer.remove(VulnerabilityIndexer.java:96)
        at org.dependencytrack.search.VulnerabilityIndexer.remove(VulnerabilityIndexer.java:42)
        at org.dependencytrack.tasks.IndexTask.inform(IndexTask.java:51)
        at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene70' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene84]
        at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116)
        at org.apache.lucene.codecs.Codec.forName(Codec.java:116)
        at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:416)
        ... 12 common frames omitted
2020-07-28 22:35:15,074 [] ERROR [alpine.event.framework.LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.IllegalArgumentException: Could not load codec 'Lucene70'.  Did you forget to add lucene-backward-codecs.jar?
        at org.apache.lucene.ind

**Comment by stevespringett** [comment]
Stop Dependency-Track, delete the ~/.dependency-track/index directory, and restart Dependency-Track.
