### ISSUE TITLE
Unable to load privious project data after reinstallation of jdk

### ISSUE THREAD

**Issue by anuragpathak2608** [DependencyTrack/dependency-track#774]
Hello,

This is not an issue but a question.
There was an issue in our environment and we are getting max heap exceeded error, to resolve that we have reinstalled the JDK.

After removing old JDK the heap issue got resolved but when we tried to restart the DT server all our previous data vanished and not showing a single project there.

How can we restore our previous data??
I can see there is a project and vulnerabilities directory in the ~ 

Thanks in advance
Anurag

**Comment by anuragpathak2608** [comment]
Getting below exception while launching the application:
06:36:33.190 ERROR [HikariPool] HikariPool-1 - Exception during pool initializat

ion.

org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.IllegalState

Exception: Chunk 6006836 not found [1.4.200/9]" [50000-200]

        at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)

        at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)

        at org.h2.message.DbException.get(DbException.java:194)

        at org.h2.message.DbException.convert(DbException.java:347)

        at org.h2.engine.Database.openDatabase(Database.java:333)

        at org.h2.engine.Database.<init>(Database.java:301)

        at org.h2.engine.Engine.openSession(Engine.java:74)

        at org.h2.engine.Engine.openSession(Engine.java:192)

        at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)

        at org.h2.engine.Engine.createSession(Engine.java:166)

        at org.h2.engine.Engine.createSession(Engine.java:29)

        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.jav

a:340)

        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)

        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)

        at org.h2.Driver.connect(Driver.java:69)

        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSourc

e.java:138)

        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)

        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)

        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473

)

        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)

        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)

        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)

        at org.datanucleus.store.rdbms.connectionpool.HikariCPConnectionPoolFact

ory.createConnectionPool(HikariCPConnectionPoolFactory.java:171)

        at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSource(

ConnectionFactoryImpl.java:259)

        at org.datanucleus.store.rdbms.ConnectionFactoryImpl.initialiseDataSourc

e(ConnectionFactoryImpl.java:127)

        at org.datanucleus.store.rdbms.ConnectionFactoryImpl.<init>(ConnectionFa

ctoryImpl.java:92)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

 

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct

orAccessorImpl.java:62)

        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC

onstructorAccessorImpl.java:45)

        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

        at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExten

sion(NonManagedPluginRegistry.java:651)

        at org.datanucleus.plugin.PluginManager.createExecutableExtension(Plugin

Manager.java:321)

        at org.datanucleus.store.connection.ConnectionManagerImpl.<init>(Connect

ionManagerImpl.java:98)

        at org.datanucleus.store.AbstractStoreManager.registerConnectionMgr(Abst

ractStoreManager.java:167)

        at org.datanucleus.store.AbstractStoreManager.<init>(AbstractStoreManage

r.java:149)

        at org.datanucleus.store.rdbms.RDBMSStoreManager.<init>(RDBMSStoreManage

r.java:278)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

 

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct

orAccessorImpl.java:62)

        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC

onstructorAccessorImpl.java:45)

        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

        at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExten

sion(NonManagedPluginRegistry.java:651)

        at org.datanucleus.plugin.PluginManager.createExecutableExtension(Plugin

Manager.java:295)

        at org.datanucleus.NucleusContextHelper.createStoreManagerForProperties(

NucleusContextHelper.java:140)

        at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceN

ucleusContextImpl.java:445)

        at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfigurat

ion(JDOPersistenceManagerFactory.java:859)

        at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenc

eManagerFactory(JDOPersistenceManagerFactory.java:346)

        at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceMa

nagerFactory(JDOPersistenceManagerFactory.java:279)

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.

java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces

sorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at javax.jdo.JDOHelper$16.run(JDOHelper.java:1975)

        at java.security.AccessController.doPrivileged(Native Method)

        at javax.jdo.JDOHelper.invoke(JDOHelper.java:1970)

        at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementatio

n(JDOHelper.java:1139)

        at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:851)

        at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:1109)

 

        at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:969)

        at org.dependencytrack.upgrade.UpgradeInitializer.contextInitialized(Upg

radeInitializer.java:56)

        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialize

d(ContextHandler.java:933)

        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialize

d(ServletContextHandler.java:553)

        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextH

andler.java:892)

        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletC

ontextHandler.java:356)

        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java

:1445)

        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.jav

a:1409)

        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandle

r.java:825)

        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContex

tHandler.java:275)

        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524

)

        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife

Cycle.java:72)

        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLi

feCycle.java:169)

        at org.eclipse.jetty.server.Server.start(Server.java:407)

        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(Container

LifeCycle.java:110)

        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHand

ler.java:97)

        at org.eclipse.jetty.server.Server.doStart(Server.java:371)

        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife

Cycle.java:72)

        at alpine.embedded.EmbeddedJettyServer.main(EmbeddedJettyServer.java:93)

 

Caused by: java.lang.IllegalStateException: Chunk 6006836 not found [1.4.200/9]

        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:950)

 

        at org.h2.mvstore.MVStore.getChunk(MVStore.java:1230)

        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1214)

        at org.h2.mvstore.MVStore.readPage(MVStore.java:2209)

        at org.h2.mvstore.MVMap.readPage(MVMap.java:672)

        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)

        at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)

        at org.h2.mvstore.MVMap$2$1.hasNext(MVMap.java:802)

        at org.h2.mvstore.db.LobStorageMap.init(LobStorageMap.java:109)

        at org.h2.engine.Database.open(Database.java:791)

        at org.h2.engine.Database.openDatabase(Database.java:307)

        ... 71 common frames omitted

06:36:33.299 ERROR [Datastore] Exception thrown creating StoreManager : Chunk 60

06836 not found [1.4.200/9]
Any idea why it is throwing this ??

**Comment by stevespringett** [comment]
No idea. Keep in mind that this project is not capable of supporting the traditional or executable war in deployed environments. There's simply too many variables that impact execution. At this time, Docker is the only deliverable that's supportable due to greatly improved consistency of execution.

**Comment by anuragpathak2608** [comment]
Thanks Steve for your quick replies.
We will be moving towards docker deployment.

**Comment by stevespringett** [comment]
Downloads for tradition and executable war combined account for 2.3% of all downloads. The other 97.7% is Docker. There will come a time when only Docker images are available.
