### ISSUE TITLE
DT on Tomcat never actually yields any results

### ISSUE THREAD

**Issue by jrobertsz366** [DependencyTrack/dependency-track#779]
### Environment:
  
  - Dependency-Track Version: 3.8
  - Distribution: [Traditional WAR]
  - BOM Format & Version:
  - Database Server: [ Using the default - I did not create one]
  - Browser:  Chrome

### Additional Details:
Tomcat 8.5.57 and Java 1.8.0_251-b08 

DT starts on tomcat but there are errors in the logs and importing a bom file never yields any findings even though I know there are some as the same steps via the executable WAR yield findings. I have tried this on 3 servers with Tomcat 8.5.57 and Java 1.8.0_251-b08 and get the same following errors in catalina.log file:

catalina.2020-09-15.log:15-Sep-2020 08:06:11.895 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [MVStore background writer nio:C:/Users/SVC-pspccybsec/.dependency-track/db.mv.db] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
sun.nio.ch.FileDispatcherImpl.pread(Unknown Source)
sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
sun.nio.ch.IOUtil.read(Unknown Source)
sun.nio.ch.FileChannelImpl.readInternal(Unknown Source)
sun.nio.ch.FileChannelImpl.read(Unknown Source)
org.h2.store.fs.FileNio.read(FilePathNio.java:74)
org.h2.mvstore.DataUtils.readFully(DataUtils.java:442)
org.h2.mvstore.FileStore.readFully(FileStore.java:98)
org.h2.mvstore.Chunk.readBufferForPage(Chunk.java:361)
org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1214)
org.h2.mvstore.MVStore.readPage(MVStore.java:2209)
org.h2.mvstore.MVMap.readPage(MVMap.java:672)
org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1043)
org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
org.h2.mvstore.MVMap.rewrite(MVMap.java:748)
org.h2.mvstore.MVMap.rewrite(MVMap.java:710)
org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2137)
org.h2.mvstore.MVStore.rewriteChunks(MVStore.java:2026)
org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2802)
org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3290)

5-Sep-2020 18:30:50.050 WARNING [http-nio-8080-exec-8] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
15-Sep-2020 18:30:50.065 WARNING [http-nio-8080-exec-8] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [Thread-24] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
java.util.concurrent.ArrayBlockingQueue.poll(Unknown Source)
org.dependencytrack.common.HttpClientPool$IdleConnectionMonitor.run(HttpClientPool.java:90)
java.lang.Thread.run(Unknown Source)
15-Sep-2020 18:30:53.066 INFO [http-nio-8080-exec-8] org.apache.catalina.startup.HostConfig.undeploy Undeploying context []

I also get this exception in localhost.log file:

15-Sep-2020 08:06:11.723 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [alpine.persistence.PersistenceManagerFactory]
	javax.jdo.JDOFatalUserException: A property named javax.jdo.PersistenceManagerFactoryClass must be specified, or a jar file with a META-INF/services/javax.jdo.PersistenceManagerFactory entry must be in the classpath, or a property named javax.jdo.option.PersistenceUnitName must be specified.
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:870)
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:1109)
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:969)
		at alpine.persistence.PersistenceManagerFactory.contextInitialized(PersistenceManagerFactory.java:57)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
NestedThrowablesStackTrace:
	javax.jdo.JDOFatalInternalException: Error creating transactional connection factory
		at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:670)
		at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:872)
		at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:346)
		at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:279)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at javax.jdo.JDOHelper$16.run(JDOHelper.java:1975)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.jdo.JDOHelper.invoke(JDOHelper.java:1970)
		at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1139)
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:851)
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:1109)
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:969)
		at alpine.persistence.PersistenceManagerFactory.contextInitialized(PersistenceManagerFactory.java:57)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
NestedThrowablesStackTrace:
	java.lang.reflect.InvocationTargetException
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
		at java.lang.reflect.Constructor.newInstance(Unknown Source)
		at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:651)
		at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:321)
		at org.datanucleus.store.connection.ConnectionManagerImpl.<init>(ConnectionManagerImpl.java:98)
		at org.datanucleus.store.AbstractStoreManager.registerConnectionMgr(AbstractStoreManager.java:167)
		at org.datanucleus.store.AbstractStoreManager.<init>(AbstractStoreManager.java:149)
		at org.datanucleus.store.rdbms.RDBMSStoreManager.<init>(RDBMSStoreManager.java:278)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
		at java.lang.reflect.Constructor.newInstance(Unknown Source)
		at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:651)
		at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:295)
		at org.datanucleus.NucleusContextHelper.createStoreManagerForProperties(NucleusContextHelper.java:140)
		at org.datanucleus.PersistenceNucleusContextImpl.initialise(PersistenceNucleusContextImpl.java:445)
		at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.freezeConfiguration(JDOPersistenceManagerFactory.java:859)
		at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.createPersistenceManagerFactory(JDOPersistenceManagerFactory.java:346)
		at org.datanucleus.api.jdo.JDOPersistenceManagerFactory.getPersistenceManagerFactory(JDOPersistenceManagerFactory.java:279)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at javax.jdo.JDOHelper$16.run(JDOHelper.java:1975)
		at java.security.AccessController.doPrivileged(Native Method)
		at javax.jdo.JDOHelper.invoke(JDOHelper.java:1970)
		at javax.jdo.JDOHelper.invokeGetPersistenceManagerFactoryOnImplementation(JDOHelper.java:1139)
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:851)
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:1109)
		at javax.jdo.JDOHelper.getPersistenceManagerFactory(JDOHelper.java:969)
		at alpine.persistence.PersistenceManagerFactory.contextInitialized(PersistenceManagerFactory.java:57)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
	Caused by: org.datanucleus.exceptions.NucleusException: Attempt to invoke the "HikariCP" plugin to create a ConnectionPool gave an error : Failed to initialize pool: Database may be already in use: "Waited for database closing longer than 1 minute". Possible solutions: close all other connection(s); use the server mode [90020-200]
		at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSource(ConnectionFactoryImpl.java:278)
		at org.datanucleus.store.rdbms.ConnectionFactoryImpl.initialiseDataSource(ConnectionFactoryImpl.java:127)
		at org.datanucleus.store.rdbms.ConnectionFactoryImpl.<init>(ConnectionFactoryImpl.java:92)
		... 46 more
	Caused by: com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Database may be already in use: "Waited for database closing longer than 1 minute". Possible solutions: close all other connection(s); use the server mode [90020-200]
		at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
		at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
		at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
		at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
		at org.datanucleus.store.rdbms.connectionpool.HikariCPConnectionPoolFactory.createConnectionPool(HikariCPConnectionPoolFactory.java:171)
		at org.datanucleus.store.rdbms.ConnectionFactoryImpl.generateDataSource(ConnectionFactoryImpl.java:259)
		... 48 more
	Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: "Waited for database closing longer than 1 minute". Possible solutions: close all other connection(s); use the server mode [90020-200]
		at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
		at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
		at org.h2.message.DbException.get(DbException.java:205)
		at org.h2.message.DbException.get(DbException.java:181)
		at org.h2.engine.Engine.openSession(Engine.java:200)
		at org.h2.engine.Engine.createSessionAndValidate(Engine.java:171)
		at org.h2.engine.Engine.createSession(Engine.java:166)
		at org.h2.engine.Engine.createSession(Engine.java:29)
		at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:340)
		at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:173)
		at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
		at org.h2.Driver.connect(Driver.java:69)
		at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
		at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
		at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
		at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
		at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
		... 52 more
15-Sep-2020 08:06:11.770 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.dependencytrack.event.EventSubsystemInitializer]
	java.lang.ExceptionInInitializerError
		at org.dependencytrack.event.EventSubsystemInitializer.contextInitialized(EventSubsystemInitializer.java:94)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
	Caused by: java.lang.IllegalStateException: Context is not initialized yet.
		at alpine.persistence.PersistenceManagerFactory.createPersistenceManager(PersistenceManagerFactory.java:82)
		at alpine.persistence.AbstractAlpineQueryManager.<init>(AbstractAlpineQueryManager.java:76)
		at alpine.persistence.AlpineQueryManager.<init>(AlpineQueryManager.java:61)
		at org.dependencytrack.persistence.QueryManager.<init>(QueryManager.java:90)
		at org.dependencytrack.tasks.TaskScheduler.scheduleConfigurableTask(TaskScheduler.java:98)
		at org.dependencytrack.tasks.TaskScheduler.<init>(TaskScheduler.java:84)
		at org.dependencytrack.tasks.TaskScheduler.<clinit>(TaskScheduler.java:49)
		... 14 more
15-Sep-2020 08:06:11.817 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class [org.dependencytrack.persistence.DefaultObjectGenerator]
	java.lang.IllegalStateException: Context is not initialized yet.
		at alpine.persistence.PersistenceManagerFactory.createPersistenceManager(PersistenceManagerFactory.java:82)
		at alpine.persistence.AbstractAlpineQueryManager.<init>(AbstractAlpineQueryManager.java:76)
		at alpine.persistence.AlpineQueryManager.<init>(AlpineQueryManager.java:61)
		at org.dependencytrack.persistence.QueryManager.<init>(QueryManager.java:90)
		at org.dependencytrack.persistence.DefaultObjectGenerator.loadDefaultPermissions(DefaultObjectGenerator.java:137)
		at org.dependencytrack.persistence.DefaultObjectGenerator.contextInitialized(DefaultObjectGenerator.java:88)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
15-Sep-2020 08:06:11.895 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class [org.dependencytrack.event.EventSubsystemInitializer]
	java.lang.NoClassDefFoundError: Could not initialize class org.dependencytrack.tasks.TaskScheduler
		at org.dependencytrack.event.EventSubsystemInitializer.contextDestroyed(EventSubsystemInitializer.java:103)
		at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4735)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5399)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
15-Sep-2020 08:06:11.895 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStop Exception sending context destroyed event to listener instance of class [alpine.persistence.PersistenceManagerFactory]
	java.lang.NullPointerException
		at alpine.persistence.PersistenceManagerFactory.contextDestroyed(PersistenceManagerFactory.java:70)
		at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4735)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5399)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)

**Comment by stevespringett** [comment]
Looks like Windows has a lock on the file. Consult your sysadmin to find out what Windows process has a lock on the file. This is common with Windows servers that have anti-virus/malware installed or have services that index the filesystem. Some endpoint protections can also cause these issues.

Also, absolutely no testing has ever been performed on Windows. There are likely some issues on Windows which will not be fixed.

**Comment by jrobertsz366** [comment]
OK - switching to DT embedded as I've had success with it.
