### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "VULNERABILITY"

### ISSUE THREAD

**Issue by rvsoni** [DependencyTrack/dependency-track#830]
Error logs on server.log

```
2020-11-11 11:29:49,044 [] WARN [org.eclipse.jetty.server.HttpChannel] /api/v1/finding/project/2c3f276d-7388-4761-a727-9b8d68b2e8bf
javax.servlet.ServletException: javax.jdo.JDODataStoreException: Error executing SQL query "SELECT "COMPONENT"."UUID" AS "COMPONENT_UUID", "COMPONENT"."NAME" AS "COMPONENT_NAME", "COMPONENT"."GROUP" AS "COMPONENT_GROUP", "COMPONENT"."VERSION" AS "COMPONENT_VERSION", "COMPONENT"."PURL" AS "COMPONENT_PURL", "VULNERABILITY"."UUID" AS "VULN_UUID", "VULNERABILITY"."SOURCE" AS "VULN_SOURCE", "VULNERABILITY"."VULNID" AS "VULN_ID", "VULNERABILITY"."TITLE" AS "VULN_TITLE", "VULNERABILITY"."SUBTITLE" AS "VULN_SUBTITLE", "VULNERABILITY"."DESCRIPTION" AS "VULN_DESCRIPTION", "VULNERABILITY"."RECOMMENDATION" AS "VULN_RECOMMENDATION", "VULNERABILITY"."SEVERITY" AS "VULN_SEVERITY", "VULNERABILITY"."CVSSV2BASESCORE" AS "VULN_CVSSV2BASESCORE", "VULNERABILITY"."CVSSV3BASESCORE" AS "VULN_CVSSV3BASESCORE", "FINDINGATTRIBUTION"."ANALYZERIDENTITY" AS "FINDINGATTRIBUTION_ANALYZERIDENTITY", "FINDINGATTRIBUTION"."ATTRIBUTED_ON" AS "FINDINGATTRIBUTION_ATTRIBUTED_ON", "CWE"."CWEID" AS "CWE_ID", "CWE"."NAME" AS "CWE_NAME", "ANALYSIS"."STATE" AS "ANALYSIS_STATE", "ANALYSIS"."SUPPRESSED" AS "ANALYSIS_SUPPRESSED" FROM "COMPONENT" INNER JOIN "FINDINGATTRIBUTION" ON ("COMPONENT"."ID" = "FINDINGATTRIBUTION"."COMPONENT_ID") AND ("VULNERABILITY"."ID" = "FINDINGATTRIBUTION"."VULNERABILITY_ID")INNER JOIN "COMPONENTS_VULNERABILITIES" ON ("COMPONENT"."ID" = "COMPONENTS_VULNERABILITIES"."COMPONENT_ID") INNER JOIN "VULNERABILITY" ON ("COMPONENTS_VULNERABILITIES"."VULNERABILITY_ID" = "VULNERABILITY"."ID") LEFT JOIN "CWE"  ON ("VULNERABILITY"."CWE" = "CWE"."ID") LEFT JOIN "ANALYSIS" ON ("COMPONENT"."ID" = "ANALYSIS"."COMPONENT_ID") AND ("VULNERABILITY"."ID" = "ANALYSIS"."VULNERABILITY_ID") AND ("COMPONENT"."PROJECT_ID" = "ANALYSIS"."PROJECT_ID") WHERE "COMPONENT"."PROJECT_ID" = ?".
NestedThrowables:
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "VULNERABILITY"
  Position: 1122
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:408)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1395)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at alpine.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:224)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at alpine.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:92)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at alpine.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:149)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.jdo.JDODataStoreException: Error executing SQL query "SELECT "COMPONENT"."UUID" AS "COMPONENT_UUID", "COMPONENT"."NAME" AS "COMPONENT_NAME", "COMPONENT"."GROUP" AS "COMPONENT_GROUP", "COMPONENT"."VERSION" AS "COMPONENT_VERSION", "COMPONENT"."PURL" AS "COMPONENT_PURL", "VULNERABILITY"."UUID" AS "VULN_UUID", "VULNERABILITY"."SOURCE" AS "VULN_SOURCE", "VULNERABILITY"."VULNID" AS "VULN_ID", "VULNERABILITY"."TITLE" AS "VULN_TITLE", "VULNERABILITY"."SUBTITLE" AS "VULN_SUBTITLE", "VULNERABILITY"."DESCRIPTION" AS "VULN_DESCRIPTION", "VULNERABILITY"."RECOMMENDATION" AS "VULN_RECOMMENDATION", "VULNERABILITY"."SEVERITY" AS "VULN_SEVERITY", "VULNERABILITY"."CVSSV2BASESCORE" AS "VULN_CVSSV2BASESCORE", "VULNERABILITY"."CVSSV3BASESCORE" AS "VULN_CVSSV3BASESCORE", "FINDINGATTRIBUTION"."ANALYZERIDENTITY" AS "FINDINGATTRIBUTION_ANALYZERIDENTITY", "FINDINGATTRIBUTION"."ATTRIBUTED_ON" AS "FINDINGATTRIBUTION_ATTRIBUTED_ON", "CWE"."CWEID" AS "CWE_ID", "CWE"."NAME" AS "CWE_NAME", "ANALYSIS"."STATE" AS "ANALYSIS_STATE", "ANALYSIS"."SUPPRESSED" AS "ANALYSIS_SUPPRESSED" FROM "COMPONENT" INNER JOIN "FINDINGATTRIBUTION" ON ("COMPONENT"."ID" = "FINDINGATTRIBUTION"."COMPONENT_ID") AND ("VULNERABILITY"."ID" = "FINDINGATTRIBUTION"."VULNERABILITY_ID")INNER JOIN "COMPONENTS_VULNERABILITIES" ON ("COMPONENT"."ID" = "COMPONENTS_VULNERABILITIES"."COMPONENT_ID") INNER JOIN "VULNERABILITY" ON ("COMPONENTS_VULNERABILITIES"."VULNERABILITY_ID" = "VULNERABILITY"."ID") LEFT JOIN "CWE"  ON ("VULNERABILITY"."CWE" = "CWE"."ID") LEFT JOIN "ANALYSIS" ON ("COMPONENT"."ID" = "ANALYSIS"."COMPONENT_ID") AND ("VULNERABILITY"."ID" = "ANALYSIS"."VULNERABILITY_ID") AND ("COMPONENT"."PROJECT_ID" = "ANALYSIS"."PROJECT_ID") WHERE "COMPONENT"."PROJECT_ID" = ?".
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:542)
	at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:456)
	at org.datanucleus.api.jdo.JDOQuery.executeList(JDOQuery.java:345)
	at org.dependencytrack.persistence.QueryManager.getFindings(QueryManager.java:2125)
	at org.dependencytrack.resources.v1.FindingResource.getFindingsByProject(FindingResource.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	... 44 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table "VULNERABILITY"
  Position: 1122
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeQuery(ParamLoggingPreparedStatement.java:375)
	at org.datanucleus.store.rdbms.SQLController.executeStatementQuery(SQLController.java:545)
	at org.datanucleus.store.rdbms.query.SQLQuery.performExecute(SQLQuery.java:651)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1973)
	at org.datanucleus.store.rdbms.query.SQLQuery.executeWithArray(SQLQuery.java:805)
	at org.datanucleus.api.jdo.JDOQuery.executeInternal(JDOQuery.java:433)
	... 69 common frames omitted


Error on Jenkins

`2020-11-11 06:40:22.210+0000 [id=299]	WARNING	h.m.AbstractBuild$AbstractBuildExecution#reportError: Step ‘Publish BOM to Dependency-Track’ aborted due to exception: 
org.jenkinsci.plugins.DependencyTrack.ApiClientException: An error occurred while retrieving findings - HTTP response code: 500 Server Error
	at org.jenkinsci.plugins.DependencyTrack.ApiClient.getFindings(ApiClient.java:95)
Caused: org.jenkinsci.plugins.DependencyTrack.ApiClientException: An error occurred while retrieving findings
	at org.jenkinsci.plugins.DependencyTrack.ApiClient.getFindings(ApiClient.java:98)
	at org.jenkinsci.plugins.DependencyTrack.DependencyTrackPublisher.perform(DependencyTrackPublisher.java:230)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:112)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1919)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
`
```

### Current Behavior:

Throws Error on logs when push bom for analysis.

### Steps to Reproduce:
Start application,
Run Build on Jenkins and push the bom for analysis,
Jenkins shows error Http 500

### Expected Behavior:

Should return the analysis detail back to Jenkins, so Jenkins can show details against the build job.

### Environment:
  
  - Dependency-Track Version: 4 beta 1 (https://github.com/DependencyTrack/dependency-track/releases/tag/4.0.0-beta.1)
  - Distribution: [ Executable WAR ]
  - BOM Format & Version: 
  - Database Server: [ PostgreSQL ]
  - Browser: 

### Additional Details:

[](url)

**Comment by rvsoni** [comment]
#593 is the fix for this issue, 

Ravi

**Comment by rvsoni** [comment]
Tested on 4.0.0-beta.2 release, it looks good, 

Thanks
