### ISSUE TITLE
Object with id "149316" is managed by a different persistence manager

### ISSUE THREAD

**Issue by rvsoni** [DependencyTrack/dependency-track#848]
The defect may already be reported! Please search for the defect before creating one.

### Current Behavior:
Error throws on analysis new project, 

```

09:36:23.746 INFO [BomUploadProcessingTask] Processing CycloneDX BOM uploaded to project: 85bfefa0-347f-48ee-8bd5-d5e7b835429d
--
09:36:26.556 INFO [BomUploadProcessingTask] Processed 198 components uploaded to project 85bfefa0-347f-48ee-8bd5-d5e7b835429d
09:36:37.443 INFO [InternalAnalysisTask] Starting internal analysis task
09:36:37.683 INFO [InternalAnalysisTask] Internal analysis complete
09:36:37.687 INFO [OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
09:36:37.719 ERROR [VulnerabilityAnalysisTask] An unexpected error occurred performing a vulnerability analysis task
org.datanucleus.exceptions.NucleusUserException: Object with id "149316" is managed by a different persistence manager
at org.datanucleus.ExecutionContextImpl.findObjectProvider(ExecutionContextImpl.java:1276)
at org.datanucleus.store.rdbms.scostore.ElementContainerStore.validateElementForWriting(ElementContainerStore.java:283)
at org.datanucleus.store.rdbms.scostore.JoinListStore.internalAdd(JoinListStore.java:200)
at org.datanucleus.store.rdbms.scostore.AbstractListStore.add(AbstractListStore.java:113)
at org.datanucleus.store.types.wrappers.backed.List.add(List.java:647)
at org.dependencytrack.model.Component.addVulnerability(Component.java:593)
at org.dependencytrack.persistence.QueryManager.addVulnerability(QueryManager.java:1402)
at org.dependencytrack.persistence.QueryManager.addVulnerability(QueryManager.java:1388)
at org.dependencytrack.tasks.scanners.BaseComponentAnalyzerTask.applyAnalysisFromCache(BaseComponentAnalyzerTask.java:156)
at org.dependencytrack.tasks.scanners.OssIndexAnalysisTask.analyze(OssIndexAnalysisTask.java:164)
at org.dependencytrack.tasks.scanners.OssIndexAnalysisTask.inform(OssIndexAnalysisTask.java:112)
at org.dependencytrack.tasks.VulnerabilityAnalysisTask.performAnalysis(VulnerabilityAnalysisTask.java:146)
at org.dependencytrack.tasks.VulnerabilityAnalysisTask.inform(VulnerabilityAnalysisTask.java:103)
at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
09:36:37.721 INFO [PolicyEngine] Evaluating 198 component(s) against applicable policies
09:36:38.293 INFO [PolicyEngine] Policy analysis complete
```

### Environment:
  
  - Dependency-Track Version: Docker, Snapshot version (4 beta 3) https://hub.docker.com/layers/owasp/dependency-track/snapshot/images/sha256-015a86d6ca7149bfb928f893a22c998aec0ad748a6f4494379ec9eff92384cfe?context=explore
  - Distribution: [ Docker  ]
  - BOM Format & Version: 
  - Database Server: [ PostgreSQL ]
  - Browser: FF Linux

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rvsoni** [comment]
After this exception non of analysis works, all are gettig same error in processing.

**Comment by rvsoni** [comment]
Thanks for fixing this, i don't see this error any more, tested on SNAPSHOT docker, postgresql

**Comment by stevespringett** [comment]
Glad it's working. Closing. Reopen if you see it again. Cheers
