### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint 

### ISSUE THREAD

**Issue by rvsoni** [DependencyTrack/dependency-track#858]
The defect may already be reported! Please search for the defect before creating one.
Upload BOM for analysis, 

Bom is created using multile module maven project.

modules are inter dependant, 

### Current Behavior:
Throws SQL Exception
```

11:22:39.338 INFO [BomUploadProcessingTask] Processed 298 components uploaded to project b8593720-e372-475e-bee4-3e54d64bc486
11:22:50.993 WARN [Persist] Insert of object "org.dependencytrack.model.RepositoryMetaComponent@661f19e2" using statement "INSERT INTO "REPOSITORY_META_COMPONENT" ("LAST_CHECK","LATEST_VERSION","NAME","NAMESPACE","PUBLISHED","REPOSITORY_TYPE") VALUES (?,?,?,?,?,?)" failed : ERROR: duplicate key value violates unique constraint "REPOSITORY_META_COMPONENT_COMPOUND_IDX"
  Detail: Key ("REPOSITORY_TYPE", "NAMESPACE", "NAME")=(MAVEN, com.i.t, tr-war) already exists.
11:22:51.000 WARN [General] ExecutionContext closed with active transaction, so rolling back the active transaction
11:22:51.001 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
javax.jdo.JDODataStoreException: Insert of object "org.dependencytrack.model.RepositoryMetaComponent@661f19e2" using statement "INSERT INTO "REPOSITORY_META_COMPONENT" ("LAST_CHECK","LATEST_VERSION","NAME","NAMESPACE","PUBLISHED","REPOSITORY_TYPE") VALUES (?,?,?,?,?,?)" failed : ERROR: duplicate key value violates unique constraint "REPOSITORY_META_COMPONENT_COMPOUND_IDX"
  Detail: Key ("REPOSITORY_TYPE", "NAMESPACE", "NAME")=(MAVEN, com.i.t, tr-war) already exists.
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:542)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:717)
	at org.datanucleus.api.jdo.JDOPersistenceManager.makePersistent(JDOPersistenceManager.java:738)
	at alpine.persistence.AbstractAlpineQueryManager.persist(AbstractAlpineQueryManager.java:398)
	at org.dependencytrack.persistence.QueryManager.synchronizeRepositoryMetaComponent(QueryManager.java:2470)
	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.analyze(RepositoryMetaAnalyzerTask.java:107)
	at org.dependencytrack.tasks.repositories.RepositoryMetaAnalyzerTask.inform(RepositoryMetaAnalyzerTask.java:52)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "REPOSITORY_META_COMPONENT_COMPOUND_IDX"
  Detail: Key ("REPOSITORY_TYPE", "NAMESPACE", "NAME")=(MAVEN, com.i.t, tr-war) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2578)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2313)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:331)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeUpdate(ParamLoggingPreparedStatement.java:393)
	at org.datanucleus.store.rdbms.SQLController.executeStatementUpdate(SQLController.java:435)
	at org.datanucleus.store.rdbms.request.InsertRequest.execute(InsertRequest.java:479)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObjectInTable(RDBMSPersistenceHandler.java:162)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.insertObject(RDBMSPersistenceHandler.java:138)
	at org.datanucleus.state.StateManagerImpl.internalMakePersistent(StateManagerImpl.java:4569)
	at org.datanucleus.state.StateManagerImpl.makePersistent(StateManagerImpl.java:4546)
	at org.datanucleus.ExecutionContextImpl.persistObjectInternal(ExecutionContextImpl.java:2026)
	at org.datanucleus.ExecutionContextImpl.persistObjectWork(ExecutionContextImpl.java:1869)
	at org.datanucleus.ExecutionContextImpl.persistObject(ExecutionContextImpl.java:1724)
	at org.datanucleus.api.jdo.JDOPersistenceManager.jdoMakePersistent(JDOPersistenceManager.java:712)
	... 9 common frames omitted
11:22:52.331 INFO [InternalAnalysisTask] Starting internal analysis task
11:22:52.720 INFO [InternalAnalysisTask] Internal analysis complete
11:22:52.725 INFO [OssIndexAnalysisTask] Starting Sonatype OSS Index analysis task
11:23:36.484 INFO [OssIndexAnalysisTask] Analyzing 78 component(s)
11:24:25.059 INFO [OssIndexAnalysisTask] Analyzing 85 component(s)
11:25:00.637 WARN [Persistence] Exception thrown by StateManager.isLoaded for field=12 of StateManager[pc=org.dependencytrack.model.Project@5915e524, lifecycle=P_NONTRANS] : This statement has been closed.
11:25:00.637 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
javax.jdo.JDODataStoreException: Iteration request failed : SELECT 'org.dependencytrack.model.ProjectProperty' AS "DN_TYPE","A0"."DESCRIPTION","A0"."GROUPNAME" AS "NUCORDER0","A0"."ID","A0"."PROPERTYNAME" AS "NUCORDER1","A0"."PROPERTYTYPE","A0"."PROPERTYVALUE" FROM "PROJECT_PROPERTY" "A0" WHERE "A0"."PROJECT_ID" = ? ORDER BY "NUCORDER0","NUCORDER1"
	at org.datanucleus.api.jdo.NucleusJDOHelper.getJDOExceptionForNucleusException(NucleusJDOHelper.java:542)
	at org.datanucleus.api.jdo.JDOAdapter.getApiExceptionForNucleusException(JDOAdapter.java:543)
	at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:4128)
	at org.dependencytrack.model.Project.dnGetuuid(Project.java)
	at org.dependencytrack.model.Project.getUuid(Project.java:207)
	at org.dependencytrack.util.NotificationUtil.toJson(NotificationUtil.java:196)
	at org.dependencytrack.util.NotificationUtil.toJson(NotificationUtil.java:276)
	at org.dependencytrack.notification.publisher.Publisher.prepareTemplate(Publisher.java:72)
	at org.dependencytrack.notification.publisher.SendMailPublisher.inform(SendMailPublisher.java:53)
	at org.dependencytrack.notification.NotificationRouter.inform(NotificationRouter.java:64)
	at alpine.notification.NotificationService.lambda$alertSubscriber$0(NotificationService.java:100)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: This statement has been closed.
	at org.postgresql.jdbc.PgStatement.checkClosed(PgStatement.java:709)
	at org.postgresql.jdbc.PgStatement.getMaxRows(PgStatement.java:510)
	at org.postgresql.jdbc.PgStatement.createResultSet(PgStatement.java:154)
	at org.postgresql.jdbc.PgStatement$StatementResultHandler.handleResultRows(PgStatement.java:205)
	at org.postgresql.core.ResultHandlerDelegate.handleResultRows(ResultHandlerDelegate.java:29)
	at org.postgresql.core.v3.QueryExecutorImpl$1.handleResultRows(QueryExecutorImpl.java:580)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2256)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:331)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:109)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.datanucleus.store.rdbms.ParamLoggingPreparedStatement.executeQuery(ParamLoggingPreparedStatement.java:375)
	at org.datanucleus.store.rdbms.SQLController.executeStatementQuery(SQLController.java:553)
	at org.datanucleus.store.rdbms.scostore.FKListStore.listIterator(FKListStore.java:1138)
	at org.datanucleus.store.rdbms.scostore.AbstractListStore.listIterator(AbstractListStore.java:92)
	at org.datanucleus.store.rdbms.scostore.AbstractListStore.iterator(AbstractListStore.java:82)
	at org.datanucleus.store.types.wrappers.backed.List.loadFromStore(List.java:267)
	at org.datanucleus.store.types.wrappers.backed.List.initialise(List.java:216)
	at org.datanucleus.store.types.TypeManagerImpl.createSCOInstance(TypeManagerImpl.java:471)
	at org.datanucleus.store.rdbms.mapping.java.AbstractContainerMapping.replaceFieldWithWrapper(AbstractContainerMapping.java:442)
	at org.datanucleus.store.rdbms.mapping.java.AbstractContainerMapping.postFetch(AbstractContainerMapping.java:459)
	at org.datanucleus.store.rdbms.request.FetchRequest.execute(FetchRequest.java:503)
	at org.datanucleus.store.rdbms.RDBMSPersistenceHandler.fetchObject(RDBMSPersistenceHandler.java:316)
	at org.datanucleus.state.StateManagerImpl.loadFieldsFromDatastore(StateManagerImpl.java:1542)
	at org.datanucleus.state.StateManagerImpl.refreshLoadedFields(StateManagerImpl.java:4043)
	at org.datanucleus.api.jdo.state.PersistentNontransactional.transitionReadField(PersistentNontransactional.java:156)
	at org.datanucleus.state.StateManagerImpl.transitionReadField(StateManagerImpl.java:1038)
	at org.datanucleus.state.StateManagerImpl.isLoaded(StateManagerImpl.java:4091)
	... 11 common frames omitted
11:25:16.935 INFO [OssIndexAnalysisTask] Analyzing 93 component(s)
```

### Environment:
  
  - Dependency-Track Version: 4 beta 3 (snapshot)
  - Distribution: Docker 
  - BOM Format & Version:
  - Database Server: PostgreSQL 
  - Browser: Any

### Additional Details:

(e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by stevespringett** [comment]
I haven't been able to replicate this, but I think I understand why its happening and have committed a potential fix. It would be great if you could test and validate if this is resolved or not.

**Comment by rvsoni** [comment]
Thanks for quickly fixing this, i just tested on latest snapshot docker, and this looks good, i dont see this error any more, 

Thanks,

**Comment by stevespringett** [comment]
Fantastic. Thanks for testing. Closing. Reopen if you see it again. Cheers

**Comment by mk3rnb8** [comment]
Looks like there is a regression... 

DpT version 4.2.2

2021-06-23 10:22:37.971 UTC [5481] ERROR:  duplicate key value violates unique constraint "REPOSITORY_META_COMPONENT_COMPOUND_IDX"
2021-06-23 10:22:37.971 UTC [5481] DETAIL:  Key ("REPOSITORY_TYPE", "NAMESPACE", "NAME")=(MAVEN, org.openjfx, javafx-swing) already exists.
2021-06-23 10:22:37.971 UTC [5481] STATEMENT:  INSERT INTO "REPOSITORY_META_COMPONENT" ("LAST_CHECK","LATEST_VERSION","NAME","NAMESPACE","PUBLISHED","REPOSITORY_TYPE") VALUES ($1,$2,$3,$4,$5,$6)
	RETURNING *
2021-06-23 10:22:37.998 UTC [5479] ERROR:  duplicate key value violates unique constraint "REPOSITORY_META_COMPONENT_COMPOUND_IDX"
2021-06-23 10:22:37.998 UTC [5479] DETAIL:  Key ("REPOSITORY_TYPE", "NAMESPACE", "NAME")=(MAVEN, org.openjfx, javafx-fxml) already exists.
2021-06-23 10:22:37.998 UTC [5479] STATEMENT:  INSERT INTO "REPOSITORY_META_COMPONENT" ("LAST_CHECK","LATEST_VERSION","NAME","NAMESPACE","PUBLISHED","REPOSITORY_TYPE") VALUES ($1,$2,$3,$4,$5,$6)
	RETURNING *
