### ISSUE TITLE
Errors in logs :  An I/O error has occurred while writing a response message entity to the container output stream

### ISSUE THREAD

**Issue by Whisper40** [DependencyTrack/dependency-track#868]
### Current Behavior:
Errors appears in logs 

### Steps to Reproduce:
Fresh install with a war and a mysql database
Activate OSS index , api key....
Upload some projects into it
Go to your log and wait few minutes

### Expected Behavior:
No errors

### Environment:
  
  - Dependency-Track Version: 3.8
  - Distribution: Executable WAR  ]
  - BOM Format & Version: 1.1
  - Database Server: [ MySQL]
  - Browser: Chrome Latest

### Additional Details:
```

10:55:42.108 INFO [InternalAnalysisTask] Starting internal analysis task
--
  | 10:55:42.193 INFO [InternalAnalysisTask] Internal analysis complete
  | 10:55:42.234 INFO [MetricsUpdateTask] Executing metrics update for project: 5ab4c642-f916-42c0-bc37-52cce22810b6
  | 10:57:31.505 ERROR [ServerRuntime$Responder] An I/O error has occurred while writing a response message entity to the container output stream.
  | org.glassfish.jersey.server.internal.process.MappableException: org.eclipse.jetty.io.EofException
  | at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:67)
  | at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
  | at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1115)
  | at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:638)
  | at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:371)
  | at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:361)
  | at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:256)
  | at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
  | at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
  | at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
  | at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
  | at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
  | at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
  | at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
  | at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
  | at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
  | at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
  | at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
  | at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
  | at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
  | at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1395)
  | at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
  | at alpine.filters.ContentSecurityPolicyFilter.doFilter(ContentSecurityPolicyFilter.java:224)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
  | at alpine.filters.ClickjackingFilter.doFilter(ClickjackingFilter.java:92)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
  | at alpine.filters.WhitelistUrlFilter.doFilter(WhitelistUrlFilter.java:149)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1596)
  | at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
  | at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
  | at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  | at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1300)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  | at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
  | at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  | at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1215)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  | at org.eclipse.jetty.server.Server.handle(Server.java:500)
  | at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
  | at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
  | at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
  | at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
  | at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
  | at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
  | at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
  | at java.lang.Thread.run(Thread.java:748)
  | Caused by: org.eclipse.jetty.io.EofException: null
  | at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:283)
  | at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:422)
  | at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
  | at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:381)
  | at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:821)
  | at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
  | at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
  | at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:549)
  | at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:824)
  | at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:901)
  | at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:283)
  | at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:267)
  | at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:705)
  | at com.compuware.apm.agent.introspection.uem.impl.AgentInjectingServletOutputStream.flush(AgentInjectingServletOutputStream.java:209)
  | at org.glassfish.jersey.servlet.internal.ResponseWriter$NonCloseableOutputStreamWrapper.flush(ResponseWriter.java:306)
  | at org.glassfish.jersey.message.internal.CommittingOutputStream.flush(CommittingOutputStream.java:263)
  | at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.flush(WriterInterceptorExecutor.java:281)
  | at com.fasterxml.jackson.core.json.UTF8JsonGenerator.flush(UTF8JsonGenerator.java:1153)
  | at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:923)
  | at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:648)
  | at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
  | at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
  | at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
  | at alpine.filters.GZipInterceptor.aroundWriteTo(GZipInterceptor.java:78)
  | at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
  | at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:85)
  | at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
  | at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:61)
  | ... 59 common frames omitted
  | Caused by: java.io.IOException: Connection reset by peer
  | at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
  | at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
  | at sun.nio.ch.IOUtil.write(IOUtil.java:148)
  | at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
  | at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:263)
  | ... 86 common frames omitted
  | 11:00:33.839 INFO [MetricsUpdateTask] Completed metrics update for project: 5ab4c642-f916-42c0-bc37-52cce22810b6
  | 11:00:50.114 INFO [MetricsUpdateTask] Completed metrics update for project: 5ab4c642-f916-42c0-bc37-52cce22810b6


```

**Comment by stevespringett** [comment]
This is a "Connection reset by peer" exception. It is common in Java and occurs whenever a client abruptly terminates a connection. This could be caused by the browser of a user disconnecting in the middle of a transaction, or can also be a result of one of the integrations that DT integrates with (NPM, OSS Index, Maven Central, etc) disconnecting prematurely.

Regardless, this is not an error in DT. Most of the time, this error can be ignored. However, in some cases, organizational proxy servers, infrastructure firewalls, etc, can actually cause these issues if they're not configured correctly.
