### ISSUE TITLE
4.0.0 / Docker API server image: java.lang.IllegalArgumentException: Could not load codec 'Lucene84'

### ISSUE THREAD

**Issue by cnocula-i** [DependencyTrack/dependency-track#888]
### Current Behavior:
When launching the docker image for the API server and/or invoking the API, the logs are spammed with this exception for a missing Lucene codec:
`java.lang.IllegalArgumentException: Could not load codec 'Lucene84'.  Did you forget to add lucene-backward-codecs.jar?`

### Steps to Reproduce:
Launch the Docker image.

### Expected Behavior:
Graceful handling or no error stacktraces.

### Environment:
  
  - Dependency-Track Version: 4.0.0 (dependencytrack/apiserver:4.0.0)
  - Distribution: [ Docker ]
  - BOM Format & Version: n/a
  - Database Server: [ PostgreSQL ]
  - Browser: n/a

### Additional Details:
```
08:57:46.015 ERROR [LoggableUncaughtExceptionHandler] An unknown error occurred in an asynchronous event or notification thread
java.lang.IllegalArgumentException: Could not load codec 'Lucene84'.  Did you forget to add lucene-backward-codecs.jar?
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:449)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:356)
	at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:291)
	at org.apache.lucene.index.IndexWriter.<init>(IndexWriter.java:1037)
	at org.dependencytrack.search.IndexManager.openIndex(IndexManager.java:144)
	at org.dependencytrack.search.IndexManager.getIndexWriter(IndexManager.java:155)
	at org.dependencytrack.search.ComponentIndexer.add(ComponentIndexer.java:78)
	at org.dependencytrack.search.ComponentIndexer.add(ComponentIndexer.java:42)
	at org.dependencytrack.tasks.IndexTask.inform(IndexTask.java:49)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: org.apache.lucene.index.CorruptIndexException: checksum passed (4765dbdd). possibly transient resource issue, or a Lucene or JVM bug (resource=BufferedChecksumIndexInput(SimpleFSIndexInput(path="/data/.dependency-track/index/component/segments_1pv")))
		at org.apache.lucene.codecs.CodecUtil.checkFooter(CodecUtil.java:466)
		at org.apache.lucene.index.SegmentInfos.readCommit(SegmentInfos.java:434)
		... 11 common frames omitted
Caused by: java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene84' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [Lucene87]
	at org.apache.lucene.util.NamedSPILoader.lookup(NamedSPILoader.java:116)
	at org.apache.lucene.codecs.Codec.forName(Codec.java:116)
	at org.apache.lucene.index.SegmentInfos.readCodec(SegmentInfos.java:445)
	... 12 common frames omitted
```

**Comment by stevespringett** [comment]
This needs to be documented in the migration instructions. Users will need to delete the dependency-track/index directory. 

However, please note that if this directory exists, I'm assuming you're already using Dependency-Track? If so, the migration isn't complete yet, so it's not possible to move from 3.x to 4.0 at this time. Please see https://docs.dependencytrack.org/changelog/

**Comment by cnocula-i** [comment]
Yes, we were using DT 3.8.0 before (running in a Kubernetes cluster with a persistent volume under the hood + an external PostgreSQL), so I launched the image + version on top of that volume.
