### ISSUE TITLE
About Fortify SSC 20.2 Integration

### ISSUE THREAD

**Issue by aykutaricioglu** [DependencyTrack/dependency-track#910]
Hello,

I get the following error when I integrate DependencyTrack with Fortify. How can i fix this problem?

2021-01-28 16:09:27,091 [] ERROR [org.dependencytrack.integrations.fortifyssc.FortifySscUploader] An error occurred with the Fortify SSC integration point
javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
	at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2164)
	at alpine.crypto.DataEncryption.decryptAsBytes(DataEncryption.java:136)
	at alpine.crypto.DataEncryption.decryptAsBytes(DataEncryption.java:148)
	at alpine.crypto.DataEncryption.decryptAsString(DataEncryption.java:176)
	at org.dependencytrack.integrations.fortifyssc.FortifySscUploader.upload(FortifySscUploader.java:84)
	at org.dependencytrack.tasks.VulnerabilityManagementUploadTask.processProjectFindings(VulnerabilityManagementUploadTask.java:65)
	at org.dependencytrack.tasks.VulnerabilityManagementUploadTask.inform(VulnerabilityManagementUploadTask.java:45)
	at org.dependencytrack.tasks.FortifySscUploadTask.inform(FortifySscUploadTask.java:37)
	at alpine.event.framework.BaseEventService.lambda$publish$0(BaseEventService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by stevespringett** [comment]
Fortify broke existing API contacts in v20.1.0. This is a known problem. All tools that integrate with SSC have to update how the integrate.

Please see #700
